// This file is generated automatically. DO NOT EDIT.
// Catalog of Gunold Sulky colors
import 'package:thread_digit/colors/model/thread_color.dart';

const List<ThreadColor> gunoldSulkyColors = [
  ThreadColor(
    code: "501",
    catalog: "Gunold Sulky",
    name: "Khaki Beige",
    red: 180,
    green: 185,
    blue: 165,
  ),
  ThreadColor(
    code: "502",
    catalog: "Gunold Sulky",
    name: "Cornsilk",
    red: 239,
    green: 200,
    blue: 16,
  ),
  ThreadColor(
    code: "505",
    catalog: "Gunold Sulky",
    name: "Deep Arctic Sky",
    red: 12,
    green: 8,
    blue: 45,
  ),
  ThreadColor(
    code: "508",
    catalog: "Gunold Sulky",
    name: "Flesh",
    red: 249,
    green: 230,
    blue: 202,
  ),
  ThreadColor(
    code: "520",
    catalog: "Gunold Sulky",
    name: "Light Cream",
    red: 253,
    green: 243,
    blue: 218,
  ),
  ThreadColor(
    code: "521",
    catalog: "Gunold Sulky",
    name: "Tiger Eye",
    red: 178,
    green: 108,
    blue: 41,
  ),
  ThreadColor(
    code: "523",
    catalog: "Gunold Sulky",
    name: "Autumn Gold",
    red: 231,
    green: 144,
    blue: 2,
  ),
  ThreadColor(
    code: "524",
    catalog: "Gunold Sulky",
    name: "Dk. Navy",
    red: 34,
    green: 3,
    blue: 39,
  ),
  ThreadColor(
    code: "525",
    catalog: "Gunold Sulky",
    name: "English Green",
    red: 52,
    green: 72,
    blue: 30,
  ),
  ThreadColor(
    code: "526",
    catalog: "Gunold Sulky",
    name: "Cobalt Blue",
    red: 20,
    green: 64,
    blue: 135,
  ),
  ThreadColor(
    code: "534",
    catalog: "Gunold Sulky",
    name: "Purple Ice",
    red: 120,
    green: 20,
    blue: 60,
  ),
  ThreadColor(
    code: "535",
    catalog: "Gunold Sulky",
    name: "Burgundy",
    red: 125,
    green: 38,
    blue: 42,
  ),
  ThreadColor(
    code: "538",
    catalog: "Gunold Sulky",
    name: "Enchanted Sea",
    red: 48,
    green: 91,
    blue: 78,
  ),
  ThreadColor(
    code: "542",
    catalog: "Gunold Sulky",
    name: "Gold/Yellow",
    red: 255,
    green: 255,
    blue: 0,
  ),
  ThreadColor(
    code: "561",
    catalog: "Gunold Sulky",
    name: "Lipstick",
    red: 225,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "562",
    catalog: "Gunold Sulky",
    name: "Spice",
    red: 230,
    green: 173,
    blue: 98,
  ),
  ThreadColor(
    code: "567",
    catalog: "Gunold Sulky",
    name: "Butterfly Gold",
    red: 243,
    green: 160,
    blue: 1,
  ),
  ThreadColor(
    code: "568",
    catalog: "Gunold Sulky",
    name: "Cinnamon",
    red: 230,
    green: 109,
    blue: 0,
  ),
  ThreadColor(
    code: "569",
    catalog: "Gunold Sulky",
    name: "Garden Green",
    red: 22,
    green: 95,
    blue: 40,
  ),
  ThreadColor(
    code: "570",
    catalog: "Gunold Sulky",
    name: "Bright Green",
    red: 55,
    green: 140,
    blue: 55,
  ),
  ThreadColor(
    code: "571",
    catalog: "Gunold Sulky",
    name: "Deep Aqua",
    red: 8,
    green: 142,
    blue: 108,
  ),
  ThreadColor(
    code: "572",
    catalog: "Gunold Sulky",
    name: "Blue Ribbon",
    red: 16,
    green: 10,
    blue: 124,
  ),
  ThreadColor(
    code: "580",
    catalog: "Gunold Sulky",
    name: "Mint Julep",
    red: 53,
    green: 105,
    blue: 61,
  ),
  ThreadColor(
    code: "607",
    catalog: "Gunold Sulky",
    name: "Deep Rose",
    red: 150,
    green: 60,
    blue: 70,
  ),
  ThreadColor(
    code: "610",
    catalog: "Gunold Sulky",
    name: "GS Gray",
    red: 149,
    green: 149,
    blue: 139,
  ),
  ThreadColor(
    code: "614",
    catalog: "Gunold Sulky",
    name: "Chestnut",
    red: 109,
    green: 48,
    blue: 7,
  ),
  ThreadColor(
    code: "619",
    catalog: "Gunold Sulky",
    name: "Dusty Peach",
    red: 233,
    green: 189,
    blue: 150,
  ),
  ThreadColor(
    code: "621",
    catalog: "Gunold Sulky",
    name: "Sunset",
    red: 205,
    green: 57,
    blue: 0,
  ),
  ThreadColor(
    code: "622",
    catalog: "Gunold Sulky",
    name: "Blond",
    red: 248,
    green: 212,
    blue: 138,
  ),
  ThreadColor(
    code: "630",
    catalog: "Gunold Sulky",
    name: "Moss Green",
    red: 119,
    green: 113,
    blue: 19,
  ),
  ThreadColor(
    code: "640",
    catalog: "Gunold Sulky",
    name: "Med. Aqua",
    red: 28,
    green: 111,
    blue: 81,
  ),
  ThreadColor(
    code: "643",
    catalog: "Gunold Sulky",
    name: "Arctic Sky",
    red: 38,
    green: 35,
    blue: 69,
  ),
  ThreadColor(
    code: "670",
    catalog: "Gunold Sulky",
    name: "Sepia",
    red: 74,
    green: 38,
    blue: 41,
  ),
  ThreadColor(
    code: "677",
    catalog: "Gunold Sulky",
    name: "Orange Slice",
    red: 255,
    green: 110,
    blue: 0,
  ),
  ThreadColor(
    code: "688",
    catalog: "Gunold Sulky",
    name: "Pale Green/Yellow",
    red: 201,
    green: 154,
    blue: 107,
  ),
  ThreadColor(
    code: "817",
    catalog: "Gunold Sulky",
    name: "Pale Mint Green",
    red: 145,
    green: 235,
    blue: 195,
  ),
  ThreadColor(
    code: "836",
    catalog: "Gunold Sulky",
    name: "Cocoa Mulch",
    red: 220,
    green: 210,
    blue: 175,
  ),
  ThreadColor(
    code: "861",
    catalog: "Gunold Sulky",
    name: "Pale Purple",
    red: 70,
    green: 135,
    blue: 180,
  ),
  ThreadColor(
    code: "868",
    catalog: "Gunold Sulky",
    name: "Popcorn",
    red: 235,
    green: 210,
    blue: 120,
  ),
  ThreadColor(
    code: "1001",
    catalog: "Gunold Sulky",
    name: "Bright White",
    red: 249,
    green: 249,
    blue: 255,
  ),
  ThreadColor(
    code: "1002",
    catalog: "Gunold Sulky",
    name: "Soft White",
    red: 249,
    green: 249,
    blue: 244,
  ),
  ThreadColor(
    code: "1005",
    catalog: "Gunold Sulky",
    name: "Black",
    red: 0,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1011",
    catalog: "Gunold Sulky",
    name: "Steel Gray",
    red: 183,
    green: 169,
    blue: 172,
  ),
  ThreadColor(
    code: "1015",
    catalog: "Gunold Sulky",
    name: "Med. Peach",
    red: 225,
    green: 175,
    blue: 154,
  ),
  ThreadColor(
    code: "1016",
    catalog: "Gunold Sulky",
    name: "Pastel Coral",
    red: 236,
    green: 150,
    blue: 140,
  ),
  ThreadColor(
    code: "1017",
    catalog: "Gunold Sulky",
    name: "Pastel Peach",
    red: 244,
    green: 220,
    blue: 202,
  ),
  ThreadColor(
    code: "1019",
    catalog: "Gunold Sulky",
    name: "Peach",
    red: 236,
    green: 160,
    blue: 130,
  ),
  ThreadColor(
    code: "1020",
    catalog: "Gunold Sulky",
    name: "Dark Peach",
    red: 240,
    green: 130,
    blue: 120,
  ),
  ThreadColor(
    code: "1021",
    catalog: "Gunold Sulky",
    name: "Maple",
    red: 235,
    green: 102,
    blue: 2,
  ),
  ThreadColor(
    code: "1022",
    catalog: "Gunold Sulky",
    name: "Cream",
    red: 255,
    green: 247,
    blue: 213,
  ),
  ThreadColor(
    code: "1023",
    catalog: "Gunold Sulky",
    name: "Yellow",
    red: 255,
    green: 230,
    blue: 105,
  ),
  ThreadColor(
    code: "1024",
    catalog: "Gunold Sulky",
    name: "Goldenrod",
    red: 255,
    green: 184,
    blue: 0,
  ),
  ThreadColor(
    code: "1025",
    catalog: "Gunold Sulky",
    name: "Mine Gold",
    red: 215,
    green: 128,
    blue: 0,
  ),
  ThreadColor(
    code: "1028",
    catalog: "Gunold Sulky",
    name: "Baby Blue",
    red: 190,
    green: 195,
    blue: 225,
  ),
  ThreadColor(
    code: "1029",
    catalog: "Gunold Sulky",
    name: "Med. Blue",
    red: 160,
    green: 195,
    blue: 235,
  ),
  ThreadColor(
    code: "1030",
    catalog: "Gunold Sulky",
    name: "Periwinkle",
    red: 166,
    green: 162,
    blue: 198,
  ),
  ThreadColor(
    code: "1031",
    catalog: "Gunold Sulky",
    name: "Med. Orchid",
    red: 223,
    green: 190,
    blue: 200,
  ),
  ThreadColor(
    code: "1032",
    catalog: "Gunold Sulky",
    name: "Med. Purple",
    red: 230,
    green: 140,
    blue: 235,
  ),
  ThreadColor(
    code: "1033",
    catalog: "Gunold Sulky",
    name: "Dk. Orchid",
    red: 216,
    green: 100,
    blue: 150,
  ),
  ThreadColor(
    code: "1034",
    catalog: "Gunold Sulky",
    name: "Burgundy",
    red: 198,
    green: 50,
    blue: 60,
  ),
  ThreadColor(
    code: "1035",
    catalog: "Gunold Sulky",
    name: "Dk. Burgundy",
    red: 121,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1036",
    catalog: "Gunold Sulky",
    name: "Tawny Brown",
    red: 122,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1037",
    catalog: "Gunold Sulky",
    name: "Lt. Red",
    red: 249,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1039",
    catalog: "Gunold Sulky",
    name: "Christmas Red",
    red: 235,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1040",
    catalog: "Gunold Sulky",
    name: "Med. Dk. Khaki",
    red: 135,
    green: 115,
    blue: 117,
  ),
  ThreadColor(
    code: "1041",
    catalog: "Gunold Sulky",
    name: "Med. Dk. Gray",
    red: 127,
    green: 127,
    blue: 127,
  ),
  ThreadColor(
    code: "1042",
    catalog: "Gunold Sulky",
    name: "Bright Navy Blue",
    red: 50,
    green: 30,
    blue: 80,
  ),
  ThreadColor(
    code: "1043",
    catalog: "Gunold Sulky",
    name: "Dk. Navy",
    red: 25,
    green: 5,
    blue: 37,
  ),
  ThreadColor(
    code: "1044",
    catalog: "Gunold Sulky",
    name: "Midnight Blue",
    red: 29,
    green: 6,
    blue: 47,
  ),
  ThreadColor(
    code: "1045",
    catalog: "Gunold Sulky",
    name: "Lt. Teal",
    red: 195,
    green: 239,
    blue: 191,
  ),
  ThreadColor(
    code: "1046",
    catalog: "Gunold Sulky",
    name: "Teal",
    red: 46,
    green: 131,
    blue: 89,
  ),
  ThreadColor(
    code: "1047",
    catalog: "Gunold Sulky",
    name: "Mint Green",
    red: 166,
    green: 194,
    blue: 132,
  ),
  ThreadColor(
    code: "1049",
    catalog: "Gunold Sulky",
    name: "Grass Green",
    red: 66,
    green: 160,
    blue: 33,
  ),
  ThreadColor(
    code: "1051",
    catalog: "Gunold Sulky",
    name: "Christmas Green",
    red: 30,
    green: 100,
    blue: 25,
  ),
  ThreadColor(
    code: "1054",
    catalog: "Gunold Sulky",
    name: "Med. Dk. Ecru",
    red: 238,
    green: 190,
    blue: 174,
  ),
  ThreadColor(
    code: "1055",
    catalog: "Gunold Sulky",
    name: "Tawny Tan",
    red: 235,
    green: 188,
    blue: 128,
  ),
  ThreadColor(
    code: "1056",
    catalog: "Gunold Sulky",
    name: "Med. Tawny Tan",
    red: 175,
    green: 91,
    blue: 0,
  ),
  ThreadColor(
    code: "1057",
    catalog: "Gunold Sulky",
    name: "Chocolate",
    red: 100,
    green: 39,
    blue: 2,
  ),
  ThreadColor(
    code: "1058",
    catalog: "Gunold Sulky",
    name: "Dark brown",
    red: 102,
    green: 53,
    blue: 0,
  ),
  ThreadColor(
    code: "1059",
    catalog: "Gunold Sulky",
    name: "Dk. Tawny Brown",
    red: 55,
    green: 33,
    blue: 30,
  ),
  ThreadColor(
    code: "1061",
    catalog: "Gunold Sulky",
    name: "Pale Yellow",
    red: 255,
    green: 247,
    blue: 185,
  ),
  ThreadColor(
    code: "1063",
    catalog: "Gunold Sulky",
    name: "Pale Yellow-Green",
    red: 240,
    green: 248,
    blue: 236,
  ),
  ThreadColor(
    code: "1064",
    catalog: "Gunold Sulky",
    name: "Pale Peach",
    red: 230,
    green: 180,
    blue: 170,
  ),
  ThreadColor(
    code: "1065",
    catalog: "Gunold Sulky",
    name: "Orange Yellow",
    red: 255,
    green: 145,
    blue: 0,
  ),
  ThreadColor(
    code: "1066",
    catalog: "Gunold Sulky",
    name: "Primrose",
    red: 255,
    green: 241,
    blue: 128,
  ),
  ThreadColor(
    code: "1067",
    catalog: "Gunold Sulky",
    name: "Lemon Yellow",
    red: 255,
    green: 255,
    blue: 133,
  ),
  ThreadColor(
    code: "1068",
    catalog: "Gunold Sulky",
    name: "Pink Tint",
    red: 243,
    green: 219,
    blue: 217,
  ),
  ThreadColor(
    code: "1070",
    catalog: "Gunold Sulky",
    name: "Gold",
    red: 246,
    green: 206,
    blue: 105,
  ),
  ThreadColor(
    code: "1071",
    catalog: "Gunold Sulky",
    name: "Off White",
    red: 249,
    green: 249,
    blue: 234,
  ),
  ThreadColor(
    code: "1074",
    catalog: "Gunold Sulky",
    name: "Pale Powder Blue",
    red: 214,
    green: 213,
    blue: 232,
  ),
  ThreadColor(
    code: "1076",
    catalog: "Gunold Sulky",
    name: "Royal Blue",
    red: 90,
    green: 90,
    blue: 139,
  ),
  ThreadColor(
    code: "1077",
    catalog: "Gunold Sulky",
    name: "Jade Tint",
    red: 190,
    green: 205,
    blue: 200,
  ),
  ThreadColor(
    code: "1078",
    catalog: "Gunold Sulky",
    name: "Orange",
    red: 255,
    green: 102,
    blue: 0,
  ),
  ThreadColor(
    code: "1079",
    catalog: "Gunold Sulky",
    name: "Emerald Green",
    red: 23,
    green: 85,
    blue: 35,
  ),
  ThreadColor(
    code: "1080",
    catalog: "Gunold Sulky",
    name: "Orchid",
    red: 220,
    green: 130,
    blue: 160,
  ),
  ThreadColor(
    code: "1081",
    catalog: "Gunold Sulky",
    name: "Brick",
    red: 240,
    green: 110,
    blue: 120,
  ),
  ThreadColor(
    code: "1082",
    catalog: "Gunold Sulky",
    name: "Ecru",
    red: 247,
    green: 227,
    blue: 187,
  ),
  ThreadColor(
    code: "1083",
    catalog: "Gunold Sulky",
    name: "Spark Gold",
    red: 255,
    green: 193,
    blue: 0,
  ),
  ThreadColor(
    code: "1085",
    catalog: "Gunold Sulky",
    name: "Silver",
    red: 226,
    green: 207,
    blue: 199,
  ),
  ThreadColor(
    code: "1086",
    catalog: "Gunold Sulky",
    name: "Pale Sea Foam",
    red: 249,
    green: 249,
    blue: 224,
  ),
  ThreadColor(
    code: "1090",
    catalog: "Gunold Sulky",
    name: "Deep Peacock",
    red: 22,
    green: 98,
    blue: 95,
  ),
  ThreadColor(
    code: "1094",
    catalog: "Gunold Sulky",
    name: "Med. Turquoise",
    red: 38,
    green: 191,
    blue: 202,
  ),
  ThreadColor(
    code: "1095",
    catalog: "Gunold Sulky",
    name: "Turquoise",
    red: 16,
    green: 209,
    blue: 189,
  ),
  ThreadColor(
    code: "1096",
    catalog: "Gunold Sulky",
    name: "Dk. Turquoise",
    red: 15,
    green: 105,
    blue: 120,
  ),
  ThreadColor(
    code: "1100",
    catalog: "Gunold Sulky",
    name: "Lt. Grass Green",
    red: 194,
    green: 211,
    blue: 125,
  ),
  ThreadColor(
    code: "1101",
    catalog: "Gunold Sulky",
    name: "True Green",
    red: 9,
    green: 133,
    blue: 49,
  ),
  ThreadColor(
    code: "1103",
    catalog: "Gunold Sulky",
    name: "Dk. Khaki",
    red: 2,
    green: 20,
    blue: 15,
  ),
  ThreadColor(
    code: "1104",
    catalog: "Gunold Sulky",
    name: "Pastel Yellow-Green",
    red: 165,
    green: 175,
    blue: 104,
  ),
  ThreadColor(
    code: "1108",
    catalog: "Gunold Sulky",
    name: "Lt. Mauve",
    red: 250,
    green: 164,
    blue: 164,
  ),
  ThreadColor(
    code: "1109",
    catalog: "Gunold Sulky",
    name: "Hot Pink",
    red: 220,
    green: 100,
    blue: 150,
  ),
  ThreadColor(
    code: "1111",
    catalog: "Gunold Sulky",
    name: "Pastel Orchid",
    red: 252,
    green: 203,
    blue: 223,
  ),
  ThreadColor(
    code: "1112",
    catalog: "Gunold Sulky",
    name: "Royal Purple",
    red: 70,
    green: 1,
    blue: 110,
  ),
  ThreadColor(
    code: "1113",
    catalog: "Gunold Sulky",
    name: "Pastel Mauve",
    red: 240,
    green: 200,
    blue: 180,
  ),
  ThreadColor(
    code: "1115",
    catalog: "Gunold Sulky",
    name: "Lt. Pink",
    red: 240,
    green: 185,
    blue: 185,
  ),
  ThreadColor(
    code: "1117",
    catalog: "Gunold Sulky",
    name: "Mauve",
    red: 245,
    green: 169,
    blue: 160,
  ),
  ThreadColor(
    code: "1119",
    catalog: "Gunold Sulky",
    name: "Dk. Mauve",
    red: 180,
    green: 110,
    blue: 117,
  ),
  ThreadColor(
    code: "1120",
    catalog: "Gunold Sulky",
    name: "Pale Pink",
    red: 240,
    green: 214,
    blue: 210,
  ),
  ThreadColor(
    code: "1121",
    catalog: "Gunold Sulky",
    name: "Pink",
    red: 250,
    green: 185,
    blue: 203,
  ),
  ThreadColor(
    code: "1122",
    catalog: "Gunold Sulky",
    name: "Purple",
    red: 130,
    green: 40,
    blue: 142,
  ),
  ThreadColor(
    code: "1124",
    catalog: "Gunold Sulky",
    name: "Manila",
    red: 255,
    green: 236,
    blue: 0,
  ),
  ThreadColor(
    code: "1126",
    catalog: "Gunold Sulky",
    name: "Tan",
    red: 220,
    green: 140,
    blue: 23,
  ),
  ThreadColor(
    code: "1127",
    catalog: "Gunold Sulky",
    name: "Med. Ecru",
    red: 250,
    green: 236,
    blue: 198,
  ),
  ThreadColor(
    code: "1128",
    catalog: "Gunold Sulky",
    name: "Dk. Ecru",
    red: 195,
    green: 148,
    blue: 113,
  ),
  ThreadColor(
    code: "1129",
    catalog: "Gunold Sulky",
    name: "Brown",
    red: 106,
    green: 31,
    blue: 6,
  ),
  ThreadColor(
    code: "1130",
    catalog: "Gunold Sulky",
    name: "Dark Brown",
    red: 85,
    green: 22,
    blue: 2,
  ),
  ThreadColor(
    code: "1131",
    catalog: "Gunold Sulky",
    name: "Cloister Brown",
    red: 73,
    green: 0,
    blue: 2,
  ),
  ThreadColor(
    code: "1134",
    catalog: "Gunold Sulky",
    name: "Peacock Blue",
    red: 80,
    green: 125,
    blue: 170,
  ),
  ThreadColor(
    code: "1135",
    catalog: "Gunold Sulky",
    name: "Pastel Yellow",
    red: 255,
    green: 240,
    blue: 114,
  ),
  ThreadColor(
    code: "1137",
    catalog: "Gunold Sulky",
    name: "Yellow Orange",
    red: 255,
    green: 190,
    blue: 0,
  ),
  ThreadColor(
    code: "1143",
    catalog: "Gunold Sulky",
    name: "True Blue",
    red: 74,
    green: 88,
    blue: 112,
  ),
  ThreadColor(
    code: "1145",
    catalog: "Gunold Sulky",
    name: "Powder Blue",
    red: 180,
    green: 225,
    blue: 235,
  ),
  ThreadColor(
    code: "1147",
    catalog: "Gunold Sulky",
    name: "True Red",
    red: 235,
    green: 0,
    blue: 1,
  ),
  ThreadColor(
    code: "1148",
    catalog: "Gunold Sulky",
    name: "Lt. Coral",
    red: 255,
    green: 189,
    blue: 189,
  ),
  ThreadColor(
    code: "1149",
    catalog: "Gunold Sulky",
    name: "Deep Ecru",
    red: 232,
    green: 200,
    blue: 156,
  ),
  ThreadColor(
    code: "1151",
    catalog: "Gunold Sulky",
    name: "Powder Blue Tint",
    red: 226,
    green: 226,
    blue: 235,
  ),
  ThreadColor(
    code: "1154",
    catalog: "Gunold Sulky",
    name: "Coral",
    red: 250,
    green: 153,
    blue: 153,
  ),
  ThreadColor(
    code: "1156",
    catalog: "Gunold Sulky",
    name: "Lt. Army Green",
    red: 99,
    green: 99,
    blue: 39,
  ),
  ThreadColor(
    code: "1158",
    catalog: "Gunold Sulky",
    name: "Dk. Maple",
    red: 186,
    green: 69,
    blue: 0,
  ),
  ThreadColor(
    code: "1159",
    catalog: "Gunold Sulky",
    name: "Temple Gold",
    red: 211,
    green: 157,
    blue: 0,
  ),
  ThreadColor(
    code: "1162",
    catalog: "Gunold Sulky",
    name: "Deep Teal",
    red: 16,
    green: 57,
    blue: 74,
  ),
  ThreadColor(
    code: "1165",
    catalog: "Gunold Sulky",
    name: "Lt. Sky Blue",
    red: 223,
    green: 229,
    blue: 235,
  ),
  ThreadColor(
    code: "1166",
    catalog: "Gunold Sulky",
    name: "Med. Steel Gray",
    red: 142,
    green: 126,
    blue: 126,
  ),
  ThreadColor(
    code: "1167",
    catalog: "Gunold Sulky",
    name: "Maize Yellow",
    red: 255,
    green: 210,
    blue: 38,
  ),
  ThreadColor(
    code: "1168",
    catalog: "Gunold Sulky",
    name: "True Orange",
    red: 245,
    green: 116,
    blue: 10,
  ),
  ThreadColor(
    code: "1169",
    catalog: "Gunold Sulky",
    name: "Bayberry Red",
    red: 156,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1170",
    catalog: "Gunold Sulky",
    name: "Lt. Brown",
    red: 151,
    green: 95,
    blue: 47,
  ),
  ThreadColor(
    code: "1171",
    catalog: "Gunold Sulky",
    name: "Weathered Blue",
    red: 8,
    green: 24,
    blue: 14,
  ),
  ThreadColor(
    code: "1172",
    catalog: "Gunold Sulky",
    name: "Med. Weathered Blue",
    red: 110,
    green: 120,
    blue: 140,
  ),
  ThreadColor(
    code: "1173",
    catalog: "Gunold Sulky",
    name: "Med. Army Green",
    red: 89,
    green: 89,
    blue: 29,
  ),
  ThreadColor(
    code: "1174",
    catalog: "Gunold Sulky",
    name: "Dk. Pine Green",
    red: 13,
    green: 41,
    blue: 4,
  ),
  ThreadColor(
    code: "1175",
    catalog: "Gunold Sulky",
    name: "Dk. Avocado",
    red: 21,
    green: 45,
    blue: 4,
  ),
  ThreadColor(
    code: "1176",
    catalog: "Gunold Sulky",
    name: "Med. Dk. Avocado",
    red: 81,
    green: 83,
    blue: 8,
  ),
  ThreadColor(
    code: "1177",
    catalog: "Gunold Sulky",
    name: "Avocado",
    red: 137,
    green: 152,
    blue: 18,
  ),
  ThreadColor(
    code: "1179",
    catalog: "Gunold Sulky",
    name: "Dk. Taupe",
    red: 143,
    green: 98,
    blue: 61,
  ),
  ThreadColor(
    code: "1180",
    catalog: "Gunold Sulky",
    name: "Med. Taupe",
    red: 165,
    green: 137,
    blue: 115,
  ),
  ThreadColor(
    code: "1181",
    catalog: "Gunold Sulky",
    name: "Rust",
    red: 203,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1182",
    catalog: "Gunold Sulky",
    name: "Blue Black",
    red: 2,
    green: 1,
    blue: 20,
  ),
  ThreadColor(
    code: "1183",
    catalog: "Gunold Sulky",
    name: "Black Cherry",
    red: 50,
    green: 6,
    blue: 20,
  ),
  ThreadColor(
    code: "1184",
    catalog: "Gunold Sulky",
    name: "Orange",
    red: 255,
    green: 102,
    blue: 1,
  ),
  ThreadColor(
    code: "1185",
    catalog: "Gunold Sulky",
    name: "Golden Yellow",
    red: 252,
    green: 190,
    blue: 5,
  ),
  ThreadColor(
    code: "1186",
    catalog: "Gunold Sulky",
    name: "Sable Brown",
    red: 91,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1187",
    catalog: "Gunold Sulky",
    name: "Mimosa Yellow",
    red: 255,
    green: 229,
    blue: 0,
  ),
  ThreadColor(
    code: "1188",
    catalog: "Gunold Sulky",
    name: "Deep Red",
    red: 255,
    green: 0,
    blue: 75,
  ),
  ThreadColor(
    code: "1189",
    catalog: "Gunold Sulky",
    name: "Dk. Chestnut",
    red: 75,
    green: 18,
    blue: 45,
  ),
  ThreadColor(
    code: "1190",
    catalog: "Gunold Sulky",
    name: "Med. Burgundy",
    red: 160,
    green: 70,
    blue: 86,
  ),
  ThreadColor(
    code: "1191",
    catalog: "Gunold Sulky",
    name: "Dk. Rose",
    red: 189,
    green: 30,
    blue: 96,
  ),
  ThreadColor(
    code: "1192",
    catalog: "Gunold Sulky",
    name: "Fuchsia",
    red: 210,
    green: 30,
    blue: 130,
  ),
  ThreadColor(
    code: "1193",
    catalog: "Gunold Sulky",
    name: "Lavender",
    red: 230,
    green: 175,
    blue: 210,
  ),
  ThreadColor(
    code: "1194",
    catalog: "Gunold Sulky",
    name: "Lt. Purple",
    red: 210,
    green: 116,
    blue: 215,
  ),
  ThreadColor(
    code: "1195",
    catalog: "Gunold Sulky",
    name: "Dk. Purple",
    red: 55,
    green: 1,
    blue: 80,
  ),
  ThreadColor(
    code: "1196",
    catalog: "Gunold Sulky",
    name: "Blue",
    red: 98,
    green: 170,
    blue: 220,
  ),
  ThreadColor(
    code: "1197",
    catalog: "Gunold Sulky",
    name: "Med. Navy",
    red: 34,
    green: 15,
    blue: 52,
  ),
  ThreadColor(
    code: "1198",
    catalog: "Gunold Sulky",
    name: "Dusty Navy",
    red: 60,
    green: 80,
    blue: 117,
  ),
  ThreadColor(
    code: "1199",
    catalog: "Gunold Sulky",
    name: "Admiral Navy Blue",
    red: 42,
    green: 20,
    blue: 63,
  ),
  ThreadColor(
    code: "1200",
    catalog: "Gunold Sulky",
    name: "Med. Dk. Navy",
    red: 20,
    green: 11,
    blue: 45,
  ),
  ThreadColor(
    code: "1201",
    catalog: "Gunold Sulky",
    name: "Med. Powder Blue",
    red: 100,
    green: 139,
    blue: 190,
  ),
  ThreadColor(
    code: "1202",
    catalog: "Gunold Sulky",
    name: "Deep Turquoise",
    red: 24,
    green: 43,
    blue: 86,
  ),
  ThreadColor(
    code: "1203",
    catalog: "Gunold Sulky",
    name: "Lt. Weathered Blue",
    red: 174,
    green: 184,
    blue: 195,
  ),
  ThreadColor(
    code: "1205",
    catalog: "Gunold Sulky",
    name: "Med. Jade",
    red: 110,
    green: 144,
    blue: 165,
  ),
  ThreadColor(
    code: "1206",
    catalog: "Gunold Sulky",
    name: "Dark Jade",
    red: 30,
    green: 110,
    blue: 111,
  ),
  ThreadColor(
    code: "1207",
    catalog: "Gunold Sulky",
    name: "Sea Foam Green",
    red: 128,
    green: 163,
    blue: 136,
  ),
  ThreadColor(
    code: "1208",
    catalog: "Gunold Sulky",
    name: "Mallard Green",
    red: 12,
    green: 61,
    blue: 3,
  ),
  ThreadColor(
    code: "1209",
    catalog: "Gunold Sulky",
    name: "Lt. Avocado",
    red: 189,
    green: 209,
    blue: 99,
  ),
  ThreadColor(
    code: "1210",
    catalog: "Gunold Sulky",
    name: "Dk. Army Green",
    red: 39,
    green: 59,
    blue: 0,
  ),
  ThreadColor(
    code: "1211",
    catalog: "Gunold Sulky",
    name: "Lt. Khaki",
    red: 149,
    green: 164,
    blue: 144,
  ),
  ThreadColor(
    code: "1212",
    catalog: "Gunold Sulky",
    name: "Khaki",
    red: 99,
    green: 99,
    blue: 45,
  ),
  ThreadColor(
    code: "1213",
    catalog: "Gunold Sulky",
    name: "Taupe",
    red: 185,
    green: 160,
    blue: 150,
  ),
  ThreadColor(
    code: "1214",
    catalog: "Gunold Sulky",
    name: "Med. Chestnut",
    red: 100,
    green: 40,
    blue: 40,
  ),
  ThreadColor(
    code: "1215",
    catalog: "Gunold Sulky",
    name: "Blackberry",
    red: 80,
    green: 10,
    blue: 30,
  ),
  ThreadColor(
    code: "1216",
    catalog: "Gunold Sulky",
    name: "Med. Maple",
    red: 172,
    green: 28,
    blue: 1,
  ),
  ThreadColor(
    code: "1217",
    catalog: "Gunold Sulky",
    name: "Chestnut",
    red: 151,
    green: 31,
    blue: 1,
  ),
  ThreadColor(
    code: "1218",
    catalog: "Gunold Sulky",
    name: "Silver Gray",
    red: 223,
    green: 223,
    blue: 203,
  ),
  ThreadColor(
    code: "1219",
    catalog: "Gunold Sulky",
    name: "Gray",
    red: 152,
    green: 136,
    blue: 140,
  ),
  ThreadColor(
    code: "1220",
    catalog: "Gunold Sulky",
    name: "Charcoal Gray",
    red: 96,
    green: 96,
    blue: 96,
  ),
  ThreadColor(
    code: "1222",
    catalog: "Gunold Sulky",
    name: "Lt. Baby Blue",
    red: 209,
    green: 219,
    blue: 255,
  ),
  ThreadColor(
    code: "1223",
    catalog: "Gunold Sulky",
    name: "Baby Blue Tint",
    red: 220,
    green: 224,
    blue: 241,
  ),
  ThreadColor(
    code: "1224",
    catalog: "Gunold Sulky",
    name: "Bright Pink",
    red: 240,
    green: 160,
    blue: 185,
  ),
  ThreadColor(
    code: "1225",
    catalog: "Gunold Sulky",
    name: "Pastel Pink",
    red: 250,
    green: 203,
    blue: 203,
  ),
  ThreadColor(
    code: "1226",
    catalog: "Gunold Sulky",
    name: "Dk. Periwinkle",
    red: 87,
    green: 54,
    blue: 158,
  ),
  ThreadColor(
    code: "1227",
    catalog: "Gunold Sulky",
    name: "Gold Green",
    red: 175,
    green: 137,
    blue: 1,
  ),
  ThreadColor(
    code: "1228",
    catalog: "Gunold Sulky",
    name: "Drab Green",
    red: 150,
    green: 170,
    blue: 139,
  ),
  ThreadColor(
    code: "1229",
    catalog: "Gunold Sulky",
    name: "Lt. Putty",
    red: 224,
    green: 219,
    blue: 219,
  ),
  ThreadColor(
    code: "1230",
    catalog: "Gunold Sulky",
    name: "Dk. Teal",
    red: 11,
    green: 65,
    blue: 51,
  ),
  ThreadColor(
    code: "1231",
    catalog: "Gunold Sulky",
    name: "Med. Rose",
    red: 229,
    green: 50,
    blue: 106,
  ),
  ThreadColor(
    code: "1232",
    catalog: "Gunold Sulky",
    name: "Classic Green",
    red: 25,
    green: 50,
    blue: 7,
  ),
  ThreadColor(
    code: "1233",
    catalog: "Gunold Sulky",
    name: "Ocean Teal",
    red: 13,
    green: 34,
    blue: 16,
  ),
  ThreadColor(
    code: "1234",
    catalog: "Gunold Sulky",
    name: "Almost Black",
    red: 43,
    green: 43,
    blue: 43,
  ),
  ThreadColor(
    code: "1235",
    catalog: "Gunold Sulky",
    name: "Deep Purple",
    red: 120,
    green: 50,
    blue: 152,
  ),
  ThreadColor(
    code: "1236",
    catalog: "Gunold Sulky",
    name: "Lt. Silver",
    red: 234,
    green: 228,
    blue: 228,
  ),
  ThreadColor(
    code: "1237",
    catalog: "Gunold Sulky",
    name: "Deep Mauve",
    red: 188,
    green: 61,
    blue: 44,
  ),
  ThreadColor(
    code: "1238",
    catalog: "Gunold Sulky",
    name: "Orange Sunrise",
    red: 255,
    green: 131,
    blue: 0,
  ),
  ThreadColor(
    code: "1239",
    catalog: "Gunold Sulky",
    name: "Apricot",
    red: 255,
    green: 171,
    blue: 87,
  ),
  ThreadColor(
    code: "1240",
    catalog: "Gunold Sulky",
    name: "Smokey Grey",
    red: 116,
    green: 88,
    blue: 108,
  ),
  ThreadColor(
    code: "1241",
    catalog: "Gunold Sulky",
    name: "Intense Maroon",
    red: 63,
    green: 54,
    blue: 67,
  ),
  ThreadColor(
    code: "1242",
    catalog: "Gunold Sulky",
    name: "Nassau Blue",
    red: 84,
    green: 58,
    blue: 141,
  ),
  ThreadColor(
    code: "1243",
    catalog: "Gunold Sulky",
    name: "Mimosa",
    red: 224,
    green: 198,
    blue: 59,
  ),
  ThreadColor(
    code: "1244",
    catalog: "Gunold Sulky",
    name: "Royal Gold",
    red: 202,
    green: 169,
    blue: 2,
  ),
  ThreadColor(
    code: "1245",
    catalog: "Gunold Sulky",
    name: "Shimmering Gold",
    red: 178,
    green: 142,
    blue: 0,
  ),
  ThreadColor(
    code: "1246",
    catalog: "Gunold Sulky",
    name: "Blaze Medium",
    red: 255,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1247",
    catalog: "Gunold Sulky",
    name: "Mahogany",
    red: 102,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1248",
    catalog: "Gunold Sulky",
    name: "Med. Pastel Blue",
    red: 210,
    green: 230,
    blue: 240,
  ),
  ThreadColor(
    code: "1249",
    catalog: "Gunold Sulky",
    name: "Cornflower Blue",
    red: 150,
    green: 195,
    blue: 224,
  ),
  ThreadColor(
    code: "1250",
    catalog: "Gunold Sulky",
    name: "Duck Wing Blue",
    red: 39,
    green: 92,
    blue: 112,
  ),
  ThreadColor(
    code: "1251",
    catalog: "Gunold Sulky",
    name: "Bright Turquoise",
    red: 48,
    green: 111,
    blue: 117,
  ),
  ThreadColor(
    code: "1252",
    catalog: "Gunold Sulky",
    name: "Bright Peacock",
    red: 9,
    green: 161,
    blue: 168,
  ),
  ThreadColor(
    code: "1253",
    catalog: "Gunold Sulky",
    name: "Dk. Sapphire",
    red: 27,
    green: 76,
    blue: 164,
  ),
  ThreadColor(
    code: "1254",
    catalog: "Gunold Sulky",
    name: "Dusty Lavender",
    red: 230,
    green: 185,
    blue: 245,
  ),
  ThreadColor(
    code: "1255",
    catalog: "Gunold Sulky",
    name: "Deep Orchid",
    red: 157,
    green: 33,
    blue: 160,
  ),
  ThreadColor(
    code: "1256",
    catalog: "Gunold Sulky",
    name: "Sweet Pink",
    red: 235,
    green: 130,
    blue: 150,
  ),
  ThreadColor(
    code: "1257",
    catalog: "Gunold Sulky",
    name: "Deep Coral",
    red: 230,
    green: 0,
    blue: 65,
  ),
  ThreadColor(
    code: "1258",
    catalog: "Gunold Sulky",
    name: "Coast Point",
    red: 240,
    green: 196,
    blue: 160,
  ),
  ThreadColor(
    code: "1259",
    catalog: "Gunold Sulky",
    name: "Salmon Peach",
    red: 226,
    green: 130,
    blue: 100,
  ),
  ThreadColor(
    code: "1260",
    catalog: "Gunold Sulky",
    name: "Dusky Brass",
    red: 221,
    green: 171,
    blue: 0,
  ),
  ThreadColor(
    code: "1261",
    catalog: "Gunold Sulky",
    name: "Empire Yellow",
    red: 255,
    green: 227,
    blue: 0,
  ),
  ThreadColor(
    code: "1262",
    catalog: "Gunold Sulky",
    name: "Gold Green",
    red: 169,
    green: 136,
    blue: 3,
  ),
  ThreadColor(
    code: "1263",
    catalog: "Gunold Sulky",
    name: "Red Jubilee",
    red: 179,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1264",
    catalog: "Gunold Sulky",
    name: "Cognac",
    red: 106,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1265",
    catalog: "Gunold Sulky",
    name: "Burnt Toast",
    red: 165,
    green: 122,
    blue: 58,
  ),
  ThreadColor(
    code: "1204",
    catalog: "Gunold Sulky",
    name: "Pastel Jade",
    red: 168,
    green: 200,
    blue: 188,
  ),
  ThreadColor(
    code: "1266",
    catalog: "Gunold Sulky",
    name: "Toast",
    red: 156,
    green: 109,
    blue: 69,
  ),
  ThreadColor(
    code: "1267",
    catalog: "Gunold Sulky",
    name: "Mink Brown",
    red: 134,
    green: 76,
    blue: 49,
  ),
  ThreadColor(
    code: "1268",
    catalog: "Gunold Sulky",
    name: "Light Gray Khaki",
    red: 239,
    green: 239,
    blue: 229,
  ),
  ThreadColor(
    code: "1269",
    catalog: "Gunold Sulky",
    name: "Light Purple",
    red: 172,
    green: 135,
    blue: 131,
  ),
  ThreadColor(
    code: "1270",
    catalog: "Gunold Sulky",
    name: "Dk. Gray Khaki",
    red: 183,
    green: 183,
    blue: 175,
  ),
  ThreadColor(
    code: "1271",
    catalog: "Gunold Sulky",
    name: "Evergreen",
    red: 60,
    green: 79,
    blue: 49,
  ),
  ThreadColor(
    code: "1272",
    catalog: "Gunold Sulky",
    name: "Hedge Green",
    red: 74,
    green: 74,
    blue: 25,
  ),
  ThreadColor(
    code: "1273",
    catalog: "Gunold Sulky",
    name: "Dark Forest",
    red: 54,
    green: 54,
    blue: 31,
  ),
  ThreadColor(
    code: "1274",
    catalog: "Gunold Sulky",
    name: "Nile Green",
    red: 92,
    green: 154,
    blue: 26,
  ),
  ThreadColor(
    code: "1275",
    catalog: "Gunold Sulky",
    name: "Sea Mist",
    red: 224,
    green: 230,
    blue: 200,
  ),
  ThreadColor(
    code: "1276",
    catalog: "Gunold Sulky",
    name: "Pistachio",
    red: 112,
    green: 119,
    blue: 15,
  ),
  ThreadColor(
    code: "1277",
    catalog: "Gunold Sulky",
    name: "Ivy Green",
    red: 2,
    green: 118,
    blue: 2,
  ),
  ThreadColor(
    code: "1278",
    catalog: "Gunold Sulky",
    name: "Bright Green",
    red: 0,
    green: 175,
    blue: 56,
  ),
  ThreadColor(
    code: "1279",
    catalog: "Gunold Sulky",
    name: "Willow Green",
    red: 147,
    green: 209,
    blue: 108,
  ),
  ThreadColor(
    code: "1280",
    catalog: "Gunold Sulky",
    name: "Dk. Willow Green",
    red: 70,
    green: 183,
    blue: 116,
  ),
  ThreadColor(
    code: "1281",
    catalog: "Gunold Sulky",
    name: "Dark Green",
    red: 3,
    green: 103,
    blue: 70,
  ),
  ThreadColor(
    code: "1282",
    catalog: "Gunold Sulky",
    name: "Tamarack",
    red: 169,
    green: 173,
    blue: 3,
  ),
  ThreadColor(
    code: "1283",
    catalog: "Gunold Sulky",
    name: "Slate Gray",
    red: 72,
    green: 61,
    blue: 89,
  ),
  ThreadColor(
    code: "1284",
    catalog: "Gunold Sulky",
    name: "Dk. Winter Sky",
    red: 70,
    green: 110,
    blue: 120,
  ),
  ThreadColor(
    code: "1285",
    catalog: "Gunold Sulky",
    name: "Dk. Sage Green",
    red: 19,
    green: 79,
    blue: 69,
  ),
  ThreadColor(
    code: "1286",
    catalog: "Gunold Sulky",
    name: "Dk. French Green",
    red: 52,
    green: 50,
    blue: 19,
  ),
  ThreadColor(
    code: "1287",
    catalog: "Gunold Sulky",
    name: "French Green",
    red: 65,
    green: 85,
    blue: 69,
  ),
  ThreadColor(
    code: "1288",
    catalog: "Gunold Sulky",
    name: "Aqua",
    red: 13,
    green: 168,
    blue: 149,
  ),
  ThreadColor(
    code: "1289",
    catalog: "Gunold Sulky",
    name: "Ice Blue",
    red: 220,
    green: 235,
    blue: 240,
  ),
  ThreadColor(
    code: "1290",
    catalog: "Gunold Sulky",
    name: "Bright Blue",
    red: 22,
    green: 85,
    blue: 165,
  ),
  ThreadColor(
    code: "1291",
    catalog: "Gunold Sulky",
    name: "Winter Sky",
    red: 114,
    green: 116,
    blue: 131,
  ),
  ThreadColor(
    code: "1292",
    catalog: "Gunold Sulky",
    name: "Heron Blue",
    red: 209,
    green: 220,
    blue: 250,
  ),
  ThreadColor(
    code: "1293",
    catalog: "Gunold Sulky",
    name: "Deep Nassau Blue",
    red: 68,
    green: 35,
    blue: 93,
  ),
  ThreadColor(
    code: "1294",
    catalog: "Gunold Sulky",
    name: "Deep Slate Gray",
    red: 65,
    green: 32,
    blue: 68,
  ),
  ThreadColor(
    code: "1295",
    catalog: "Gunold Sulky",
    name: "Sterling",
    red: 130,
    green: 135,
    blue: 140,
  ),
  ThreadColor(
    code: "1296",
    catalog: "Gunold Sulky",
    name: "Hyacinth",
    red: 210,
    green: 170,
    blue: 240,
  ),
  ThreadColor(
    code: "1297",
    catalog: "Gunold Sulky",
    name: "Lt. Plum",
    red: 115,
    green: 90,
    blue: 100,
  ),
  ThreadColor(
    code: "1298",
    catalog: "Gunold Sulky",
    name: "Dk. Plum",
    red: 100,
    green: 70,
    blue: 100,
  ),
  ThreadColor(
    code: "1299",
    catalog: "Gunold Sulky",
    name: "Purple Shadow",
    red: 65,
    green: 20,
    blue: 70,
  ),
  ThreadColor(
    code: "1300",
    catalog: "Gunold Sulky",
    name: "Plum",
    red: 126,
    green: 30,
    blue: 70,
  ),
  ThreadColor(
    code: "1301",
    catalog: "Gunold Sulky",
    name: "Deep Eggplant",
    red: 50,
    green: 0,
    blue: 70,
  ),
  ThreadColor(
    code: "1302",
    catalog: "Gunold Sulky",
    name: "Eggplant",
    red: 110,
    green: 10,
    blue: 150,
  ),
  ThreadColor(
    code: "1303",
    catalog: "Gunold Sulky",
    name: "Dusty Rose",
    red: 250,
    green: 95,
    blue: 127,
  ),
  ThreadColor(
    code: "1304",
    catalog: "Gunold Sulky",
    name: "Dewberry",
    red: 180,
    green: 115,
    blue: 100,
  ),
  ThreadColor(
    code: "1305",
    catalog: "Gunold Sulky",
    name: "Sage Green",
    red: 174,
    green: 198,
    blue: 187,
  ),
  ThreadColor(
    code: "1306",
    catalog: "Gunold Sulky",
    name: "Gun Metal Gray",
    red: 126,
    green: 108,
    blue: 124,
  ),
  ThreadColor(
    code: "1307",
    catalog: "Gunold Sulky",
    name: "Petal Pink",
    red: 219,
    green: 100,
    blue: 120,
  ),
  ThreadColor(
    code: "1308",
    catalog: "Gunold Sulky",
    name: "Rose Wine Very Dark",
    red: 154,
    green: 44,
    blue: 80,
  ),
  ThreadColor(
    code: "1309",
    catalog: "Gunold Sulky",
    name: "Magenta",
    red: 120,
    green: 35,
    blue: 70,
  ),
  ThreadColor(
    code: "1310",
    catalog: "Gunold Sulky",
    name: "Atom Red",
    red: 188,
    green: 54,
    blue: 90,
  ),
  ThreadColor(
    code: "1311",
    catalog: "Gunold Sulky",
    name: "Mulberry",
    red: 150,
    green: 26,
    blue: 50,
  ),
  ThreadColor(
    code: "1312",
    catalog: "Gunold Sulky",
    name: "Wine",
    red: 132,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1313",
    catalog: "Gunold Sulky",
    name: "Bittersweet",
    red: 252,
    green: 143,
    blue: 12,
  ),
  ThreadColor(
    code: "1314",
    catalog: "Gunold Sulky",
    name: "Pumpkin Orange",
    red: 240,
    green: 110,
    blue: 12,
  ),
  ThreadColor(
    code: "1315",
    catalog: "Gunold Sulky",
    name: "Maple",
    red: 235,
    green: 102,
    blue: 6,
  ),
  ThreadColor(
    code: "1317",
    catalog: "Gunold Sulky",
    name: "Blaze Dark",
    red: 255,
    green: 0,
    blue: 1,
  ),
  ThreadColor(
    code: "1319",
    catalog: "Gunold Sulky",
    name: "Hot Cha Cha",
    red: 239,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1320",
    catalog: "Gunold Sulky",
    name: "Pollen Gold",
    red: 199,
    green: 126,
    blue: 35,
  ),
  ThreadColor(
    code: "1321",
    catalog: "Gunold Sulky",
    name: "Gray Khaki",
    red: 203,
    green: 203,
    blue: 189,
  ),
  ThreadColor(
    code: "1322",
    catalog: "Gunold Sulky",
    name: "Chartreuse",
    red: 129,
    green: 137,
    blue: 1,
  ),
  ThreadColor(
    code: "1323",
    catalog: "Gunold Sulky",
    name: "Dark Chocolate",
    red: 71,
    green: 2,
    blue: 0,
  ),
  ThreadColor(
    code: "1324",
    catalog: "Gunold Sulky",
    name: "Dark Chocolate",
    red: 70,
    green: 1,
    blue: 0,
  ),
  ThreadColor(
    code: "1325",
    catalog: "Gunold Sulky",
    name: "Whisper Gray",
    red: 248,
    green: 245,
    blue: 241,
  ),
  ThreadColor(
    code: "1326",
    catalog: "Gunold Sulky",
    name: "Oyster",
    red: 238,
    green: 227,
    blue: 225,
  ),
  ThreadColor(
    code: "1327",
    catalog: "Gunold Sulky",
    name: "Dk. Whisper Gray",
    red: 213,
    green: 199,
    blue: 195,
  ),
  ThreadColor(
    code: "1328",
    catalog: "Gunold Sulky",
    name: "Nickel Gray",
    red: 184,
    green: 184,
    blue: 184,
  ),
  ThreadColor(
    code: "1329",
    catalog: "Gunold Sulky",
    name: "Dk. Nickel Gray",
    red: 165,
    green: 165,
    blue: 165,
  ),
  ThreadColor(
    code: "1330",
    catalog: "Gunold Sulky",
    name: "Lavender",
    red: 137,
    green: 112,
    blue: 125,
  ),
  ThreadColor(
    code: "1331",
    catalog: "Gunold Sulky",
    name: "Pale Green",
    red: 237,
    green: 246,
    blue: 212,
  ),
  ThreadColor(
    code: "1332",
    catalog: "Gunold Sulky",
    name: "Deep Chartreuse",
    red: 134,
    green: 129,
    blue: 5,
  ),
  ThreadColor(
    code: "1333",
    catalog: "Gunold Sulky",
    name: "Sunflower Gold",
    red: 243,
    green: 182,
    blue: 0,
  ),
  ThreadColor(
    code: "1334",
    catalog: "Gunold Sulky",
    name: "Autumn Green",
    red: 167,
    green: 138,
    blue: 5,
  ),
  ThreadColor(
    code: "1351",
    catalog: "Gunold Sulky",
    name: "Snow White",
    red: 255,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "1352",
    catalog: "Gunold Sulky",
    name: "Black",
    red: 40,
    green: 40,
    blue: 40,
  ),
  ThreadColor(
    code: "1366",
    catalog: "Gunold Sulky",
    name: "Loden Green Medium Light",
    red: 185,
    green: 180,
    blue: 145,
  ),
  ThreadColor(
    code: "1367",
    catalog: "Gunold Sulky",
    name: "Goldenrod",
    red: 255,
    green: 180,
    blue: 0,
  ),
  ThreadColor(
    code: "1389",
    catalog: "Gunold Sulky",
    name: "Gravel",
    red: 195,
    green: 185,
    blue: 150,
  ),
  ThreadColor(
    code: "1393",
    catalog: "Gunold Sulky",
    name: "Red",
    red: 230,
    green: 25,
    blue: 25,
  ),
  ThreadColor(
    code: "1401",
    catalog: "Gunold Sulky",
    name: "Ruby",
    red: 185,
    green: 25,
    blue: 25,
  ),
  ThreadColor(
    code: "1465",
    catalog: "Gunold Sulky",
    name: "Silver Gray",
    red: 225,
    green: 225,
    blue: 225,
  ),
  ThreadColor(
    code: "1503",
    catalog: "Gunold Sulky",
    name: "Green Peacock",
    red: 52,
    green: 150,
    blue: 105,
  ),
  ThreadColor(
    code: "1508",
    catalog: "Gunold Sulky",
    name: "Putty",
    red: 193,
    green: 203,
    blue: 185,
  ),
  ThreadColor(
    code: "1510",
    catalog: "Gunold Sulky",
    name: "Lime Green",
    red: 122,
    green: 179,
    blue: 29,
  ),
  ThreadColor(
    code: "1511",
    catalog: "Gunold Sulky",
    name: "Deep Rose",
    red: 238,
    green: 80,
    blue: 120,
  ),
  ThreadColor(
    code: "1513",
    catalog: "Gunold Sulky",
    name: "Wild Peacock",
    red: 0,
    green: 122,
    blue: 103,
  ),
  ThreadColor(
    code: "1515",
    catalog: "Gunold Sulky",
    name: "Pink Mist",
    red: 255,
    green: 130,
    blue: 180,
  ),
  ThreadColor(
    code: "1517",
    catalog: "Gunold Sulky",
    name: "Coachman Green",
    red: 1,
    green: 79,
    blue: 58,
  ),
  ThreadColor(
    code: "1534",
    catalog: "Gunold Sulky",
    name: "Sapphire",
    red: 52,
    green: 125,
    blue: 203,
  ),
  ThreadColor(
    code: "1535",
    catalog: "Gunold Sulky",
    name: "Team Blue",
    red: 35,
    green: 35,
    blue: 139,
  ),
  ThreadColor(
    code: "1536",
    catalog: "Gunold Sulky",
    name: "Midnight Teal",
    red: 8,
    green: 23,
    blue: 5,
  ),
  ThreadColor(
    code: "1549",
    catalog: "Gunold Sulky",
    name: "Tan",
    red: 205,
    green: 168,
    blue: 104,
  ),
  ThreadColor(
    code: "1558",
    catalog: "Gunold Sulky",
    name: "Dusky Pink",
    red: 240,
    green: 90,
    blue: 115,
  ),
  ThreadColor(
    code: "1561",
    catalog: "Gunold Sulky",
    name: "Violet",
    red: 125,
    green: 120,
    blue: 199,
  ),
  ThreadColor(
    code: "1598",
    catalog: "Gunold Sulky",
    name: "Black",
    red: 25,
    green: 30,
    blue: 45,
  ),
  ThreadColor(
    code: "1609",
    catalog: "Gunold Sulky",
    name: "Mallard Green",
    red: 15,
    green: 60,
    blue: 15,
  ),
  ThreadColor(
    code: "1711",
    catalog: "Gunold Sulky",
    name: "Traditional Gray",
    red: 170,
    green: 175,
    blue: 180,
  ),
  ThreadColor(
    code: "1718",
    catalog: "Gunold Sulky",
    name: "Harvest Green",
    red: 0,
    green: 200,
    blue: 0,
  ),
  ThreadColor(
    code: "1720",
    catalog: "Gunold Sulky",
    name: "Pale Green",
    red: 140,
    green: 205,
    blue: 175,
  ),
  ThreadColor(
    code: "1721",
    catalog: "Gunold Sulky",
    name: "Taupe",
    red: 160,
    green: 145,
    blue: 130,
  ),
  ThreadColor(
    code: "1728",
    catalog: "Gunold Sulky",
    name: "Royal",
    red: 15,
    green: 15,
    blue: 125,
  ),
];
