// This file is generated automatically. DO NOT EDIT.
// Catalog of Gunold Cotty Zusatz colors
import 'package:thread_digit/colors/thread_color.dart';

const List<ThreadColor> gunoldCottyZusatzColors = [
  ThreadColor(
    code: "10",
    catalog: "Gunold COTTY-Zusatz",
    name: "Golden Cream",
    red: 224,
    green: 177,
    blue: 92,
  ),
  ThreadColor(
    code: "68",
    catalog: "Gunold COTTY-Zusatz",
    name: "Kelly",
    red: 0,
    green: 124,
    blue: 64,
  ),
  ThreadColor(
    code: "11",
    catalog: "Gunold COTTY-Zusatz",
    name: "Nutmeg",
    red: 133,
    green: 91,
    blue: 79,
  ),
  ThreadColor(
    code: "69",
    catalog: "Gunold COTTY-Zusatz",
    name: "Date",
    red: 154,
    green: 107,
    blue: 52,
  ),
  ThreadColor(
    code: "12",
    catalog: "Gunold COTTY-Zusatz",
    name: "Old World Buff",
    red: 222,
    green: 180,
    blue: 122,
  ),
  ThreadColor(
    code: "70",
    catalog: "Gunold COTTY-Zusatz",
    name: "Medium Purple",
    red: 104,
    green: 70,
    blue: 128,
  ),
  ThreadColor(
    code: "13",
    catalog: "Gunold COTTY-Zusatz",
    name: "Auburn",
    red: 152,
    green: 78,
    blue: 34,
  ),
  ThreadColor(
    code: "71",
    catalog: "Gunold COTTY-Zusatz",
    name: "Saffron Orange",
    red: 202,
    green: 75,
    blue: 39,
  ),
  ThreadColor(
    code: "14",
    catalog: "Gunold COTTY-Zusatz",
    name: "Raspberry Ice",
    red: 185,
    green: 54,
    blue: 52,
  ),
  ThreadColor(
    code: "72",
    catalog: "Gunold COTTY-Zusatz",
    name: "MD Lime",
    red: 150,
    green: 162,
    blue: 61,
  ),
  ThreadColor(
    code: "15",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Jade Green",
    red: 60,
    green: 102,
    blue: 83,
  ),
  ThreadColor(
    code: "73",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dusk",
    red: 137,
    green: 121,
    blue: 116,
  ),
  ThreadColor(
    code: "16",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Peach",
    red: 231,
    green: 127,
    blue: 118,
  ),
  ThreadColor(
    code: "17",
    catalog: "Gunold COTTY-Zusatz",
    name: "Blueball",
    red: 63,
    green: 113,
    blue: 159,
  ),
  ThreadColor(
    code: "18",
    catalog: "Gunold COTTY-Zusatz",
    name: "Claret",
    red: 130,
    green: 23,
    blue: 73,
  ),
  ThreadColor(
    code: "19",
    catalog: "Gunold COTTY-Zusatz",
    name: "French Raspberry Red",
    red: 93,
    green: 19,
    blue: 54,
  ),
  ThreadColor(
    code: "20",
    catalog: "Gunold COTTY-Zusatz",
    name: "Medium Rust Red",
    red: 155,
    green: 27,
    blue: 43,
  ),
  ThreadColor(
    code: "21",
    catalog: "Gunold COTTY-Zusatz",
    name: "Bright Peacock",
    red: 0,
    green: 162,
    blue: 171,
  ),
  ThreadColor(
    code: "22",
    catalog: "Gunold COTTY-Zusatz",
    name: "Green",
    red: 0,
    green: 101,
    blue: 48,
  ),
  ThreadColor(
    code: "23",
    catalog: "Gunold COTTY-Zusatz",
    name: "Buttercup",
    red: 255,
    green: 219,
    blue: 124,
  ),
  ThreadColor(
    code: "24",
    catalog: "Gunold COTTY-Zusatz",
    name: "Blue",
    red: 0,
    green: 71,
    blue: 138,
  ),
  ThreadColor(
    code: "25",
    catalog: "Gunold COTTY-Zusatz",
    name: "Perfect Ruby",
    red: 149,
    green: 44,
    blue: 60,
  ),
  ThreadColor(
    code: "26",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Aqua Green",
    red: 0,
    green: 114,
    blue: 130,
  ),
  ThreadColor(
    code: "27",
    catalog: "Gunold COTTY-Zusatz",
    name: "Peacock",
    red: 0,
    green: 85,
    blue: 114,
  ),
  ThreadColor(
    code: "28",
    catalog: "Gunold COTTY-Zusatz",
    name: "Deep Plum",
    red: 176,
    green: 55,
    blue: 117,
  ),
  ThreadColor(
    code: "29",
    catalog: "Gunold COTTY-Zusatz",
    name: "Royal Blue",
    red: 37,
    green: 29,
    blue: 90,
  ),
  ThreadColor(
    code: "30",
    catalog: "Gunold COTTY-Zusatz",
    name: "Medium Purple",
    red: 165,
    green: 73,
    blue: 118,
  ),
  ThreadColor(
    code: "31",
    catalog: "Gunold COTTY-Zusatz",
    name: "Fire Blue",
    red: 0,
    green: 86,
    blue: 133,
  ),
  ThreadColor(
    code: "32",
    catalog: "Gunold COTTY-Zusatz",
    name: "Medium Blue/Green",
    red: 102,
    green: 118,
    blue: 82,
  ),
  ThreadColor(
    code: "33",
    catalog: "Gunold COTTY-Zusatz",
    name: "Grape Shake",
    red: 99,
    green: 39,
    blue: 62,
  ),
  ThreadColor(
    code: "34",
    catalog: "Gunold COTTY-Zusatz",
    name: "Avocado Medium Dark",
    red: 77,
    green: 88,
    blue: 57,
  ),
  ThreadColor(
    code: "35",
    catalog: "Gunold COTTY-Zusatz",
    name: "Green",
    red: 21,
    green: 93,
    blue: 45,
  ),
  ThreadColor(
    code: "36",
    catalog: "Gunold COTTY-Zusatz",
    name: "Green Gables",
    red: 30,
    green: 92,
    blue: 46,
  ),
  ThreadColor(
    code: "37",
    catalog: "Gunold COTTY-Zusatz",
    name: "Endicott Bay",
    red: 92,
    green: 137,
    blue: 85,
  ),
  ThreadColor(
    code: "38",
    catalog: "Gunold COTTY-Zusatz",
    name: "Olive",
    red: 74,
    green: 74,
    blue: 62,
  ),
  ThreadColor(
    code: "39",
    catalog: "Gunold COTTY-Zusatz",
    name: "Lemon",
    red: 250,
    green: 228,
    blue: 69,
  ),
  ThreadColor(
    code: "40",
    catalog: "Gunold COTTY-Zusatz",
    name: "Salmon Dark",
    red: 222,
    green: 1,
    blue: 86,
  ),
  ThreadColor(
    code: "41",
    catalog: "Gunold COTTY-Zusatz",
    name: "Boysenberry",
    red: 143,
    green: 48,
    blue: 96,
  ),
  ThreadColor(
    code: "42",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Red",
    red: 149,
    green: 34,
    blue: 100,
  ),
  ThreadColor(
    code: "43",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Purple",
    red: 124,
    green: 20,
    blue: 91,
  ),
  ThreadColor(
    code: "44",
    catalog: "Gunold COTTY-Zusatz",
    name: "Capri",
    red: 73,
    green: 143,
    blue: 159,
  ),
  ThreadColor(
    code: "45",
    catalog: "Gunold COTTY-Zusatz",
    name: "Peacock",
    red: 0,
    green: 94,
    blue: 118,
  ),
  ThreadColor(
    code: "46",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dk. Navy",
    red: 41,
    green: 16,
    blue: 31,
  ),
  ThreadColor(
    code: "47",
    catalog: "Gunold COTTY-Zusatz",
    name: "Baked Apple",
    red: 173,
    green: 70,
    blue: 64,
  ),
  ThreadColor(
    code: "48",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Turquoise",
    red: 0,
    green: 117,
    blue: 123,
  ),
  ThreadColor(
    code: "49",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Sepia",
    red: 95,
    green: 39,
    blue: 42,
  ),
  ThreadColor(
    code: "50",
    catalog: "Gunold COTTY-Zusatz",
    name: "Blithe",
    red: 66,
    green: 146,
    blue: 193,
  ),
  ThreadColor(
    code: "51",
    catalog: "Gunold COTTY-Zusatz",
    name: "Dark Blue",
    red: 21,
    green: 71,
    blue: 127,
  ),
  ThreadColor(
    code: "52",
    catalog: "Gunold COTTY-Zusatz",
    name: "Burnt Sienna",
    red: 182,
    green: 93,
    blue: 72,
  ),
  ThreadColor(
    code: "53",
    catalog: "Gunold COTTY-Zusatz",
    name: "Peacock Blue dark",
    red: 0,
    green: 105,
    blue: 143,
  ),
  ThreadColor(
    code: "54",
    catalog: "Gunold COTTY-Zusatz",
    name: "Blue",
    red: 0,
    green: 77,
    blue: 149,
  ),
  ThreadColor(
    code: "55",
    catalog: "Gunold COTTY-Zusatz",
    name: "Deep Periwinkle",
    red: 120,
    green: 127,
    blue: 189,
  ),
  ThreadColor(
    code: "56",
    catalog: "Gunold COTTY-Zusatz",
    name: "Ruby Glint",
    red: 211,
    green: 80,
    blue: 137,
  ),
  ThreadColor(
    code: "57",
    catalog: "Gunold COTTY-Zusatz",
    name: "Rich Burgundy",
    red: 74,
    green: 28,
    blue: 36,
  ),
  ThreadColor(
    code: "58",
    catalog: "Gunold COTTY-Zusatz",
    name: "Baja Blue",
    red: 99,
    green: 105,
    blue: 164,
  ),
  ThreadColor(
    code: "59",
    catalog: "Gunold COTTY-Zusatz",
    name: "Teaberry",
    red: 201,
    green: 55,
    blue: 90,
  ),
  ThreadColor(
    code: "60",
    catalog: "Gunold COTTY-Zusatz",
    name: "Lafayette Rose",
    red: 216,
    green: 53,
    blue: 77,
  ),
  ThreadColor(
    code: "61",
    catalog: "Gunold COTTY-Zusatz",
    name: "Medium Lime",
    red: 77,
    green: 169,
    blue: 69,
  ),
  ThreadColor(
    code: "62",
    catalog: "Gunold COTTY-Zusatz",
    name: "Autumn Green",
    red: 140,
    green: 116,
    blue: 53,
  ),
  ThreadColor(
    code: "63",
    catalog: "Gunold COTTY-Zusatz",
    name: "Royal",
    red: 39,
    green: 64,
    blue: 125,
  ),
  ThreadColor(
    code: "64",
    catalog: "Gunold COTTY-Zusatz",
    name: "Amaranth Purple",
    red: 69,
    green: 28,
    blue: 83,
  ),
  ThreadColor(
    code: "65",
    catalog: "Gunold COTTY-Zusatz",
    name: "Huckleberry",
    red: 77,
    green: 47,
    blue: 106,
  ),
  ThreadColor(
    code: "66",
    catalog: "Gunold COTTY-Zusatz",
    name: "Redish Purple",
    red: 104,
    green: 35,
    blue: 107,
  ),
  ThreadColor(
    code: "67",
    catalog: "Gunold COTTY-Zusatz",
    name: "Meadow Green",
    red: 106,
    green: 138,
    blue: 38,
  ),
];
