// This file is generated automatically. DO NOT EDIT.
// Catalog of Gunold Cotty colors
import 'package:thread_digit/colors/thread_color.dart';

const List<ThreadColor> gunoldCottyColors = [
  ThreadColor(
    code: "100",
    catalog: "Gunold COTTY",
    name: "Snow White",
    red: 255,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "246",
    catalog: "Gunold COTTY",
    name: "Starlight Blue",
    red: 50,
    green: 90,
    blue: 162,
  ),
  ThreadColor(
    code: "101",
    catalog: "Gunold COTTY",
    name: "N/A",
    red: 221,
    green: 8,
    blue: 59,
  ),
  ThreadColor(
    code: "262",
    catalog: "Gunold COTTY",
    name: "Pink",
    red: 213,
    green: 106,
    blue: 144,
  ),
  ThreadColor(
    code: "102",
    catalog: "Gunold COTTY",
    name: "Deep Pink",
    red: 191,
    green: 27,
    blue: 62,
  ),
  ThreadColor(
    code: "278",
    catalog: "Gunold COTTY",
    name: "Light Pink",
    red: 220,
    green: 191,
    blue: 214,
  ),
  ThreadColor(
    code: "103",
    catalog: "Gunold COTTY",
    name: "Raspberry",
    red: 139,
    green: 33,
    blue: 80,
  ),
  ThreadColor(
    code: "279",
    catalog: "Gunold COTTY",
    name: "Dark Royal Blue",
    red: 70,
    green: 36,
    blue: 127,
  ),
  ThreadColor(
    code: "104",
    catalog: "Gunold COTTY",
    name: "Orangeade",
    red: 232,
    green: 78,
    blue: 15,
  ),
  ThreadColor(
    code: "280",
    catalog: "Gunold COTTY",
    name: "Grape",
    red: 162,
    green: 142,
    blue: 173,
  ),
  ThreadColor(
    code: "105",
    catalog: "Gunold COTTY",
    name: "Honeysuckle",
    red: 230,
    green: 51,
    blue: 35,
  ),
  ThreadColor(
    code: "281",
    catalog: "Gunold COTTY",
    name: "Mink Brown",
    red: 138,
    green: 70,
    blue: 47,
  ),
  ThreadColor(
    code: "106",
    catalog: "Gunold COTTY",
    name: "Granet Very Dark",
    red: 135,
    green: 28,
    blue: 77,
  ),
  ThreadColor(
    code: "285",
    catalog: "Gunold COTTY",
    name: "Black Red",
    red: 50,
    green: 23,
    blue: 28,
  ),
  ThreadColor(
    code: "107",
    catalog: "Gunold COTTY",
    name: "Sangria",
    red: 198,
    green: 26,
    blue: 39,
  ),
  ThreadColor(
    code: "292",
    catalog: "Gunold COTTY",
    name: "Cherry Red",
    red: 167,
    green: 33,
    blue: 41,
  ),
  ThreadColor(
    code: "112",
    catalog: "Gunold COTTY",
    name: "Dark Teal",
    red: 0,
    green: 81,
    blue: 84,
  ),
  ThreadColor(
    code: "293",
    catalog: "Gunold COTTY",
    name: "Dusky Burgandy",
    red: 72,
    green: 36,
    blue: 46,
  ),
  ThreadColor(
    code: "113",
    catalog: "Gunold COTTY",
    name: "Frosty Spruce",
    red: 0,
    green: 97,
    blue: 74,
  ),
  ThreadColor(
    code: "294",
    catalog: "Gunold COTTY",
    name: "Dark Chocolate",
    red: 43,
    green: 2,
    blue: 0,
  ),
  ThreadColor(
    code: "114",
    catalog: "Gunold COTTY",
    name: "Fresh green",
    red: 77,
    green: 158,
    blue: 66,
  ),
  ThreadColor(
    code: "295",
    catalog: "Gunold COTTY",
    name: "Espresso",
    red: 23,
    green: 13,
    blue: 7,
  ),
  ThreadColor(
    code: "115",
    catalog: "Gunold COTTY",
    name: "Dark Green",
    red: 0,
    green: 111,
    blue: 76,
  ),
  ThreadColor(
    code: "298",
    catalog: "Gunold COTTY",
    name: "Light Cocoa",
    red: 125,
    green: 71,
    blue: 52,
  ),
  ThreadColor(
    code: "116",
    catalog: "Gunold COTTY",
    name: "Jungle Green",
    red: 0,
    green: 115,
    blue: 65,
  ),
  ThreadColor(
    code: "299",
    catalog: "Gunold COTTY",
    name: "Dark Maroon",
    red: 97,
    green: 30,
    blue: 41,
  ),
  ThreadColor(
    code: "117",
    catalog: "Gunold COTTY",
    name: "Irish Spring",
    red: 0,
    green: 124,
    blue: 102,
  ),
  ThreadColor(
    code: "300",
    catalog: "Gunold COTTY",
    name: "Jet Black",
    red: 0,
    green: 0,
    blue: 6,
  ),
  ThreadColor(
    code: "118",
    catalog: "Gunold COTTY",
    name: "Coachman Green",
    red: 0,
    green: 78,
    blue: 59,
  ),
  ThreadColor(
    code: "301",
    catalog: "Gunold COTTY",
    name: "Mimosa",
    red: 221,
    green: 160,
    blue: 44,
  ),
  ThreadColor(
    code: "120",
    catalog: "Gunold COTTY",
    name: "Blue Satin",
    red: 0,
    green: 103,
    blue: 119,
  ),
  ThreadColor(
    code: "302",
    catalog: "Gunold COTTY",
    name: "Dark Brown",
    red: 48,
    green: 31,
    blue: 39,
  ),
  ThreadColor(
    code: "122",
    catalog: "Gunold COTTY",
    name: "Blue",
    red: 20,
    green: 56,
    blue: 127,
  ),
  ThreadColor(
    code: "303",
    catalog: "Gunold COTTY",
    name: "Peach",
    red: 237,
    green: 202,
    blue: 163,
  ),
  ThreadColor(
    code: "124",
    catalog: "Gunold COTTY",
    name: "Eggplant",
    red: 26,
    green: 29,
    blue: 86,
  ),
  ThreadColor(
    code: "304",
    catalog: "Gunold COTTY",
    name: "Cloud Dancer",
    red: 245,
    green: 241,
    blue: 233,
  ),
  ThreadColor(
    code: "125",
    catalog: "Gunold COTTY",
    name: "Teal",
    red: 0,
    green: 118,
    blue: 156,
  ),
  ThreadColor(
    code: "305",
    catalog: "Gunold COTTY",
    name: "Enchanted Sea",
    red: 45,
    green: 89,
    blue: 83,
  ),
  ThreadColor(
    code: "126",
    catalog: "Gunold COTTY",
    name: "Medium blue",
    red: 70,
    green: 156,
    blue: 208,
  ),
  ThreadColor(
    code: "306",
    catalog: "Gunold COTTY",
    name: "Olive Drab",
    red: 93,
    green: 94,
    blue: 48,
  ),
  ThreadColor(
    code: "127",
    catalog: "Gunold COTTY",
    name: "Fire Blue",
    red: 22,
    green: 65,
    blue: 148,
  ),
  ThreadColor(
    code: "307",
    catalog: "Gunold COTTY",
    name: "Pastel Green",
    red: 175,
    green: 209,
    blue: 169,
  ),
  ThreadColor(
    code: "128",
    catalog: "Gunold COTTY",
    name: "Sapphire",
    red: 40,
    green: 129,
    blue: 190,
  ),
  ThreadColor(
    code: "308",
    catalog: "Gunold COTTY",
    name: "Harbor Green",
    red: 79,
    green: 109,
    blue: 94,
  ),
  ThreadColor(
    code: "129",
    catalog: "Gunold COTTY",
    name: "Sky Blue",
    red: 136,
    green: 188,
    blue: 231,
  ),
  ThreadColor(
    code: "309",
    catalog: "Gunold COTTY",
    name: "Carousel Green",
    red: 157,
    green: 180,
    blue: 161,
  ),
  ThreadColor(
    code: "130",
    catalog: "Gunold COTTY",
    name: "Silver Lining",
    red: 201,
    green: 224,
    blue: 238,
  ),
  ThreadColor(
    code: "310",
    catalog: "Gunold COTTY",
    name: "Teal",
    red: 39,
    green: 111,
    blue: 157,
  ),
  ThreadColor(
    code: "133",
    catalog: "Gunold COTTY",
    name: "Mango",
    red: 232,
    green: 124,
    blue: 40,
  ),
  ThreadColor(
    code: "311",
    catalog: "Gunold COTTY",
    name: "Medium Plum",
    red: 215,
    green: 129,
    blue: 163,
  ),
  ThreadColor(
    code: "134",
    catalog: "Gunold COTTY",
    name: "Bright Pineapple",
    red: 245,
    green: 203,
    blue: 69,
  ),
  ThreadColor(
    code: "312",
    catalog: "Gunold COTTY",
    name: "Deep Rose",
    red: 152,
    green: 55,
    blue: 67,
  ),
  ThreadColor(
    code: "135",
    catalog: "Gunold COTTY",
    name: "Sunshine",
    red: 248,
    green: 223,
    blue: 126,
  ),
  ThreadColor(
    code: "313",
    catalog: "Gunold COTTY",
    name: "Baroque Rose",
    red: 189,
    green: 98,
    blue: 109,
  ),
  ThreadColor(
    code: "136",
    catalog: "Gunold COTTY",
    name: "Golden Rod",
    red: 245,
    green: 157,
    blue: 36,
  ),
  ThreadColor(
    code: "314",
    catalog: "Gunold COTTY",
    name: "Rose Wine",
    red: 172,
    green: 96,
    blue: 110,
  ),
  ThreadColor(
    code: "137",
    catalog: "Gunold COTTY",
    name: "Pale Sunflower",
    red: 239,
    green: 224,
    blue: 163,
  ),
  ThreadColor(
    code: "315",
    catalog: "Gunold COTTY",
    name: "Champagne Mist",
    red: 238,
    green: 232,
    blue: 213,
  ),
  ThreadColor(
    code: "140",
    catalog: "Gunold COTTY",
    name: "Black",
    red: 47,
    green: 38,
    blue: 47,
  ),
  ThreadColor(
    code: "316",
    catalog: "Gunold COTTY",
    name: "Hyacinth",
    red: 105,
    green: 172,
    blue: 223,
  ),
  ThreadColor(
    code: "142",
    catalog: "Gunold COTTY",
    name: "Gobelin Blue",
    red: 83,
    green: 109,
    blue: 115,
  ),
  ThreadColor(
    code: "317",
    catalog: "Gunold COTTY",
    name: "Buttercup",
    red: 246,
    green: 202,
    blue: 33,
  ),
  ThreadColor(
    code: "143",
    catalog: "Gunold COTTY",
    name: "Stormy Sea",
    red: 114,
    green: 130,
    blue: 128,
  ),
  ThreadColor(
    code: "318",
    catalog: "Gunold COTTY",
    name: "Umbra Grey",
    red: 65,
    green: 65,
    blue: 63,
  ),
  ThreadColor(
    code: "147",
    catalog: "Gunold COTTY",
    name: "Pistachio",
    red: 156,
    green: 160,
    blue: 57,
  ),
  ThreadColor(
    code: "319",
    catalog: "Gunold COTTY",
    name: "Tan",
    red: 192,
    green: 156,
    blue: 113,
  ),
  ThreadColor(
    code: "148",
    catalog: "Gunold COTTY",
    name: "Sea Glass",
    red: 53,
    green: 187,
    blue: 180,
  ),
  ThreadColor(
    code: "322",
    catalog: "Gunold COTTY",
    name: "Purple",
    red: 164,
    green: 73,
    blue: 132,
  ),
  ThreadColor(
    code: "151",
    catalog: "Gunold COTTY",
    name: "Southampton",
    red: 0,
    green: 150,
    blue: 143,
  ),
  ThreadColor(
    code: "323",
    catalog: "Gunold COTTY",
    name: "Light Green/Yellow",
    red: 171,
    green: 165,
    blue: 151,
  ),
  ThreadColor(
    code: "152",
    catalog: "Gunold COTTY",
    name: "Opal Blue",
    red: 197,
    green: 221,
    blue: 208,
  ),
  ThreadColor(
    code: "324",
    catalog: "Gunold COTTY",
    name: "Crabapple",
    red: 204,
    green: 113,
    blue: 98,
  ),
  ThreadColor(
    code: "153",
    catalog: "Gunold COTTY",
    name: "Beauty Rose Medium",
    red: 224,
    green: 51,
    blue: 115,
  ),
  ThreadColor(
    code: "325",
    catalog: "Gunold COTTY",
    name: "Dark Pink",
    red: 166,
    green: 33,
    blue: 75,
  ),
  ThreadColor(
    code: "154",
    catalog: "Gunold COTTY",
    name: "Emberglow",
    red: 237,
    green: 105,
    blue: 75,
  ),
  ThreadColor(
    code: "326",
    catalog: "Gunold COTTY",
    name: "Titanium",
    red: 233,
    green: 229,
    blue: 236,
  ),
  ThreadColor(
    code: "156",
    catalog: "Gunold COTTY",
    name: "Creamy White",
    red: 224,
    green: 213,
    blue: 187,
  ),
  ThreadColor(
    code: "327",
    catalog: "Gunold COTTY",
    name: "Natural White",
    red: 245,
    green: 237,
    blue: 234,
  ),
  ThreadColor(
    code: "157",
    catalog: "Gunold COTTY",
    name: "Lead",
    red: 122,
    green: 137,
    blue: 137,
  ),
  ThreadColor(
    code: "328",
    catalog: "Gunold COTTY",
    name: "Baby Blue Light",
    red: 202,
    green: 224,
    blue: 229,
  ),
  ThreadColor(
    code: "159",
    catalog: "Gunold COTTY",
    name: "Stone Grey",
    red: 177,
    green: 173,
    blue: 173,
  ),
  ThreadColor(
    code: "330",
    catalog: "Gunold COTTY",
    name: "Midnight Navy",
    red: 0,
    green: 11,
    blue: 40,
  ),
  ThreadColor(
    code: "161",
    catalog: "Gunold COTTY",
    name: "Ash Blonde",
    red: 199,
    green: 178,
    blue: 150,
  ),
  ThreadColor(
    code: "332",
    catalog: "Gunold COTTY",
    name: "Light Grey",
    red: 156,
    green: 166,
    blue: 171,
  ),
  ThreadColor(
    code: "162",
    catalog: "Gunold COTTY",
    name: "Laurel Green",
    red: 170,
    green: 189,
    blue: 146,
  ),
  ThreadColor(
    code: "333",
    catalog: "Gunold COTTY",
    name: "Pure Diamond",
    red: 246,
    green: 245,
    blue: 238,
  ),
  ThreadColor(
    code: "169",
    catalog: "Gunold COTTY",
    name: "Carnation",
    red: 219,
    green: 81,
    blue: 109,
  ),
  ThreadColor(
    code: "334",
    catalog: "Gunold COTTY",
    name: "Carnatio",
    red: 235,
    green: 167,
    blue: 196,
  ),
  ThreadColor(
    code: "181",
    catalog: "Gunold COTTY",
    name: "Dark Purple",
    red: 92,
    green: 38,
    blue: 123,
  ),
  ThreadColor(
    code: "335",
    catalog: "Gunold COTTY",
    name: "Cocoa",
    red: 58,
    green: 28,
    blue: 35,
  ),
  ThreadColor(
    code: "199",
    catalog: "Gunold COTTY",
    name: "Purple Maze",
    red: 60,
    green: 30,
    blue: 108,
  ),
  ThreadColor(
    code: "336",
    catalog: "Gunold COTTY",
    name: "Fuchsia",
    red: 158,
    green: 33,
    blue: 95,
  ),
  ThreadColor(
    code: "200",
    catalog: "Gunold COTTY",
    name: "Dark Pink",
    red: 192,
    green: 24,
    blue: 88,
  ),
  ThreadColor(
    code: "337",
    catalog: "Gunold COTTY",
    name: "Rich Burgundy",
    red: 82,
    green: 33,
    blue: 35,
  ),
  ThreadColor(
    code: "208",
    catalog: "Gunold COTTY",
    name: "Orchid",
    red: 223,
    green: 128,
    blue: 158,
  ),
  ThreadColor(
    code: "338",
    catalog: "Gunold COTTY",
    name: "Teal",
    red: 46,
    green: 105,
    blue: 153,
  ),
  ThreadColor(
    code: "209",
    catalog: "Gunold COTTY",
    name: "Light Melon",
    red: 229,
    green: 183,
    blue: 186,
  ),
  ThreadColor(
    code: "339",
    catalog: "Gunold COTTY",
    name: "Desma Blue",
    red: 108,
    green: 117,
    blue: 135,
  ),
  ThreadColor(
    code: "211",
    catalog: "Gunold COTTY",
    name: "Orchid Pink",
    red: 237,
    green: 175,
    blue: 181,
  ),
  ThreadColor(
    code: "340",
    catalog: "Gunold COTTY",
    name: "Window Grey",
    red: 153,
    green: 158,
    blue: 172,
  ),
  ThreadColor(
    code: "214",
    catalog: "Gunold COTTY",
    name: "Peach Bloosom",
    red: 232,
    green: 130,
    blue: 122,
  ),
  ThreadColor(
    code: "342",
    catalog: "Gunold COTTY",
    name: "Light Grape",
    red: 146,
    green: 142,
    blue: 171,
  ),
  ThreadColor(
    code: "221",
    catalog: "Gunold COTTY",
    name: "Pale Salmon",
    red: 228,
    green: 172,
    blue: 173,
  ),
  ThreadColor(
    code: "344",
    catalog: "Gunold COTTY",
    name: "Dark Brown",
    red: 84,
    green: 70,
    blue: 65,
  ),
  ThreadColor(
    code: "231",
    catalog: "Gunold COTTY",
    name: "Dark Green",
    red: 218,
    green: 215,
    blue: 76,
  ),
  ThreadColor(
    code: "346",
    catalog: "Gunold COTTY",
    name: "Hazel",
    red: 148,
    green: 106,
    blue: 94,
  ),
  ThreadColor(
    code: "235",
    catalog: "Gunold COTTY",
    name: "Dark Green",
    red: 33,
    green: 64,
    blue: 50,
  ),
  ThreadColor(
    code: "348",
    catalog: "Gunold COTTY",
    name: "Columbia Blue",
    red: 76,
    green: 150,
    blue: 203,
  ),
  ThreadColor(
    code: "236",
    catalog: "Gunold COTTY",
    name: "Bronze Green",
    red: 50,
    green: 62,
    blue: 37,
  ),
  ThreadColor(
    code: "350",
    catalog: "Gunold COTTY",
    name: "Fire Blue",
    red: 0,
    green: 86,
    blue: 138,
  ),
  ThreadColor(
    code: "237",
    catalog: "Gunold COTTY",
    name: "Caviar",
    red: 34,
    green: 38,
    blue: 34,
  ),
  ThreadColor(
    code: "351",
    catalog: "Gunold COTTY",
    name: "Evergreen",
    red: 0,
    green: 68,
    blue: 59,
  ),
  ThreadColor(
    code: "240",
    catalog: "Gunold COTTY",
    name: "Royal Crest",
    red: 40,
    green: 0,
    blue: 26,
  ),
  ThreadColor(
    code: "352",
    catalog: "Gunold COTTY",
    name: "Atom Red",
    red: 160,
    green: 33,
    blue: 62,
  ),
  ThreadColor(
    code: "243",
    catalog: "Gunold COTTY",
    name: "Suns Purple",
    red: 89,
    green: 53,
    blue: 140,
  ),
  ThreadColor(
    code: "353",
    catalog: "Gunold COTTY",
    name: "Royal",
    red: 44,
    green: 73,
    blue: 139,
  ),
  ThreadColor(
    code: "244",
    catalog: "Gunold COTTY",
    name: "Delft",
    red: 68,
    green: 94,
    blue: 136,
  ),
  ThreadColor(
    code: "354",
    catalog: "Gunold COTTY",
    name: "Charcoal",
    red: 14,
    green: 26,
    blue: 37,
  ),
];
