// This file is generated automatically. DO NOT EDIT.
// Catalog of Isacord colors
import 'package:thread_digit/colors/thread_color.dart';

const List<ThreadColor> isacordColors = [
  ThreadColor(
    code: "0003",
    catalog: "Isacord Polyester",
    name: "Ghost White",
    red: 233,
    green: 232,
    blue: 222,
  ),
  ThreadColor(
    code: "0105",
    catalog: "Isacord Polyester",
    name: "Ash Mist",
    red: 173,
    green: 180,
    blue: 185,
  ),
  ThreadColor(
    code: "0128",
    catalog: "Isacord Polyester",
    name: "Navajo",
    red: 97,
    green: 99,
    blue: 89,
  ),
  ThreadColor(
    code: "0134",
    catalog: "Isacord Polyester",
    name: "Smoky",
    red: 61,
    green: 62,
    blue: 62,
  ),
  ThreadColor(
    code: "0138",
    catalog: "Isacord Polyester",
    name: "Heavy Storm",
    red: 82,
    green: 91,
    blue: 96,
  ),
  ThreadColor(
    code: "0220",
    catalog: "Isacord Polyester",
    name: "Sunbeam",
    red: 255,
    green: 255,
    blue: 102,
  ),
  ThreadColor(
    code: "0230",
    catalog: "Isacord Polyester",
    name: "Easter Dress",
    red: 252,
    green: 243,
    blue: 141,
  ),
  ThreadColor(
    code: "0270",
    catalog: "Isacord Polyester",
    name: "Buttercream",
    red: 255,
    green: 255,
    blue: 225,
  ),
  ThreadColor(
    code: "0454",
    catalog: "Isacord Polyester",
    name: "Olive Drab",
    red: 104,
    green: 102,
    blue: 67,
  ),
  ThreadColor(
    code: "0555",
    catalog: "Isacord Polyester",
    name: "Light Sage",
    red: 127,
    green: 123,
    blue: 108,
  ),
  ThreadColor(
    code: "0576",
    catalog: "Isacord Polyester",
    name: "Very Dark Brown",
    red: 60,
    green: 48,
    blue: 46,
  ),
  ThreadColor(
    code: "0643",
    catalog: "Isacord Polyester",
    name: "Barewood",
    red: 189,
    green: 166,
    blue: 109,
  ),
  ThreadColor(
    code: "0674",
    catalog: "Isacord Polyester",
    name: "Armour",
    red: 105,
    green: 104,
    blue: 91,
  ),
  ThreadColor(
    code: "0703",
    catalog: "Isacord Polyester",
    name: "Orange Peel",
    red: 255,
    green: 204,
    blue: 70,
  ),
  ThreadColor(
    code: "0721",
    catalog: "Isacord Polyester",
    name: "Antique",
    red: 179,
    green: 133,
    blue: 51,
  ),
  ThreadColor(
    code: "0731",
    catalog: "Isacord Polyester",
    name: "Applesauce",
    red: 203,
    green: 160,
    blue: 91,
  ),
  ThreadColor(
    code: "0741",
    catalog: "Isacord Polyester",
    name: "Wheat",
    red: 222,
    green: 190,
    blue: 105,
  ),
  ThreadColor(
    code: "0763",
    catalog: "Isacord Polyester",
    name: "Dark Rattan",
    red: 123,
    green: 113,
    blue: 93,
  ),
  ThreadColor(
    code: "0781",
    catalog: "Isacord Polyester",
    name: "Candlewick",
    red: 240,
    green: 221,
    blue: 192,
  ),
  ThreadColor(
    code: "1030",
    catalog: "Isacord Polyester",
    name: "Passion Fruit",
    red: 238,
    green: 167,
    blue: 102,
  ),
  ThreadColor(
    code: "1032",
    catalog: "Isacord Polyester",
    name: "Bronze",
    red: 173,
    green: 120,
    blue: 41,
  ),
  ThreadColor(
    code: "1133",
    catalog: "Isacord Polyester",
    name: "Peru",
    red: 209,
    green: 162,
    blue: 97,
  ),
  ThreadColor(
    code: "1200",
    catalog: "Isacord Polyester",
    name: "Sunset Orange",
    red: 249,
    green: 139,
    blue: 67,
  ),
  ThreadColor(
    code: "1233",
    catalog: "Isacord Polyester",
    name: "Pony",
    red: 127,
    green: 77,
    blue: 44,
  ),
  ThreadColor(
    code: "1310",
    catalog: "Isacord Polyester",
    name: "Hunter Orange",
    red: 229,
    green: 90,
    blue: 0,
  ),
  ThreadColor(
    code: "1321",
    catalog: "Isacord Polyester",
    name: "Dark Orange",
    red: 210,
    green: 94,
    blue: 30,
  ),
  ThreadColor(
    code: "1322",
    catalog: "Isacord Polyester",
    name: "Dirty Penny",
    red: 138,
    green: 76,
    blue: 52,
  ),
  ThreadColor(
    code: "1344",
    catalog: "Isacord Polyester",
    name: "Coffee Bean",
    red: 100,
    green: 57,
    blue: 40,
  ),
  ThreadColor(
    code: "1526",
    catalog: "Isacord Polyester",
    name: "Apple Butter",
    red: 124,
    green: 54,
    blue: 45,
  ),
  ThreadColor(
    code: "1543",
    catalog: "Isacord Polyester",
    name: "Rusty Rose",
    red: 124,
    green: 76,
    blue: 70,
  ),
  ThreadColor(
    code: "1720",
    catalog: "Isacord Polyester",
    name: "Not Quite Red",
    red: 216,
    green: 44,
    blue: 48,
  ),
  ThreadColor(
    code: "1753",
    catalog: "Isacord Polyester",
    name: "Strawberries n' Cream",
    red: 235,
    green: 93,
    blue: 112,
  ),
  ThreadColor(
    code: "1776",
    catalog: "Isacord Polyester",
    name: "Blackberry",
    red: 49,
    green: 46,
    blue: 47,
  ),
  ThreadColor(
    code: "1800",
    catalog: "Isacord Polyester",
    name: "Wildfire",
    red: 234,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "2211",
    catalog: "Isacord Polyester",
    name: "Pomegranate",
    red: 118,
    green: 35,
    blue: 72,
  ),
  ThreadColor(
    code: "2508",
    catalog: "Isacord Polyester",
    name: "Hot Pink",
    red: 188,
    green: 63,
    blue: 136,
  ),
  ThreadColor(
    code: "2530",
    catalog: "Isacord Polyester",
    name: "Rose",
    red: 243,
    green: 137,
    blue: 178,
  ),
  ThreadColor(
    code: "2532",
    catalog: "Isacord Polyester",
    name: "Pretty In Pink",
    red: 219,
    green: 107,
    blue: 161,
  ),
  ThreadColor(
    code: "2564",
    catalog: "Isacord Polyester",
    name: "Titanium",
    red: 90,
    green: 94,
    blue: 97,
  ),
  ThreadColor(
    code: "2702",
    catalog: "Isacord Polyester",
    name: "Grape Jelly",
    red: 69,
    green: 43,
    blue: 102,
  ),
  ThreadColor(
    code: "2704",
    catalog: "Isacord Polyester",
    name: "Purple Passion",
    red: 101,
    green: 7,
    blue: 101,
  ),
  ThreadColor(
    code: "2723",
    catalog: "Isacord Polyester",
    name: "Peony",
    red: 143,
    green: 51,
    blue: 119,
  ),
  ThreadColor(
    code: "2732",
    catalog: "Isacord Polyester",
    name: "Frosted Orchid",
    red: 155,
    green: 91,
    blue: 170,
  ),
  ThreadColor(
    code: "2762",
    catalog: "Isacord Polyester",
    name: "Misty Rose",
    red: 169,
    green: 145,
    blue: 156,
  ),
  ThreadColor(
    code: "2776",
    catalog: "Isacord Polyester",
    name: "Black Chrome",
    red: 62,
    green: 63,
    blue: 65,
  ),
  ThreadColor(
    code: "2864",
    catalog: "Isacord Polyester",
    name: "Columbine",
    red: 81,
    green: 79,
    blue: 99,
  ),
  ThreadColor(
    code: "2944",
    catalog: "Isacord Polyester",
    name: "Scrumptious Plum",
    red: 49,
    green: 36,
    blue: 50,
  ),
  ThreadColor(
    code: "2953",
    catalog: "Isacord Polyester",
    name: "Concord Fog",
    red: 57,
    green: 52,
    blue: 87,
  ),
  ThreadColor(
    code: "2954",
    catalog: "Isacord Polyester",
    name: "Aubergine",
    red: 43,
    green: 37,
    blue: 62,
  ),
  ThreadColor(
    code: "3030",
    catalog: "Isacord Polyester",
    name: "Amethyst",
    red: 180,
    green: 160,
    blue: 192,
  ),
  ThreadColor(
    code: "3130",
    catalog: "Isacord Polyester",
    name: "Dawn of Violet",
    red: 138,
    green: 141,
    blue: 194,
  ),
  ThreadColor(
    code: "3265",
    catalog: "Isacord Polyester",
    name: "Slate Gray",
    red: 75,
    green: 79,
    blue: 88,
  ),
  ThreadColor(
    code: "3274",
    catalog: "Isacord Polyester",
    name: "Battleship Gray",
    red: 101,
    green: 108,
    blue: 116,
  ),
  ThreadColor(
    code: "3332",
    catalog: "Isacord Polyester",
    name: "Forget Me Not",
    red: 62,
    green: 90,
    blue: 160,
  ),
  ThreadColor(
    code: "3350",
    catalog: "Isacord Polyester",
    name: "Lavender Whisper",
    red: 202,
    green: 213,
    blue: 240,
  ),
  ThreadColor(
    code: "3363",
    catalog: "Isacord Polyester",
    name: "Midnight Blue",
    red: 36,
    green: 46,
    blue: 70,
  ),
  ThreadColor(
    code: "3410",
    catalog: "Isacord Polyester",
    name: "Rich Blue",
    red: 79,
    green: 109,
    blue: 161,
  ),
  ThreadColor(
    code: "3450",
    catalog: "Isacord Polyester",
    name: "Lavendar",
    red: 157,
    green: 165,
    blue: 202,
  ),
  ThreadColor(
    code: "3510",
    catalog: "Isacord Polyester",
    name: "Electric Blue",
    red: 0,
    green: 0,
    blue: 255,
  ),
  ThreadColor(
    code: "3572",
    catalog: "Isacord Polyester",
    name: "Summer Grey",
    red: 157,
    green: 172,
    blue: 185,
  ),
  ThreadColor(
    code: "3574",
    catalog: "Isacord Polyester",
    name: "Darkest Blue",
    red: 32,
    green: 39,
    blue: 48,
  ),
  ThreadColor(
    code: "3630",
    catalog: "Isacord Polyester",
    name: "Sweet Boy",
    red: 122,
    green: 172,
    blue: 231,
  ),
  ThreadColor(
    code: "3631",
    catalog: "Isacord Polyester",
    name: "Tufts Blue",
    red: 76,
    green: 113,
    blue: 160,
  ),
  ThreadColor(
    code: "3644",
    catalog: "Isacord Polyester",
    name: "Royal Navy",
    red: 14,
    green: 56,
    blue: 88,
  ),
  ThreadColor(
    code: "3645",
    catalog: "Isacord Polyester",
    name: "Prussian Blue",
    red: 43,
    green: 55,
    blue: 81,
  ),
  ThreadColor(
    code: "3654",
    catalog: "Isacord Polyester",
    name: "Blue Shadow",
    red: 58,
    green: 82,
    blue: 108,
  ),
  ThreadColor(
    code: "3666",
    catalog: "Isacord Polyester",
    name: "Space",
    red: 40,
    green: 48,
    blue: 58,
  ),
  ThreadColor(
    code: "3713",
    catalog: "Isacord Polyester",
    name: "Cornflower Blue",
    red: 51,
    green: 113,
    blue: 174,
  ),
  ThreadColor(
    code: "3730",
    catalog: "Isacord Polyester",
    name: "Something Blue",
    red: 153,
    green: 198,
    blue: 240,
  ),
  ThreadColor(
    code: "3830",
    catalog: "Isacord Polyester",
    name: "Surfs' Up",
    red: 83,
    green: 151,
    blue: 189,
  ),
  ThreadColor(
    code: "3852",
    catalog: "Isacord Polyester",
    name: "Manatee",
    red: 99,
    green: 118,
    blue: 131,
  ),
  ThreadColor(
    code: "3963",
    catalog: "Isacord Polyester",
    name: "Hint of Blue",
    red: 200,
    green: 228,
    blue: 245,
  ),
  ThreadColor(
    code: "4074",
    catalog: "Isacord Polyester",
    name: "Dimgray",
    red: 89,
    green: 100,
    blue: 104,
  ),
  ThreadColor(
    code: "4152",
    catalog: "Isacord Polyester",
    name: "Serenity",
    red: 128,
    green: 181,
    blue: 189,
  ),
  ThreadColor(
    code: "4740",
    catalog: "Isacord Polyester",
    name: "Aquamarine",
    red: 136,
    green: 213,
    blue: 198,
  ),
  ThreadColor(
    code: "4752",
    catalog: "Isacord Polyester",
    name: "Vintage Blue",
    red: 133,
    green: 171,
    blue: 167,
  ),
  ThreadColor(
    code: "4952",
    catalog: "Isacord Polyester",
    name: "Mystic Blue",
    red: 147,
    green: 206,
    blue: 200,
  ),
  ThreadColor(
    code: "5440",
    catalog: "Isacord Polyester",
    name: "Mint",
    red: 129,
    green: 223,
    blue: 149,
  ),
  ThreadColor(
    code: "5450",
    catalog: "Isacord Polyester",
    name: "Basic Seafoam",
    red: 166,
    green: 216,
    blue: 177,
  ),
  ThreadColor(
    code: "5515",
    catalog: "Isacord Polyester",
    name: "Kelly",
    red: 0,
    green: 164,
    blue: 90,
  ),
  ThreadColor(
    code: "5542",
    catalog: "Isacord Polyester",
    name: "Garden Moss",
    red: 100,
    green: 130,
    blue: 112,
  ),
  ThreadColor(
    code: "5565",
    catalog: "Isacord Polyester",
    name: "Enchanting Forest",
    red: 24,
    green: 56,
    blue: 35,
  ),
  ThreadColor(
    code: "5743",
    catalog: "Isacord Polyester",
    name: "Asparagus",
    red: 82,
    green: 108,
    blue: 81,
  ),
  ThreadColor(
    code: "5830",
    catalog: "Isacord Polyester",
    name: "Chartreuse",
    red: 220,
    green: 255,
    blue: 185,
  ),
  ThreadColor(
    code: "5832",
    catalog: "Isacord Polyester",
    name: "Celery",
    red: 156,
    green: 189,
    blue: 84,
  ),
  ThreadColor(
    code: "6011",
    catalog: "Isacord Polyester",
    name: "Tamarack",
    red: 190,
    green: 231,
    blue: 110,
  ),
  ThreadColor(
    code: "6031",
    catalog: "Isacord Polyester",
    name: "Limelight",
    red: 218,
    green: 224,
    blue: 86,
  ),
  ThreadColor(
    code: "6043",
    catalog: "Isacord Polyester",
    name: "Yellowgreen",
    red: 114,
    green: 119,
    blue: 21,
  ),
  ThreadColor(
    code: "6071",
    catalog: "Isacord Polyester",
    name: "Old Lace",
    red: 183,
    green: 180,
    blue: 150,
  ),
  ThreadColor(
    code: "6151",
    catalog: "Isacord Polyester",
    name: "Lemongrass",
    red: 237,
    green: 237,
    blue: 177,
  ),
  ThreadColor(
    code: "0010",
    catalog: "Isacord Polyester",
    name: "Silky White",
    red: 255,
    green: 255,
    blue: 250,
  ),
  ThreadColor(
    code: "0015",
    catalog: "Isacord Polyester",
    name: "White",
    red: 255,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "0017",
    catalog: "Isacord Polyester",
    name: "Paper White",
    red: 255,
    green: 255,
    blue: 254,
  ),
  ThreadColor(
    code: "0020",
    catalog: "Isacord Polyester",
    name: "Black",
    red: 0,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "0101",
    catalog: "Isacord Polyester",
    name: "Eggshell",
    red: 255,
    green: 255,
    blue: 245,
  ),
  ThreadColor(
    code: "0108",
    catalog: "Isacord Polyester",
    name: "Cobblestone",
    red: 153,
    green: 153,
    blue: 153,
  ),
  ThreadColor(
    code: "0111",
    catalog: "Isacord Polyester",
    name: "Whale",
    red: 127,
    green: 127,
    blue: 127,
  ),
  ThreadColor(
    code: "0112",
    catalog: "Isacord Polyester",
    name: "Leadville",
    red: 127,
    green: 127,
    blue: 128,
  ),
  ThreadColor(
    code: "0124",
    catalog: "Isacord Polyester",
    name: "Fieldstone",
    red: 204,
    green: 204,
    blue: 185,
  ),
  ThreadColor(
    code: "0131",
    catalog: "Isacord Polyester",
    name: "Smoke",
    red: 175,
    green: 175,
    blue: 180,
  ),
  ThreadColor(
    code: "0132",
    catalog: "Isacord Polyester",
    name: "Dark Pewter",
    red: 86,
    green: 89,
    blue: 89,
  ),
  ThreadColor(
    code: "0142",
    catalog: "Isacord Polyester",
    name: "Sterling",
    red: 178,
    green: 178,
    blue: 178,
  ),
  ThreadColor(
    code: "0145",
    catalog: "Isacord Polyester",
    name: "Skylight",
    red: 214,
    green: 214,
    blue: 216,
  ),
  ThreadColor(
    code: "0150",
    catalog: "Isacord Polyester",
    name: "Mystik Grey",
    red: 190,
    green: 190,
    blue: 180,
  ),
  ThreadColor(
    code: "0151",
    catalog: "Isacord Polyester",
    name: "Cloud",
    red: 186,
    green: 170,
    blue: 158,
  ),
  ThreadColor(
    code: "0152",
    catalog: "Isacord Polyester",
    name: "Dolphin",
    red: 140,
    green: 135,
    blue: 125,
  ),
  ThreadColor(
    code: "0182",
    catalog: "Isacord Polyester",
    name: "Saturn Grey",
    red: 214,
    green: 211,
    blue: 214,
  ),
  ThreadColor(
    code: "0184",
    catalog: "Isacord Polyester",
    name: "Pearl",
    red: 224,
    green: 209,
    blue: 198,
  ),
  ThreadColor(
    code: "0221",
    catalog: "Isacord Polyester",
    name: "Light Brass",
    red: 230,
    green: 240,
    blue: 102,
  ),
  ThreadColor(
    code: "0232",
    catalog: "Isacord Polyester",
    name: "Seaweed",
    red: 220,
    green: 226,
    blue: 139,
  ),
  ThreadColor(
    code: "0250",
    catalog: "Isacord Polyester",
    name: "Lemon Frost",
    red: 255,
    green: 255,
    blue: 204,
  ),
  ThreadColor(
    code: "0310",
    catalog: "Isacord Polyester",
    name: "Yellow",
    red: 255,
    green: 255,
    blue: 103,
  ),
  ThreadColor(
    code: "0311",
    catalog: "Isacord Polyester",
    name: "Canary",
    red: 255,
    green: 230,
    blue: 0,
  ),
  ThreadColor(
    code: "0345",
    catalog: "Isacord Polyester",
    name: "Moss",
    red: 165,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "0352",
    catalog: "Isacord Polyester",
    name: "Marsh",
    red: 230,
    green: 240,
    blue: 130,
  ),
  ThreadColor(
    code: "0442",
    catalog: "Isacord Polyester",
    name: "Tarnished Gold",
    red: 204,
    green: 204,
    blue: 51,
  ),
  ThreadColor(
    code: "0453",
    catalog: "Isacord Polyester",
    name: "Army Drab",
    red: 188,
    green: 173,
    blue: 117,
  ),
  ThreadColor(
    code: "0463",
    catalog: "Isacord Polyester",
    name: "Cypress",
    red: 114,
    green: 132,
    blue: 112,
  ),
  ThreadColor(
    code: "0465",
    catalog: "Isacord Polyester",
    name: "Umber",
    red: 115,
    green: 115,
    blue: 51,
  ),
  ThreadColor(
    code: "0501",
    catalog: "Isacord Polyester",
    name: "Sun",
    red: 255,
    green: 237,
    blue: 56,
  ),
  ThreadColor(
    code: "0506",
    catalog: "Isacord Polyester",
    name: "Yellow Bird",
    red: 255,
    green: 240,
    blue: 102,
  ),
  ThreadColor(
    code: "0520",
    catalog: "Isacord Polyester",
    name: "Daffodil",
    red: 255,
    green: 255,
    blue: 153,
  ),
  ThreadColor(
    code: "0532",
    catalog: "Isacord Polyester",
    name: "Champagne",
    red: 240,
    green: 220,
    blue: 170,
  ),
  ThreadColor(
    code: "0542",
    catalog: "Isacord Polyester",
    name: "Ochre",
    red: 204,
    green: 185,
    blue: 0,
  ),
  ThreadColor(
    code: "0546",
    catalog: "Isacord Polyester",
    name: "Ginger",
    red: 204,
    green: 180,
    blue: 65,
  ),
  ThreadColor(
    code: "0552",
    catalog: "Isacord Polyester",
    name: "Flax",
    red: 204,
    green: 180,
    blue: 135,
  ),
  ThreadColor(
    code: "0600",
    catalog: "Isacord Polyester",
    name: "Citrus",
    red: 255,
    green: 255,
    blue: 0,
  ),
  ThreadColor(
    code: "0605",
    catalog: "Isacord Polyester",
    name: "Daisy",
    red: 255,
    green: 240,
    blue: 0,
  ),
  ThreadColor(
    code: "0608",
    catalog: "Isacord Polyester",
    name: "Sunshine",
    red: 255,
    green: 220,
    blue: 0,
  ),
  ThreadColor(
    code: "0630",
    catalog: "Isacord Polyester",
    name: "Buttercup",
    red: 255,
    green: 250,
    blue: 153,
  ),
  ThreadColor(
    code: "0640",
    catalog: "Isacord Polyester",
    name: "Parchment",
    red: 255,
    green: 240,
    blue: 204,
  ),
  ThreadColor(
    code: "0651",
    catalog: "Isacord Polyester",
    name: "Cornsilk",
    red: 232,
    green: 202,
    blue: 134,
  ),
  ThreadColor(
    code: "0660",
    catalog: "Isacord Polyester",
    name: "Vanilla",
    red: 255,
    green: 250,
    blue: 204,
  ),
  ThreadColor(
    code: "0670",
    catalog: "Isacord Polyester",
    name: "Cream",
    red: 255,
    green: 255,
    blue: 240,
  ),
  ThreadColor(
    code: "0672",
    catalog: "Isacord Polyester",
    name: "Baquette",
    red: 225,
    green: 204,
    blue: 180,
  ),
  ThreadColor(
    code: "0700",
    catalog: "Isacord Polyester",
    name: "Bright Yellow",
    red: 255,
    green: 173,
    blue: 20,
  ),
  ThreadColor(
    code: "0702",
    catalog: "Isacord Polyester",
    name: "Papaya",
    red: 255,
    green: 230,
    blue: 75,
  ),
  ThreadColor(
    code: "0704",
    catalog: "Isacord Polyester",
    name: "Gold",
    red: 245,
    green: 240,
    blue: 102,
  ),
  ThreadColor(
    code: "0713",
    catalog: "Isacord Polyester",
    name: "Lemon",
    red: 255,
    green: 240,
    blue: 130,
  ),
  ThreadColor(
    code: "0722",
    catalog: "Isacord Polyester",
    name: "Khaki",
    red: 153,
    green: 130,
    blue: 110,
  ),
  ThreadColor(
    code: "0747",
    catalog: "Isacord Polyester",
    name: "Golden Brown",
    red: 111,
    green: 84,
    blue: 49,
  ),
  ThreadColor(
    code: "0761",
    catalog: "Isacord Polyester",
    name: "Oat",
    red: 245,
    green: 235,
    blue: 204,
  ),
  ThreadColor(
    code: "0776",
    catalog: "Isacord Polyester",
    name: "Sage",
    red: 135,
    green: 120,
    blue: 102,
  ),
  ThreadColor(
    code: "0800",
    catalog: "Isacord Polyester",
    name: "Goldenrod",
    red: 253,
    green: 172,
    blue: 64,
  ),
  ThreadColor(
    code: "0811",
    catalog: "Isacord Polyester",
    name: "Candlelight",
    red: 255,
    green: 204,
    blue: 0,
  ),
  ThreadColor(
    code: "0821",
    catalog: "Isacord Polyester",
    name: "Honey",
    red: 240,
    green: 204,
    blue: 51,
  ),
  ThreadColor(
    code: "0822",
    catalog: "Isacord Polyester",
    name: "Palomino",
    red: 230,
    green: 204,
    blue: 110,
  ),
  ThreadColor(
    code: "0824",
    catalog: "Isacord Polyester",
    name: "Liberty Gold",
    red: 225,
    green: 127,
    blue: 61,
  ),
  ThreadColor(
    code: "0832",
    catalog: "Isacord Polyester",
    name: "Sisal",
    red: 204,
    green: 170,
    blue: 120,
  ),
  ThreadColor(
    code: "0842",
    catalog: "Isacord Polyester",
    name: "Toffee",
    red: 240,
    green: 190,
    blue: 130,
  ),
  ThreadColor(
    code: "0851",
    catalog: "Isacord Polyester",
    name: "Old Gold",
    red: 240,
    green: 204,
    blue: 145,
  ),
  ThreadColor(
    code: "0853",
    catalog: "Isacord Polyester",
    name: "Pecan",
    red: 170,
    green: 140,
    blue: 102,
  ),
  ThreadColor(
    code: "0861",
    catalog: "Isacord Polyester",
    name: "Tantone",
    red: 221,
    green: 204,
    blue: 164,
  ),
  ThreadColor(
    code: "0862",
    catalog: "Isacord Polyester",
    name: "Wild Rice",
    red: 163,
    green: 150,
    blue: 135,
  ),
  ThreadColor(
    code: "0870",
    catalog: "Isacord Polyester",
    name: "Muslin",
    red: 255,
    green: 250,
    blue: 230,
  ),
  ThreadColor(
    code: "0873",
    catalog: "Isacord Polyester",
    name: "Stone",
    red: 195,
    green: 185,
    blue: 160,
  ),
  ThreadColor(
    code: "0874",
    catalog: "Isacord Polyester",
    name: "Gravel",
    red: 190,
    green: 160,
    blue: 145,
  ),
  ThreadColor(
    code: "0904",
    catalog: "Isacord Polyester",
    name: "Spanish Gold",
    red: 216,
    green: 140,
    blue: 2,
  ),
  ThreadColor(
    code: "0922",
    catalog: "Isacord Polyester",
    name: "Ashley Gold",
    red: 175,
    green: 117,
    blue: 5,
  ),
  ThreadColor(
    code: "0931",
    catalog: "Isacord Polyester",
    name: "Honey Gold",
    red: 188,
    green: 109,
    blue: 10,
  ),
  ThreadColor(
    code: "0932",
    catalog: "Isacord Polyester",
    name: "Nutmeg",
    red: 185,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "0933",
    catalog: "Isacord Polyester",
    name: "Redwood",
    red: 153,
    green: 102,
    blue: 51,
  ),
  ThreadColor(
    code: "0934",
    catalog: "Isacord Polyester",
    name: "Fawn",
    red: 204,
    green: 180,
    blue: 153,
  ),
  ThreadColor(
    code: "0940",
    catalog: "Isacord Polyester",
    name: "Autumn Leaf",
    red: 204,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "0941",
    catalog: "Isacord Polyester",
    name: "Golden Grain",
    red: 180,
    green: 130,
    blue: 70,
  ),
  ThreadColor(
    code: "0945",
    catalog: "Isacord Polyester",
    name: "Pine Park",
    red: 140,
    green: 110,
    blue: 70,
  ),
  ThreadColor(
    code: "0970",
    catalog: "Isacord Polyester",
    name: "Linen",
    red: 255,
    green: 255,
    blue: 230,
  ),
  ThreadColor(
    code: "1055",
    catalog: "Isacord Polyester",
    name: "Bark",
    red: 153,
    green: 102,
    blue: 52,
  ),
  ThreadColor(
    code: "1060",
    catalog: "Isacord Polyester",
    name: "Shrimp Pink",
    red: 255,
    green: 230,
    blue: 185,
  ),
  ThreadColor(
    code: "1061",
    catalog: "Isacord Polyester",
    name: "Taupe",
    red: 200,
    green: 175,
    blue: 140,
  ),
  ThreadColor(
    code: "1102",
    catalog: "Isacord Polyester",
    name: "Pumpkin",
    red: 255,
    green: 170,
    blue: 51,
  ),
  ThreadColor(
    code: "1106",
    catalog: "Isacord Polyester",
    name: "Orange",
    red: 255,
    green: 127,
    blue: 30,
  ),
  ThreadColor(
    code: "1114",
    catalog: "Isacord Polyester",
    name: "Clay",
    red: 240,
    green: 150,
    blue: 70,
  ),
  ThreadColor(
    code: "1115",
    catalog: "Isacord Polyester",
    name: "Copper",
    red: 158,
    green: 84,
    blue: 10,
  ),
  ThreadColor(
    code: "1120",
    catalog: "Isacord Polyester",
    name: "Sunset",
    red: 255,
    green: 188,
    blue: 33,
  ),
  ThreadColor(
    code: "1123",
    catalog: "Isacord Polyester",
    name: "Caramel Cream",
    red: 193,
    green: 168,
    blue: 117,
  ),
  ThreadColor(
    code: "1134",
    catalog: "Isacord Polyester",
    name: "Light Cocoa",
    red: 140,
    green: 89,
    blue: 51,
  ),
  ThreadColor(
    code: "1140",
    catalog: "Isacord Polyester",
    name: "Meringue",
    red: 225,
    green: 220,
    blue: 175,
  ),
  ThreadColor(
    code: "1141",
    catalog: "Isacord Polyester",
    name: "Tan",
    red: 232,
    green: 178,
    blue: 130,
  ),
  ThreadColor(
    code: "1154",
    catalog: "Isacord Polyester",
    name: "Penny",
    red: 140,
    green: 89,
    blue: 52,
  ),
  ThreadColor(
    code: "1172",
    catalog: "Isacord Polyester",
    name: "Ivory",
    red: 240,
    green: 225,
    blue: 204,
  ),
  ThreadColor(
    code: "1220",
    catalog: "Isacord Polyester",
    name: "Apricot",
    red: 255,
    green: 190,
    blue: 102,
  ),
  ThreadColor(
    code: "1300",
    catalog: "Isacord Polyester",
    name: "Tangerine",
    red: 255,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "1301",
    catalog: "Isacord Polyester",
    name: "Paprika",
    red: 209,
    green: 68,
    blue: 20,
  ),
  ThreadColor(
    code: "1304",
    catalog: "Isacord Polyester",
    name: "Red Pepper",
    red: 255,
    green: 125,
    blue: 0,
  ),
  ThreadColor(
    code: "1305",
    catalog: "Isacord Polyester",
    name: "Fox Fire",
    red: 255,
    green: 140,
    blue: 0,
  ),
  ThreadColor(
    code: "1306",
    catalog: "Isacord Polyester",
    name: "Devil Red",
    red: 249,
    green: 89,
    blue: 81,
  ),
  ThreadColor(
    code: "1311",
    catalog: "Isacord Polyester",
    name: "Date",
    red: 240,
    green: 140,
    blue: 75,
  ),
  ThreadColor(
    code: "1312",
    catalog: "Isacord Polyester",
    name: "Burnt Orange",
    red: 155,
    green: 48,
    blue: 28,
  ),
  ThreadColor(
    code: "1332",
    catalog: "Isacord Polyester",
    name: "Harvest",
    red: 188,
    green: 79,
    blue: 70,
  ),
  ThreadColor(
    code: "1334",
    catalog: "Isacord Polyester",
    name: "Spice",
    red: 204,
    green: 102,
    blue: 51,
  ),
  ThreadColor(
    code: "1335",
    catalog: "Isacord Polyester",
    name: "Dark Rust",
    red: 163,
    green: 38,
    blue: 56,
  ),
  ThreadColor(
    code: "1342",
    catalog: "Isacord Polyester",
    name: "Rust",
    red: 172,
    green: 77,
    blue: 45,
  ),
  ThreadColor(
    code: "1346",
    catalog: "Isacord Polyester",
    name: "Cinnamon",
    red: 135,
    green: 90,
    blue: 45,
  ),
  ThreadColor(
    code: "1351",
    catalog: "Isacord Polyester",
    name: "Starfish",
    red: 255,
    green: 195,
    blue: 153,
  ),
  ThreadColor(
    code: "1352",
    catalog: "Isacord Polyester",
    name: "Salmon",
    red: 255,
    green: 180,
    blue: 130,
  ),
  ThreadColor(
    code: "1355",
    catalog: "Isacord Polyester",
    name: "Fox",
    red: 152,
    green: 102,
    blue: 51,
  ),
  ThreadColor(
    code: "1362",
    catalog: "Isacord Polyester",
    name: "Shrimp",
    red: 255,
    green: 215,
    blue: 165,
  ),
  ThreadColor(
    code: "1366",
    catalog: "Isacord Polyester",
    name: "Mahogany",
    red: 110,
    green: 51,
    blue: 0,
  ),
  ThreadColor(
    code: "1375",
    catalog: "Isacord Polyester",
    name: "Dark Charcoal",
    red: 40,
    green: 40,
    blue: 33,
  ),
  ThreadColor(
    code: "1430",
    catalog: "Isacord Polyester",
    name: "Melon",
    red: 255,
    green: 165,
    blue: 125,
  ),
  ThreadColor(
    code: "1514",
    catalog: "Isacord Polyester",
    name: "Brick",
    red: 155,
    green: 48,
    blue: 29,
  ),
  ThreadColor(
    code: "1521",
    catalog: "Isacord Polyester",
    name: "Flamingo",
    red: 226,
    green: 61,
    blue: 40,
  ),
  ThreadColor(
    code: "1532",
    catalog: "Isacord Polyester",
    name: "Coral",
    red: 255,
    green: 185,
    blue: 170,
  ),
  ThreadColor(
    code: "1565",
    catalog: "Isacord Polyester",
    name: "Espresso",
    red: 102,
    green: 89,
    blue: 76,
  ),
  ThreadColor(
    code: "1600",
    catalog: "Isacord Polyester",
    name: "Spanish Tile",
    red: 235,
    green: 140,
    blue: 115,
  ),
  ThreadColor(
    code: "1701",
    catalog: "Isacord Polyester",
    name: "Red Berry",
    red: 255,
    green: 102,
    blue: 51,
  ),
  ThreadColor(
    code: "1703",
    catalog: "Isacord Polyester",
    name: "Poppy",
    red: 255,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1704",
    catalog: "Isacord Polyester",
    name: "Candy Apple",
    red: 232,
    green: 17,
    blue: 45,
  ),
  ThreadColor(
    code: "1725",
    catalog: "Isacord Polyester",
    name: "Terra Cotta",
    red: 220,
    green: 102,
    blue: 51,
  ),
  ThreadColor(
    code: "1755",
    catalog: "Isacord Polyester",
    name: "Hyacinth",
    red: 245,
    green: 214,
    blue: 214,
  ),
  ThreadColor(
    code: "1760",
    catalog: "Isacord Polyester",
    name: "Twine",
    red: 245,
    green: 204,
    blue: 175,
  ),
  ThreadColor(
    code: "1761",
    catalog: "Isacord Polyester",
    name: "Tea Rose",
    red: 255,
    green: 220,
    blue: 210,
  ),
  ThreadColor(
    code: "1805",
    catalog: "Isacord Polyester",
    name: "Strawberry",
    red: 193,
    green: 5,
    blue: 56,
  ),
  ThreadColor(
    code: "1840",
    catalog: "Isacord Polyester",
    name: "Corsage",
    red: 255,
    green: 175,
    blue: 175,
  ),
  ThreadColor(
    code: "1860",
    catalog: "Isacord Polyester",
    name: "Shell",
    red: 255,
    green: 245,
    blue: 240,
  ),
  ThreadColor(
    code: "1874",
    catalog: "Isacord Polyester",
    name: "Pewter",
    red: 130,
    green: 114,
    blue: 99,
  ),
  ThreadColor(
    code: "1876",
    catalog: "Isacord Polyester",
    name: "Chocolate",
    red: 64,
    green: 38,
    blue: 19,
  ),
  ThreadColor(
    code: "1900",
    catalog: "Isacord Polyester",
    name: "Geranium",
    red: 240,
    green: 0,
    blue: 102,
  ),
  ThreadColor(
    code: "1902",
    catalog: "Isacord Polyester",
    name: "Poinsettia",
    red: 204,
    green: 0,
    blue: 0,
  ),
  ThreadColor(
    code: "1903",
    catalog: "Isacord Polyester",
    name: "Lipstick",
    red: 229,
    green: 5,
    blue: 58,
  ),
  ThreadColor(
    code: "1904",
    catalog: "Isacord Polyester",
    name: "Cardinal",
    red: 191,
    green: 10,
    blue: 48,
  ),
  ThreadColor(
    code: "1906",
    catalog: "Isacord Polyester",
    name: "Tulip",
    red: 204,
    green: 51,
    blue: 102,
  ),
  ThreadColor(
    code: "1911",
    catalog: "Isacord Polyester",
    name: "Foliage Rose",
    red: 170,
    green: 0,
    blue: 51,
  ),
  ThreadColor(
    code: "1912",
    catalog: "Isacord Polyester",
    name: "Winterberry",
    red: 175,
    green: 0,
    blue: 75,
  ),
  ThreadColor(
    code: "1913",
    catalog: "Isacord Polyester",
    name: "Cherry",
    red: 204,
    green: 51,
    blue: 0,
  ),
  ThreadColor(
    code: "1921",
    catalog: "Isacord Polyester",
    name: "Blossom",
    red: 210,
    green: 130,
    blue: 130,
  ),
  ThreadColor(
    code: "1940",
    catalog: "Isacord Polyester",
    name: "Chrysanthemum",
    red: 255,
    green: 0,
    blue: 147,
  ),
  ThreadColor(
    code: "1950",
    catalog: "Isacord Polyester",
    name: "Tropical Pink",
    red: 214,
    green: 0,
    blue: 158,
  ),
  ThreadColor(
    code: "1972",
    catalog: "Isacord Polyester",
    name: "Silvery Grey",
    red: 140,
    green: 137,
    blue: 132,
  ),
  ThreadColor(
    code: "2011",
    catalog: "Isacord Polyester",
    name: "Fire Engine",
    red: 153,
    green: 33,
    blue: 53,
  ),
  ThreadColor(
    code: "2022",
    catalog: "Isacord Polyester",
    name: "Rio Red",
    red: 140,
    green: 38,
    blue: 51,
  ),
  ThreadColor(
    code: "2051",
    catalog: "Isacord Polyester",
    name: "Teaberry",
    red: 220,
    green: 180,
    blue: 180,
  ),
  ThreadColor(
    code: "2101",
    catalog: "Isacord Polyester",
    name: "Country Red",
    red: 168,
    green: 12,
    blue: 53,
  ),
  ThreadColor(
    code: "2113",
    catalog: "Isacord Polyester",
    name: "Cranberry",
    red: 117,
    green: 38,
    blue: 51,
  ),
  ThreadColor(
    code: "2115",
    catalog: "Isacord Polyester",
    name: "Beet Red",
    red: 122,
    green: 38,
    blue: 56,
  ),
  ThreadColor(
    code: "2123",
    catalog: "Isacord Polyester",
    name: "Bordeaux",
    red: 135,
    green: 0,
    blue: 51,
  ),
  ThreadColor(
    code: "2152",
    catalog: "Isacord Polyester",
    name: "Heather Pink",
    red: 255,
    green: 153,
    blue: 170,
  ),
  ThreadColor(
    code: "2153",
    catalog: "Isacord Polyester",
    name: "Dusty Mauve",
    red: 220,
    green: 153,
    blue: 160,
  ),
  ThreadColor(
    code: "2155",
    catalog: "Isacord Polyester",
    name: "Pink Tulip",
    red: 255,
    green: 204,
    blue: 204,
  ),
  ThreadColor(
    code: "2160",
    catalog: "Isacord Polyester",
    name: "Iced Pink",
    red: 250,
    green: 220,
    blue: 220,
  ),
  ThreadColor(
    code: "2170",
    catalog: "Isacord Polyester",
    name: "Chiffon",
    red: 255,
    green: 250,
    blue: 245,
  ),
  ThreadColor(
    code: "2171",
    catalog: "Isacord Polyester",
    name: "Blush",
    red: 255,
    green: 245,
    blue: 250,
  ),
  ThreadColor(
    code: "2220",
    catalog: "Isacord Polyester",
    name: "Tropicana",
    red: 255,
    green: 160,
    blue: 204,
  ),
  ThreadColor(
    code: "2222",
    catalog: "Isacord Polyester",
    name: "Burgundy",
    red: 153,
    green: 75,
    blue: 102,
  ),
  ThreadColor(
    code: "2224",
    catalog: "Isacord Polyester",
    name: "Claret",
    red: 122,
    green: 38,
    blue: 57,
  ),
  ThreadColor(
    code: "2241",
    catalog: "Isacord Polyester",
    name: "Mauve",
    red: 204,
    green: 140,
    blue: 150,
  ),
  ThreadColor(
    code: "2250",
    catalog: "Isacord Polyester",
    name: "Petal Pink",
    red: 255,
    green: 204,
    blue: 215,
  ),
  ThreadColor(
    code: "2300",
    catalog: "Isacord Polyester",
    name: "Bright Ruby",
    red: 255,
    green: 51,
    blue: 153,
  ),
  ThreadColor(
    code: "2320",
    catalog: "Isacord Polyester",
    name: "Raspberry",
    red: 220,
    green: 102,
    blue: 130,
  ),
  ThreadColor(
    code: "2333",
    catalog: "Isacord Polyester",
    name: "Wine",
    red: 153,
    green: 51,
    blue: 102,
  ),
  ThreadColor(
    code: "2336",
    catalog: "Isacord Polyester",
    name: "Maroon",
    red: 81,
    green: 45,
    blue: 68,
  ),
  ThreadColor(
    code: "2363",
    catalog: "Isacord Polyester",
    name: "Carnation",
    red: 255,
    green: 235,
    blue: 235,
  ),
  ThreadColor(
    code: "2500",
    catalog: "Isacord Polyester",
    name: "Boysenberry",
    red: 185,
    green: 80,
    blue: 130,
  ),
  ThreadColor(
    code: "2504",
    catalog: "Isacord Polyester",
    name: "Plum",
    red: 163,
    green: 5,
    blue: 127,
  ),
  ThreadColor(
    code: "2506",
    catalog: "Isacord Polyester",
    name: "Cerise",
    red: 175,
    green: 60,
    blue: 120,
  ),
  ThreadColor(
    code: "2520",
    catalog: "Isacord Polyester",
    name: "Garden Rose",
    red: 255,
    green: 204,
    blue: 180,
  ),
  ThreadColor(
    code: "2521",
    catalog: "Isacord Polyester",
    name: "Fuchsia",
    red: 226,
    green: 60,
    blue: 115,
  ),
  ThreadColor(
    code: "2550",
    catalog: "Isacord Polyester",
    name: "Soft Pink",
    red: 255,
    green: 170,
    blue: 220,
  ),
  ThreadColor(
    code: "2560",
    catalog: "Isacord Polyester",
    name: "Azalea Pink",
    red: 255,
    green: 185,
    blue: 204,
  ),
  ThreadColor(
    code: "2600",
    catalog: "Isacord Polyester",
    name: "Dusty Grape",
    red: 204,
    green: 102,
    blue: 153,
  ),
  ThreadColor(
    code: "2640",
    catalog: "Isacord Polyester",
    name: "Frosted Plum",
    red: 225,
    green: 170,
    blue: 245,
  ),
  ThreadColor(
    code: "2650",
    catalog: "Isacord Polyester",
    name: "Impatiens",
    red: 255,
    green: 204,
    blue: 230,
  ),
  ThreadColor(
    code: "2655",
    catalog: "Isacord Polyester",
    name: "Aura",
    red: 235,
    green: 204,
    blue: 215,
  ),
  ThreadColor(
    code: "2674",
    catalog: "Isacord Polyester",
    name: "Steel",
    red: 140,
    green: 140,
    blue: 150,
  ),
  ThreadColor(
    code: "2711",
    catalog: "Isacord Polyester",
    name: "Dark Current",
    red: 153,
    green: 0,
    blue: 125,
  ),
  ThreadColor(
    code: "2715",
    catalog: "Isacord Polyester",
    name: "Pansy",
    red: 153,
    green: 0,
    blue: 153,
  ),
  ThreadColor(
    code: "2764",
    catalog: "Isacord Polyester",
    name: "Violet",
    red: 183,
    green: 114,
    blue: 142,
  ),
  ThreadColor(
    code: "2810",
    catalog: "Isacord Polyester",
    name: "Orchid",
    red: 204,
    green: 102,
    blue: 204,
  ),
  ThreadColor(
    code: "2830",
    catalog: "Isacord Polyester",
    name: "Wild Iris",
    red: 204,
    green: 140,
    blue: 204,
  ),
  ThreadColor(
    code: "2900",
    catalog: "Isacord Polyester",
    name: "Deep Purple",
    red: 89,
    green: 17,
    blue: 142,
  ),
  ThreadColor(
    code: "2905",
    catalog: "Isacord Polyester",
    name: "Iris Blue",
    red: 142,
    green: 71,
    blue: 173,
  ),
  ThreadColor(
    code: "2910",
    catalog: "Isacord Polyester",
    name: "Grape",
    red: 170,
    green: 114,
    blue: 191,
  ),
  ThreadColor(
    code: "2920",
    catalog: "Isacord Polyester",
    name: "Purple",
    red: 137,
    green: 119,
    blue: 186,
  ),
  ThreadColor(
    code: "3040",
    catalog: "Isacord Polyester",
    name: "Lavender",
    red: 235,
    green: 204,
    blue: 245,
  ),
  ThreadColor(
    code: "3045",
    catalog: "Isacord Polyester",
    name: "Cachet",
    red: 230,
    green: 190,
    blue: 220,
  ),
  ThreadColor(
    code: "3102",
    catalog: "Isacord Polyester",
    name: "Provence",
    red: 75,
    green: 0,
    blue: 153,
  ),
  ThreadColor(
    code: "3110",
    catalog: "Isacord Polyester",
    name: "Dark Ink",
    red: 120,
    green: 51,
    blue: 153,
  ),
  ThreadColor(
    code: "3114",
    catalog: "Isacord Polyester",
    name: "Purple Twist",
    red: 68,
    green: 35,
    blue: 89,
  ),
  ThreadColor(
    code: "3210",
    catalog: "Isacord Polyester",
    name: "Blueberry",
    red: 105,
    green: 89,
    blue: 205,
  ),
  ThreadColor(
    code: "3211",
    catalog: "Isacord Polyester",
    name: "Twilight",
    red: 98,
    green: 74,
    blue: 147,
  ),
  ThreadColor(
    code: "3241",
    catalog: "Isacord Polyester",
    name: "Amethyst Frost",
    red: 210,
    green: 170,
    blue: 210,
  ),
  ThreadColor(
    code: "3251",
    catalog: "Isacord Polyester",
    name: "Haze",
    red: 168,
    green: 147,
    blue: 173,
  ),
  ThreadColor(
    code: "3323",
    catalog: "Isacord Polyester",
    name: "Delft",
    red: 80,
    green: 0,
    blue: 120,
  ),
  ThreadColor(
    code: "3331",
    catalog: "Isacord Polyester",
    name: "Cadet Blue",
    red: 175,
    green: 170,
    blue: 255,
  ),
  ThreadColor(
    code: "3333",
    catalog: "Isacord Polyester",
    name: "Fire Blue",
    red: 30,
    green: 28,
    blue: 119,
  ),
  ThreadColor(
    code: "3335",
    catalog: "Isacord Polyester",
    name: "Flag Blue",
    red: 0,
    green: 56,
    blue: 147,
  ),
  ThreadColor(
    code: "3344",
    catalog: "Isacord Polyester",
    name: "Midnight",
    red: 12,
    green: 56,
    blue: 68,
  ),
  ThreadColor(
    code: "3353",
    catalog: "Isacord Polyester",
    name: "Light Midnight",
    red: 0,
    green: 0,
    blue: 125,
  ),
  ThreadColor(
    code: "3355",
    catalog: "Isacord Polyester",
    name: "Dark Indigo",
    red: 0,
    green: 0,
    blue: 102,
  ),
  ThreadColor(
    code: "3444",
    catalog: "Isacord Polyester",
    name: "Concord",
    red: 80,
    green: 90,
    blue: 102,
  ),
  ThreadColor(
    code: "3522",
    catalog: "Isacord Polyester",
    name: "Blue",
    red: 45,
    green: 51,
    blue: 142,
  ),
  ThreadColor(
    code: "3536",
    catalog: "Isacord Polyester",
    name: "Heraldic",
    red: 102,
    green: 0,
    blue: 102,
  ),
  ThreadColor(
    code: "3541",
    catalog: "Isacord Polyester",
    name: "Venetian Blue",
    red: 153,
    green: 0,
    blue: 204,
  ),
  ThreadColor(
    code: "3543",
    catalog: "Isacord Polyester",
    name: "Royal Blue",
    red: 51,
    green: 0,
    blue: 204,
  ),
  ThreadColor(
    code: "3544",
    catalog: "Isacord Polyester",
    name: "Sapphire",
    red: 0,
    green: 56,
    blue: 146,
  ),
  ThreadColor(
    code: "3554",
    catalog: "Isacord Polyester",
    name: "Navy",
    red: 2,
    green: 40,
    blue: 58,
  ),
  ThreadColor(
    code: "3600",
    catalog: "Isacord Polyester",
    name: "Nordic Blue",
    red: 102,
    green: 102,
    blue: 204,
  ),
  ThreadColor(
    code: "3611",
    catalog: "Isacord Polyester",
    name: "Blue Ribbon",
    red: 125,
    green: 102,
    blue: 255,
  ),
  ThreadColor(
    code: "3612",
    catalog: "Isacord Polyester",
    name: "Starlight Blue",
    red: 45,
    green: 51,
    blue: 141,
  ),
  ThreadColor(
    code: "3622",
    catalog: "Isacord Polyester",
    name: "Imperial Blue",
    red: 48,
    green: 68,
    blue: 181,
  ),
  ThreadColor(
    code: "3640",
    catalog: "Isacord Polyester",
    name: "Lake Blue",
    red: 153,
    green: 186,
    blue: 221,
  ),
  ThreadColor(
    code: "3641",
    catalog: "Isacord Polyester",
    name: "Wedgewood",
    red: 170,
    green: 180,
    blue: 215,
  ),
  ThreadColor(
    code: "3650",
    catalog: "Isacord Polyester",
    name: "Ice Cap",
    red: 240,
    green: 245,
    blue: 250,
  ),
  ThreadColor(
    code: "3652",
    catalog: "Isacord Polyester",
    name: "Baby Blue",
    red: 147,
    green: 183,
    blue: 209,
  ),
  ThreadColor(
    code: "3732",
    catalog: "Isacord Polyester",
    name: "Slate Blue",
    red: 0,
    green: 51,
    blue: 76,
  ),
  ThreadColor(
    code: "3743",
    catalog: "Isacord Polyester",
    name: "Harbor",
    red: 80,
    green: 102,
    blue: 125,
  ),
  ThreadColor(
    code: "3750",
    catalog: "Isacord Polyester",
    name: "Winter Frost",
    red: 183,
    green: 204,
    blue: 219,
  ),
  ThreadColor(
    code: "3761",
    catalog: "Isacord Polyester",
    name: "Winter Sky",
    red: 240,
    green: 250,
    blue: 255,
  ),
  ThreadColor(
    code: "3770",
    catalog: "Isacord Polyester",
    name: "Oyster",
    red: 214,
    green: 216,
    blue: 211,
  ),
  ThreadColor(
    code: "3810",
    catalog: "Isacord Polyester",
    name: "Laguna",
    red: 120,
    green: 153,
    blue: 190,
  ),
  ThreadColor(
    code: "3815",
    catalog: "Isacord Polyester",
    name: "Reef Blue",
    red: 0,
    green: 142,
    blue: 214,
  ),
  ThreadColor(
    code: "3820",
    catalog: "Isacord Polyester",
    name: "Celestial",
    red: 150,
    green: 190,
    blue: 230,
  ),
  ThreadColor(
    code: "3840",
    catalog: "Isacord Polyester",
    name: "Oxford",
    red: 235,
    green: 250,
    blue: 255,
  ),
  ThreadColor(
    code: "3842",
    catalog: "Isacord Polyester",
    name: "Copenhagen",
    red: 120,
    green: 130,
    blue: 140,
  ),
  ThreadColor(
    code: "3900",
    catalog: "Isacord Polyester",
    name: "Cerulean",
    red: 0,
    green: 127,
    blue: 204,
  ),
  ThreadColor(
    code: "3901",
    catalog: "Isacord Polyester",
    name: "Tropical Blue",
    red: 51,
    green: 153,
    blue: 204,
  ),
  ThreadColor(
    code: "3902",
    catalog: "Isacord Polyester",
    name: "Colonial Blue",
    red: 0,
    green: 91,
    blue: 191,
  ),
  ThreadColor(
    code: "3910",
    catalog: "Isacord Polyester",
    name: "Crystal Blue",
    red: 153,
    green: 204,
    blue: 240,
  ),
  ThreadColor(
    code: "3951",
    catalog: "Isacord Polyester",
    name: "Azure Blue",
    red: 180,
    green: 200,
    blue: 225,
  ),
  ThreadColor(
    code: "3953",
    catalog: "Isacord Polyester",
    name: "Ocean Blue",
    red: 125,
    green: 125,
    blue: 140,
  ),
  ThreadColor(
    code: "3962",
    catalog: "Isacord Polyester",
    name: "River Mist",
    red: 204,
    green: 225,
    blue: 245,
  ),
  ThreadColor(
    code: "3971",
    catalog: "Isacord Polyester",
    name: "Silver",
    red: 204,
    green: 204,
    blue: 204,
  ),
  ThreadColor(
    code: "4010",
    catalog: "Isacord Polyester",
    name: "Caribbean Blue",
    red: 0,
    green: 190,
    blue: 204,
  ),
  ThreadColor(
    code: "4032",
    catalog: "Isacord Polyester",
    name: "Teal",
    red: 102,
    green: 153,
    blue: 175,
  ),
  ThreadColor(
    code: "4071",
    catalog: "Isacord Polyester",
    name: "Glacier Green",
    red: 245,
    green: 245,
    blue: 250,
  ),
  ThreadColor(
    code: "4073",
    catalog: "Isacord Polyester",
    name: "Metal",
    red: 155,
    green: 153,
    blue: 147,
  ),
  ThreadColor(
    code: "4101",
    catalog: "Isacord Polyester",
    name: "Wave Blue",
    red: 0,
    green: 165,
    blue: 180,
  ),
  ThreadColor(
    code: "4103",
    catalog: "Isacord Polyester",
    name: "California Blue",
    red: 0,
    green: 163,
    blue: 209,
  ),
  ThreadColor(
    code: "4111",
    catalog: "Isacord Polyester",
    name: "Turquoise",
    red: 0,
    green: 235,
    blue: 255,
  ),
  ThreadColor(
    code: "4113",
    catalog: "Isacord Polyester",
    name: "Alexis Blue",
    red: 120,
    green: 190,
    blue: 204,
  ),
  ThreadColor(
    code: "4116",
    catalog: "Isacord Polyester",
    name: "Dark Teal",
    red: 0,
    green: 109,
    blue: 117,
  ),
  ThreadColor(
    code: "4133",
    catalog: "Isacord Polyester",
    name: "Deep Ocean",
    red: 51,
    green: 102,
    blue: 115,
  ),
  ThreadColor(
    code: "4174",
    catalog: "Isacord Polyester",
    name: "Charcoal",
    red: 85,
    green: 85,
    blue: 85,
  ),
  ThreadColor(
    code: "4220",
    catalog: "Isacord Polyester",
    name: "Island Green",
    red: 0,
    green: 204,
    blue: 204,
  ),
  ThreadColor(
    code: "4230",
    catalog: "Isacord Polyester",
    name: "Aqua",
    red: 175,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "4240",
    catalog: "Isacord Polyester",
    name: "Spearmint",
    red: 204,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "4250",
    catalog: "Isacord Polyester",
    name: "Snomoon",
    red: 220,
    green: 255,
    blue: 250,
  ),
  ThreadColor(
    code: "4410",
    catalog: "Isacord Polyester",
    name: "Aqua Velva",
    red: 0,
    green: 160,
    blue: 186,
  ),
  ThreadColor(
    code: "4421",
    catalog: "Isacord Polyester",
    name: "Light Mallard",
    red: 51,
    green: 180,
    blue: 190,
  ),
  ThreadColor(
    code: "4423",
    catalog: "Isacord Polyester",
    name: "Marine Aqua",
    red: 0,
    green: 155,
    blue: 170,
  ),
  ThreadColor(
    code: "4430",
    catalog: "Isacord Polyester",
    name: "Island Waters",
    red: 153,
    green: 240,
    blue: 220,
  ),
  ThreadColor(
    code: "4515",
    catalog: "Isacord Polyester",
    name: "Spruce",
    red: 51,
    green: 102,
    blue: 102,
  ),
  ThreadColor(
    code: "4531",
    catalog: "Isacord Polyester",
    name: "Caribbean",
    red: 51,
    green: 153,
    blue: 153,
  ),
  ThreadColor(
    code: "4610",
    catalog: "Isacord Polyester",
    name: "Deep Aqua",
    red: 47,
    green: 185,
    blue: 165,
  ),
  ThreadColor(
    code: "4620",
    catalog: "Isacord Polyester",
    name: "Jade",
    red: 51,
    green: 204,
    blue: 180,
  ),
  ThreadColor(
    code: "4625",
    catalog: "Isacord Polyester",
    name: "Seagreen",
    red: 0,
    green: 89,
    blue: 81,
  ),
  ThreadColor(
    code: "4643",
    catalog: "Isacord Polyester",
    name: "Amazon",
    red: 75,
    green: 120,
    blue: 125,
  ),
  ThreadColor(
    code: "4644",
    catalog: "Isacord Polyester",
    name: "Mallard",
    red: 102,
    green: 130,
    blue: 115,
  ),
  ThreadColor(
    code: "5005",
    catalog: "Isacord Polyester",
    name: "Rain Forest",
    red: 0,
    green: 96,
    blue: 86,
  ),
  ThreadColor(
    code: "5010",
    catalog: "Isacord Polyester",
    name: "Scotty Green",
    red: 0,
    green: 153,
    blue: 135,
  ),
  ThreadColor(
    code: "5050",
    catalog: "Isacord Polyester",
    name: "Luster",
    red: 220,
    green: 255,
    blue: 230,
  ),
  ThreadColor(
    code: "5100",
    catalog: "Isacord Polyester",
    name: "Green",
    red: 0,
    green: 165,
    blue: 120,
  ),
  ThreadColor(
    code: "5101",
    catalog: "Isacord Polyester",
    name: "Dark Jade",
    red: 51,
    green: 175,
    blue: 153,
  ),
  ThreadColor(
    code: "5115",
    catalog: "Isacord Polyester",
    name: "Baccarat Green",
    red: 51,
    green: 204,
    blue: 165,
  ),
  ThreadColor(
    code: "5210",
    catalog: "Isacord Polyester",
    name: "Trellis Green",
    red: 51,
    green: 204,
    blue: 153,
  ),
  ThreadColor(
    code: "5220",
    catalog: "Isacord Polyester",
    name: "Silver Sage",
    red: 160,
    green: 204,
    blue: 180,
  ),
  ThreadColor(
    code: "5230",
    catalog: "Isacord Polyester",
    name: "Bottle Green",
    red: 153,
    green: 240,
    blue: 204,
  ),
  ThreadColor(
    code: "5233",
    catalog: "Isacord Polyester",
    name: "Field Green",
    red: 38,
    green: 102,
    blue: 89,
  ),
  ThreadColor(
    code: "5324",
    catalog: "Isacord Polyester",
    name: "Bright Green",
    red: 2,
    green: 73,
    blue: 48,
  ),
  ThreadColor(
    code: "5326",
    catalog: "Isacord Polyester",
    name: "Evergreen",
    red: 0,
    green: 115,
    blue: 80,
  ),
  ThreadColor(
    code: "5335",
    catalog: "Isacord Polyester",
    name: "Swamp",
    red: 0,
    green: 73,
    blue: 63,
  ),
  ThreadColor(
    code: "5374",
    catalog: "Isacord Polyester",
    name: "Forest Green",
    red: 0,
    green: 60,
    blue: 20,
  ),
  ThreadColor(
    code: "5411",
    catalog: "Isacord Polyester",
    name: "Shamrock",
    red: 0,
    green: 135,
    blue: 81,
  ),
  ThreadColor(
    code: "5415",
    catalog: "Isacord Polyester",
    name: "Irish Green",
    red: 0,
    green: 122,
    blue: 61,
  ),
  ThreadColor(
    code: "5422",
    catalog: "Isacord Polyester",
    name: "Swiss Ivy",
    red: 60,
    green: 175,
    blue: 120,
  ),
  ThreadColor(
    code: "5500",
    catalog: "Isacord Polyester",
    name: "Limedrop",
    red: 28,
    green: 206,
    blue: 40,
  ),
  ThreadColor(
    code: "5510",
    catalog: "Isacord Polyester",
    name: "Emerald",
    red: 51,
    green: 158,
    blue: 53,
  ),
  ThreadColor(
    code: "5513",
    catalog: "Isacord Polyester",
    name: "Ming",
    red: 0,
    green: 158,
    blue: 15,
  ),
  ThreadColor(
    code: "5531",
    catalog: "Isacord Polyester",
    name: "Pear",
    red: 153,
    green: 204,
    blue: 102,
  ),
  ThreadColor(
    code: "5552",
    catalog: "Isacord Polyester",
    name: "Palm Leaf",
    red: 158,
    green: 170,
    blue: 153,
  ),
  ThreadColor(
    code: "5555",
    catalog: "Isacord Polyester",
    name: "Deep Green",
    red: 35,
    green: 79,
    blue: 51,
  ),
  ThreadColor(
    code: "5610",
    catalog: "Isacord Polyester",
    name: "Bright Mint",
    red: 180,
    green: 240,
    blue: 130,
  ),
  ThreadColor(
    code: "5613",
    catalog: "Isacord Polyester",
    name: "Light Kelly",
    red: 0,
    green: 183,
    blue: 96,
  ),
  ThreadColor(
    code: "5633",
    catalog: "Isacord Polyester",
    name: "Lime",
    red: 102,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "5643",
    catalog: "Isacord Polyester",
    name: "Green Dust",
    red: 33,
    green: 91,
    blue: 51,
  ),
  ThreadColor(
    code: "5650",
    catalog: "Isacord Polyester",
    name: "Spring Frost",
    red: 225,
    green: 255,
    blue: 204,
  ),
  ThreadColor(
    code: "5664",
    catalog: "Isacord Polyester",
    name: "Willow",
    red: 119,
    green: 145,
    blue: 130,
  ),
  ThreadColor(
    code: "5822",
    catalog: "Isacord Polyester",
    name: "Kiwi",
    red: 175,
    green: 204,
    blue: 130,
  ),
  ThreadColor(
    code: "5833",
    catalog: "Isacord Polyester",
    name: "Limabean",
    red: 153,
    green: 190,
    blue: 51,
  ),
  ThreadColor(
    code: "5866",
    catalog: "Isacord Polyester",
    name: "Herb Green",
    red: 90,
    green: 60,
    blue: 0,
  ),
  ThreadColor(
    code: "5912",
    catalog: "Isacord Polyester",
    name: "Erin Green",
    red: 158,
    green: 196,
    blue: 0,
  ),
  ThreadColor(
    code: "5933",
    catalog: "Isacord Polyester",
    name: "Grasshopper",
    red: 140,
    green: 160,
    blue: 90,
  ),
  ThreadColor(
    code: "5934",
    catalog: "Isacord Polyester",
    name: "Moss Green",
    red: 153,
    green: 153,
    blue: 51,
  ),
  ThreadColor(
    code: "5940",
    catalog: "Isacord Polyester",
    name: "Sour Apple neon",
    red: 217,
    green: 255,
    blue: 66,
  ),
  ThreadColor(
    code: "5944",
    catalog: "Isacord Polyester",
    name: "Backyard Green",
    red: 80,
    green: 110,
    blue: 51,
  ),
  ThreadColor(
    code: "6010",
    catalog: "Isacord Polyester",
    name: "Mountain Dew neon",
    red: 255,
    green: 255,
    blue: 63,
  ),
  ThreadColor(
    code: "6051",
    catalog: "Isacord Polyester",
    name: "Jalapeno",
    red: 225,
    green: 255,
    blue: 153,
  ),
  ThreadColor(
    code: "6133",
    catalog: "Isacord Polyester",
    name: "Caper",
    red: 153,
    green: 153,
    blue: 45,
  ),
  ThreadColor(
    code: "6156",
    catalog: "Isacord Polyester",
    name: "Olive",
    red: 115,
    green: 102,
    blue: 40,
  ),
];
