// This file is generated automatically. DO NOT EDIT.
// Catalog of Madeira colors
import 'package:thread_digit/colors/thread_color.dart';

const List<ThreadColor> madeiraRayonColors = [
  ThreadColor(
    code: "1000",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 15,
    green: 16,
    blue: 14,
  ),
  ThreadColor(
    code: "1001",
    catalog: "Madeira Rayon",
    name: "Bright White",
    red: 255,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "1003",
    catalog: "Madeira Rayon",
    name: "Amethyst Light",
    red: 255,
    green: 255,
    blue: 252,
  ),
  ThreadColor(
    code: "1004",
    catalog: "Madeira Rayon",
    name: "Blue Blush",
    red: 252,
    green: 255,
    blue: 255,
  ),
  ThreadColor(
    code: "1005",
    catalog: "Madeira Rayon",
    name: "Bright White",
    red: 221,
    green: 231,
    blue: 233,
  ),
  ThreadColor(
    code: "1006",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 15,
    green: 16,
    blue: 17,
  ),
  ThreadColor(
    code: "1007",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 28,
    green: 30,
    blue: 26,
  ),
  ThreadColor(
    code: "1008",
    catalog: "Madeira Rayon",
    name: "Ruby Black",
    red: 33,
    green: 28,
    blue: 29,
  ),
  ThreadColor(
    code: "1009",
    catalog: "Madeira Rayon",
    name: "Sapphire Black",
    red: 35,
    green: 34,
    blue: 43,
  ),
  ThreadColor(
    code: "1010",
    catalog: "Madeira Rayon",
    name: "Vapor",
    red: 221,
    green: 219,
    blue: 209,
  ),
  ThreadColor(
    code: "1011",
    catalog: "Madeira Rayon",
    name: "Traditional Gray",
    red: 173,
    green: 175,
    blue: 170,
  ),
  ThreadColor(
    code: "1012",
    catalog: "Madeira Rayon",
    name: "Pale Silver",
    red: 198,
    green: 209,
    blue: 214,
  ),
  ThreadColor(
    code: "1013",
    catalog: "Madeira Rayon",
    name: "PLST Peach",
    red: 255,
    green: 224,
    blue: 199,
  ),
  ThreadColor(
    code: "1014",
    catalog: "Madeira Rayon",
    name: "Orchid Pink",
    red: 249,
    green: 191,
    blue: 193,
  ),
  ThreadColor(
    code: "1015",
    catalog: "Madeira Rayon",
    name: "Desert Bloom",
    red: 247,
    green: 191,
    blue: 191,
  ),
  ThreadColor(
    code: "1016",
    catalog: "Madeira Rayon",
    name: "Emily Pink",
    red: 249,
    green: 175,
    blue: 173,
  ),
  ThreadColor(
    code: "1017",
    catalog: "Madeira Rayon",
    name: "Peach",
    red: 249,
    green: 198,
    blue: 170,
  ),
  ThreadColor(
    code: "1018",
    catalog: "Madeira Rayon",
    name: "Flesh Pink",
    red: 249,
    green: 186,
    blue: 170,
  ),
  ThreadColor(
    code: "1019",
    catalog: "Madeira Rayon",
    name: "Illusion",
    red: 249,
    green: 186,
    blue: 167,
  ),
  ThreadColor(
    code: "1020",
    catalog: "Madeira Rayon",
    name: "Flamingo",
    red: 249,
    green: 165,
    blue: 140,
  ),
  ThreadColor(
    code: "1021",
    catalog: "Madeira Rayon",
    name: "Terra Cotta",
    red: 165,
    green: 63,
    blue: 15,
  ),
  ThreadColor(
    code: "1022",
    catalog: "Madeira Rayon",
    name: "Medium Yellow",
    red: 244,
    green: 237,
    blue: 124,
  ),
  ThreadColor(
    code: "1023",
    catalog: "Madeira Rayon",
    name: "Yellow Cream",
    red: 244,
    green: 237,
    blue: 71,
  ),
  ThreadColor(
    code: "1024",
    catalog: "Madeira Rayon",
    name: "Neon Orange",
    red: 255,
    green: 198,
    blue: 30,
  ),
  ThreadColor(
    code: "1025",
    catalog: "Madeira Rayon",
    name: "Pollen Gold",
    red: 224,
    green: 170,
    blue: 15,
  ),
  ThreadColor(
    code: "1026",
    catalog: "Madeira Rayon",
    name: "Glow",
    red: 255,
    green: 216,
    blue: 127,
  ),
  ThreadColor(
    code: "1027",
    catalog: "Madeira Rayon",
    name: "Cadet Blue",
    red: 196,
    green: 216,
    blue: 226,
  ),
  ThreadColor(
    code: "1028",
    catalog: "Madeira Rayon",
    name: "Caribbean Blue",
    red: 117,
    green: 170,
    blue: 219,
  ),
  ThreadColor(
    code: "1029",
    catalog: "Madeira Rayon",
    name: "Dolphin Blue",
    red: 58,
    green: 117,
    blue: 196,
  ),
  ThreadColor(
    code: "1030",
    catalog: "Madeira Rayon",
    name: "Lake Blue",
    red: 175,
    green: 188,
    blue: 219,
  ),
  ThreadColor(
    code: "1031",
    catalog: "Madeira Rayon",
    name: "Carnatio",
    red: 234,
    green: 170,
    blue: 196,
  ),
  ThreadColor(
    code: "1032",
    catalog: "Madeira Rayon",
    name: "Iris",
    red: 170,
    green: 114,
    blue: 191,
  ),
  ThreadColor(
    code: "1033",
    catalog: "Madeira Rayon",
    name: "Mulberry",
    red: 102,
    green: 17,
    blue: 109,
  ),
  ThreadColor(
    code: "1034",
    catalog: "Madeira Rayon",
    name: "Burgundy",
    red: 165,
    green: 5,
    blue: 68,
  ),
  ThreadColor(
    code: "1035",
    catalog: "Madeira Rayon",
    name: "Warm Wine",
    red: 102,
    green: 30,
    blue: 43,
  ),
  ThreadColor(
    code: "1036",
    catalog: "Madeira Rayon",
    name: "Dark Sepia",
    red: 91,
    green: 38,
    blue: 38,
  ),
  ThreadColor(
    code: "1037",
    catalog: "Madeira Rayon",
    name: "Red Orange",
    red: 214,
    green: 40,
    blue: 40,
  ),
  ThreadColor(
    code: "1038",
    catalog: "Madeira Rayon",
    name: "Red Bittersweet",
    red: 155,
    green: 48,
    blue: 28,
  ),
  ThreadColor(
    code: "1039",
    catalog: "Madeira Rayon",
    name: "Red Berry",
    red: 175,
    green: 38,
    blue: 38,
  ),
  ThreadColor(
    code: "1040",
    catalog: "Madeira Rayon",
    name: "Silvery Gray",
    red: 172,
    green: 173,
    blue: 163,
  ),
  ThreadColor(
    code: "1041",
    catalog: "Madeira Rayon",
    name: "Metal",
    red: 102,
    green: 109,
    blue: 112,
  ),
  ThreadColor(
    code: "1042",
    catalog: "Madeira Rayon",
    name: "Harbor",
    red: 51,
    green: 86,
    blue: 135,
  ),
  ThreadColor(
    code: "1043",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 6,
    green: 14,
    blue: 45,
  ),
  ThreadColor(
    code: "1044",
    catalog: "Madeira Rayon",
    name: "Navy",
    red: 20,
    green: 33,
    blue: 61,
  ),
  ThreadColor(
    code: "1045",
    catalog: "Madeira Rayon",
    name: "Seafrost",
    red: 135,
    green: 221,
    blue: 209,
  ),
  ThreadColor(
    code: "1046",
    catalog: "Madeira Rayon",
    name: "Pale Green",
    red: 122,
    green: 209,
    blue: 181,
  ),
  ThreadColor(
    code: "1047",
    catalog: "Madeira Rayon",
    name: "Mint",
    red: 181,
    green: 226,
    blue: 191,
  ),
  ThreadColor(
    code: "1048",
    catalog: "Madeira Rayon",
    name: "Green Dust",
    red: 127,
    green: 186,
    blue: 0,
  ),
  ThreadColor(
    code: "1049",
    catalog: "Madeira Rayon",
    name: "Spruce",
    red: 170,
    green: 221,
    blue: 109,
  ),
  ThreadColor(
    code: "1050",
    catalog: "Madeira Rayon",
    name: "Emerald",
    red: 51,
    green: 158,
    blue: 53,
  ),
  ThreadColor(
    code: "1051",
    catalog: "Madeira Rayon",
    name: "Kelly",
    red: 0,
    green: 122,
    blue: 61,
  ),
  ThreadColor(
    code: "1052",
    catalog: "Madeira Rayon",
    name: "Imperial Aqua",
    red: 0,
    green: 109,
    blue: 102,
  ),
  ThreadColor(
    code: "1053",
    catalog: "Madeira Rayon",
    name: "Peach",
    red: 249,
    green: 198,
    blue: 167,
  ),
  ThreadColor(
    code: "1054",
    catalog: "Madeira Rayon",
    name: "Tawny Birch",
    red: 175,
    green: 137,
    blue: 112,
  ),
  ThreadColor(
    code: "1055",
    catalog: "Madeira Rayon",
    name: "Cream",
    red: 244,
    green: 219,
    blue: 170,
  ),
  ThreadColor(
    code: "1056",
    catalog: "Madeira Rayon",
    name: "Wicker",
    red: 170,
    green: 117,
    blue: 63,
  ),
  ThreadColor(
    code: "1057",
    catalog: "Madeira Rayon",
    name: "Fawn",
    red: 178,
    green: 130,
    blue: 96,
  ),
  ThreadColor(
    code: "1058",
    catalog: "Madeira Rayon",
    name: "Mushroom",
    red: 96,
    green: 51,
    blue: 17,
  ),
  ThreadColor(
    code: "1059",
    catalog: "Madeira Rayon",
    name: "Egyptian Brown",
    red: 73,
    green: 53,
    blue: 51,
  ),
  ThreadColor(
    code: "1060",
    catalog: "Madeira Rayon",
    name: "String",
    red: 183,
    green: 187,
    blue: 170,
  ),
  ThreadColor(
    code: "1061",
    catalog: "Madeira Rayon",
    name: "Wheat",
    red: 249,
    green: 224,
    blue: 140,
  ),
  ThreadColor(
    code: "1062",
    catalog: "Madeira Rayon",
    name: "Pale Grey",
    red: 142,
    green: 140,
    blue: 122,
  ),
  ThreadColor(
    code: "1063",
    catalog: "Madeira Rayon",
    name: "Medium Green/Yellow",
    red: 119,
    green: 114,
    blue: 99,
  ),
  ThreadColor(
    code: "1064",
    catalog: "Madeira Rayon",
    name: "Buttercup",
    red: 236,
    green: 205,
    blue: 14,
  ),
  ThreadColor(
    code: "1065",
    catalog: "Madeira Rayon",
    name: "Mango",
    red: 252,
    green: 163,
    blue: 17,
  ),
  ThreadColor(
    code: "1066",
    catalog: "Madeira Rayon",
    name: "Pale Yellow",
    red: 244,
    green: 226,
    blue: 135,
  ),
  ThreadColor(
    code: "1067",
    catalog: "Madeira Rayon",
    name: "Sunshine",
    red: 249,
    green: 226,
    blue: 127,
  ),
  ThreadColor(
    code: "1068",
    catalog: "Madeira Rayon",
    name: "Canary",
    red: 249,
    green: 214,
    blue: 22,
  ),
  ThreadColor(
    code: "1069",
    catalog: "Madeira Rayon",
    name: "Papaya",
    red: 252,
    green: 209,
    blue: 22,
  ),
  ThreadColor(
    code: "1070",
    catalog: "Madeira Rayon",
    name: "Yellow Gold",
    red: 242,
    green: 206,
    blue: 104,
  ),
  ThreadColor(
    code: "1071",
    catalog: "Madeira Rayon",
    name: "Natural White",
    red: 216,
    green: 213,
    blue: 187,
  ),
  ThreadColor(
    code: "1072",
    catalog: "Madeira Rayon",
    name: "Beige",
    red: 212,
    green: 199,
    blue: 166,
  ),
  ThreadColor(
    code: "1073",
    catalog: "Madeira Rayon",
    name: "Natural White",
    red: 222,
    green: 242,
    blue: 224,
  ),
  ThreadColor(
    code: "1074",
    catalog: "Madeira Rayon",
    name: "Ice Blue",
    red: 181,
    green: 209,
    blue: 232,
  ),
  ThreadColor(
    code: "1075",
    catalog: "Madeira Rayon",
    name: "Baby Blue",
    red: 153,
    green: 186,
    blue: 221,
  ),
  ThreadColor(
    code: "1076",
    catalog: "Madeira Rayon",
    name: "Blue",
    red: 45,
    green: 51,
    blue: 142,
  ),
  ThreadColor(
    code: "1077",
    catalog: "Madeira Rayon",
    name: "Orange/Red",
    red: 234,
    green: 92,
    blue: 5,
  ),
  ThreadColor(
    code: "1078",
    catalog: "Madeira Rayon",
    name: "Paprika",
    red: 249,
    green: 86,
    blue: 2,
  ),
  ThreadColor(
    code: "1079",
    catalog: "Madeira Rayon",
    name: "Kelly",
    red: 0,
    green: 122,
    blue: 64,
  ),
  ThreadColor(
    code: "1080",
    catalog: "Madeira Rayon",
    name: "Medium Pink",
    red: 232,
    green: 127,
    blue: 201,
  ),
  ThreadColor(
    code: "1081",
    catalog: "Madeira Rayon",
    name: "Wildfire",
    red: 193,
    green: 5,
    blue: 56,
  ),
  ThreadColor(
    code: "1082",
    catalog: "Madeira Rayon",
    name: "Ivory",
    red: 203,
    green: 201,
    blue: 163,
  ),
  ThreadColor(
    code: "1083",
    catalog: "Madeira Rayon",
    name: "Moonbeam",
    red: 249,
    green: 221,
    blue: 22,
  ),
  ThreadColor(
    code: "1084",
    catalog: "Madeira Rayon",
    name: "Sea Mist",
    red: 221,
    green: 204,
    blue: 165,
  ),
  ThreadColor(
    code: "1085",
    catalog: "Madeira Rayon",
    name: "White Sand",
    red: 190,
    green: 191,
    blue: 181,
  ),
  ThreadColor(
    code: "1086",
    catalog: "Madeira Rayon",
    name: "Palest Ivory",
    red: 228,
    green: 236,
    blue: 231,
  ),
  ThreadColor(
    code: "1087",
    catalog: "Madeira Rayon",
    name: "Pearl Gray",
    red: 197,
    green: 185,
    blue: 170,
  ),
  ThreadColor(
    code: "1088",
    catalog: "Madeira Rayon",
    name: "Aquamarine",
    red: 86,
    green: 201,
    blue: 193,
  ),
  ThreadColor(
    code: "1089",
    catalog: "Madeira Rayon",
    name: "Basic Turquoise",
    red: 107,
    green: 201,
    blue: 219,
  ),
  ThreadColor(
    code: "1090",
    catalog: "Madeira Rayon",
    name: "M. D. Green",
    red: 0,
    green: 178,
    blue: 170,
  ),
  ThreadColor(
    code: "1091",
    catalog: "Madeira Rayon",
    name: "Dark Aqua Green",
    red: 0,
    green: 130,
    blue: 155,
  ),
  ThreadColor(
    code: "1092",
    catalog: "Madeira Rayon",
    name: "Cadet Blue",
    red: 196,
    green: 216,
    blue: 223,
  ),
  ThreadColor(
    code: "1093",
    catalog: "Madeira Rayon",
    name: "Indian Ocean Blue",
    red: 45,
    green: 198,
    blue: 214,
  ),
  ThreadColor(
    code: "1094",
    catalog: "Madeira Rayon",
    name: "Periwinkle",
    red: 40,
    green: 196,
    blue: 216,
  ),
  ThreadColor(
    code: "1095",
    catalog: "Madeira Rayon",
    name: "Aquamarine",
    red: 0,
    green: 173,
    blue: 198,
  ),
  ThreadColor(
    code: "1096",
    catalog: "Madeira Rayon",
    name: "Pretty Blue",
    red: 0,
    green: 122,
    blue: 165,
  ),
  ThreadColor(
    code: "1097",
    catalog: "Madeira Rayon",
    name: "Bleached Aqua",
    red: 186,
    green: 234,
    blue: 214,
  ),
  ThreadColor(
    code: "1098",
    catalog: "Madeira Rayon",
    name: "Blue Surf",
    red: 71,
    green: 142,
    blue: 121,
  ),
  ThreadColor(
    code: "1099",
    catalog: "Madeira Rayon",
    name: "Pastel Green",
    red: 201,
    green: 214,
    blue: 163,
  ),
  ThreadColor(
    code: "1100",
    catalog: "Madeira Rayon",
    name: "Pastel Green",
    red: 201,
    green: 214,
    blue: 160,
  ),
  ThreadColor(
    code: "1101",
    catalog: "Madeira Rayon",
    name: "Emerald",
    red: 51,
    green: 158,
    blue: 56,
  ),
  ThreadColor(
    code: "1102",
    catalog: "Madeira Rayon",
    name: "Green Haze",
    red: 187,
    green: 199,
    blue: 137,
  ),
  ThreadColor(
    code: "1103",
    catalog: "Madeira Rayon",
    name: "Holly",
    red: 33,
    green: 91,
    blue: 51,
  ),
  ThreadColor(
    code: "1104",
    catalog: "Madeira Rayon",
    name: "Lime Cream",
    red: 216,
    green: 221,
    blue: 181,
  ),
  ThreadColor(
    code: "1105",
    catalog: "Madeira Rayon",
    name: "Silver Fern",
    red: 178,
    green: 170,
    blue: 112,
  ),
  ThreadColor(
    code: "1106",
    catalog: "Madeira Rayon",
    name: "Crescent Moon",
    red: 135,
    green: 137,
    blue: 5,
  ),
  ThreadColor(
    code: "1107",
    catalog: "Madeira Rayon",
    name: "Shell Pink",
    red: 249,
    green: 130,
    blue: 127,
  ),
  ThreadColor(
    code: "1108",
    catalog: "Madeira Rayon",
    name: "Aurora Pink",
    red: 255,
    green: 163,
    blue: 178,
  ),
  ThreadColor(
    code: "1109",
    catalog: "Madeira Rayon",
    name: "Ruby Glint",
    red: 226,
    green: 40,
    blue: 130,
  ),
  ThreadColor(
    code: "1110",
    catalog: "Madeira Rayon",
    name: "Ruby Glint",
    red: 226,
    green: 40,
    blue: 127,
  ),
  ThreadColor(
    code: "1111",
    catalog: "Madeira Rayon",
    name: "Light Pink",
    red: 234,
    green: 204,
    blue: 206,
  ),
  ThreadColor(
    code: "1112",
    catalog: "Madeira Rayon",
    name: "Purple Accent",
    red: 79,
    green: 33,
    blue: 112,
  ),
  ThreadColor(
    code: "1113",
    catalog: "Madeira Rayon",
    name: "Pink Mist",
    red: 242,
    green: 198,
    blue: 196,
  ),
  ThreadColor(
    code: "1114",
    catalog: "Madeira Rayon",
    name: "Bisque",
    red: 242,
    green: 196,
    blue: 175,
  ),
  ThreadColor(
    code: "1115",
    catalog: "Madeira Rayon",
    name: "Crystal Pink",
    red: 247,
    green: 209,
    blue: 204,
  ),
  ThreadColor(
    code: "1116",
    catalog: "Madeira Rayon",
    name: "Orchid Pink",
    red: 249,
    green: 191,
    blue: 190,
  ),
  ThreadColor(
    code: "1117",
    catalog: "Madeira Rayon",
    name: "Begonia",
    red: 244,
    green: 84,
    blue: 124,
  ),
  ThreadColor(
    code: "1118",
    catalog: "Madeira Rayon",
    name: "Banner Gray",
    red: 145,
    green: 150,
    blue: 147,
  ),
  ThreadColor(
    code: "1119",
    catalog: "Madeira Rayon",
    name: "K. A. Bronze",
    red: 178,
    green: 107,
    blue: 112,
  ),
  ThreadColor(
    code: "1120",
    catalog: "Madeira Rayon",
    name: "Crystal Pink",
    red: 244,
    green: 201,
    blue: 201,
  ),
  ThreadColor(
    code: "1121",
    catalog: "Madeira Rayon",
    name: "Pink",
    red: 252,
    green: 191,
    blue: 201,
  ),
  ThreadColor(
    code: "1122",
    catalog: "Madeira Rayon",
    name: "Purple Shadow",
    red: 91,
    green: 2,
    blue: 122,
  ),
  ThreadColor(
    code: "1123",
    catalog: "Madeira Rayon",
    name: "Etherial Green",
    red: 247,
    green: 232,
    blue: 170,
  ),
  ThreadColor(
    code: "1124",
    catalog: "Madeira Rayon",
    name: "Star Gold",
    red: 249,
    green: 224,
    blue: 76,
  ),
  ThreadColor(
    code: "1125",
    catalog: "Madeira Rayon",
    name: "Manila",
    red: 252,
    green: 209,
    blue: 25,
  ),
  ThreadColor(
    code: "1126",
    catalog: "Madeira Rayon",
    name: "Light Bronze",
    red: 193,
    green: 142,
    blue: 96,
  ),
  ThreadColor(
    code: "1127",
    catalog: "Madeira Rayon",
    name: "Alesan",
    red: 244,
    green: 209,
    blue: 175,
  ),
  ThreadColor(
    code: "1128",
    catalog: "Madeira Rayon",
    name: "Taupe",
    red: 209,
    green: 191,
    blue: 145,
  ),
  ThreadColor(
    code: "1129",
    catalog: "Madeira Rayon",
    name: "Egyptian Brown",
    red: 73,
    green: 53,
    blue: 54,
  ),
  ThreadColor(
    code: "1130",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 63,
    green: 48,
    blue: 43,
  ),
  ThreadColor(
    code: "1131",
    catalog: "Madeira Rayon",
    name: "Dark Grey",
    red: 73,
    green: 77,
    blue: 70,
  ),
  ThreadColor(
    code: "1132",
    catalog: "Madeira Rayon",
    name: "Pale Blue",
    red: 147,
    green: 198,
    blue: 224,
  ),
  ThreadColor(
    code: "1133",
    catalog: "Madeira Rayon",
    name: "Dolphin Blue",
    red: 58,
    green: 117,
    blue: 193,
  ),
  ThreadColor(
    code: "1134",
    catalog: "Madeira Rayon",
    name: "Fire Blue",
    red: 0,
    green: 56,
    blue: 168,
  ),
  ThreadColor(
    code: "1135",
    catalog: "Madeira Rayon",
    name: "Lemon",
    red: 249,
    green: 226,
    blue: 77,
  ),
  ThreadColor(
    code: "1136",
    catalog: "Madeira Rayon",
    name: "String",
    red: 138,
    green: 129,
    blue: 107,
  ),
  ThreadColor(
    code: "1137",
    catalog: "Madeira Rayon",
    name: "Honeydew",
    red: 252,
    green: 181,
    blue: 20,
  ),
  ThreadColor(
    code: "1138",
    catalog: "Madeira Rayon",
    name: "Seashell",
    red: 214,
    green: 204,
    blue: 175,
  ),
  ThreadColor(
    code: "1140",
    catalog: "Madeira Rayon",
    name: "Tamarack",
    red: 147,
    green: 153,
    blue: 5,
  ),
  ThreadColor(
    code: "1141",
    catalog: "Madeira Rayon",
    name: "Light Pink",
    red: 188,
    green: 135,
    blue: 135,
  ),
  ThreadColor(
    code: "1142",
    catalog: "Madeira Rayon",
    name: "Whisper Pink",
    red: 224,
    green: 204,
    blue: 186,
  ),
  ThreadColor(
    code: "1143",
    catalog: "Madeira Rayon",
    name: "Medium Blue",
    red: 91,
    green: 119,
    blue: 204,
  ),
  ThreadColor(
    code: "1144",
    catalog: "Madeira Rayon",
    name: "Prairie Beige",
    red: 117,
    green: 84,
    blue: 38,
  ),
  ThreadColor(
    code: "1145",
    catalog: "Madeira Rayon",
    name: "Brown",
    red: 89,
    green: 61,
    blue: 43,
  ),
  ThreadColor(
    code: "1146",
    catalog: "Madeira Rayon",
    name: "Tuxedo Red",
    red: 241,
    green: 51,
    blue: 25,
  ),
  ThreadColor(
    code: "1147",
    catalog: "Madeira Rayon",
    name: "Foxy Red",
    red: 206,
    green: 17,
    blue: 38,
  ),
  ThreadColor(
    code: "1148",
    catalog: "Madeira Rayon",
    name: "Medium Pink",
    red: 239,
    green: 153,
    blue: 163,
  ),
  ThreadColor(
    code: "1149",
    catalog: "Madeira Rayon",
    name: "Ecru",
    red: 237,
    green: 211,
    blue: 188,
  ),
  ThreadColor(
    code: "1150",
    catalog: "Madeira Rayon",
    name: "Pebblestone",
    red: 226,
    green: 229,
    blue: 132,
  ),
  ThreadColor(
    code: "1151",
    catalog: "Madeira Rayon",
    name: "Cadmium Orange",
    red: 229,
    green: 239,
    blue: 240,
  ),
  ThreadColor(
    code: "1152",
    catalog: "Madeira Rayon",
    name: "Coral",
    red: 252,
    green: 158,
    blue: 112,
  ),
  ThreadColor(
    code: "1153",
    catalog: "Madeira Rayon",
    name: "Illusion Blue",
    red: 209,
    green: 216,
    blue: 216,
  ),
  ThreadColor(
    code: "1154",
    catalog: "Madeira Rayon",
    name: "Cerise",
    red: 229,
    green: 5,
    blue: 58,
  ),
  ThreadColor(
    code: "1155",
    catalog: "Madeira Rayon",
    name: "Chamois",
    red: 252,
    green: 173,
    blue: 86,
  ),
  ThreadColor(
    code: "1156",
    catalog: "Madeira Rayon",
    name: "Medium Green/Yellow",
    red: 140,
    green: 145,
    blue: 79,
  ),
  ThreadColor(
    code: "1157",
    catalog: "Madeira Rayon",
    name: "Desert Cactus",
    red: 130,
    green: 117,
    blue: 15,
  ),
  ThreadColor(
    code: "1158",
    catalog: "Madeira Rayon",
    name: "Mushroom",
    red: 96,
    green: 51,
    blue: 20,
  ),
  ThreadColor(
    code: "1159",
    catalog: "Madeira Rayon",
    name: "Black Eyed Susie",
    red: 198,
    green: 160,
    blue: 12,
  ),
  ThreadColor(
    code: "1160",
    catalog: "Madeira Rayon",
    name: "Wonder Blue",
    red: 94,
    green: 153,
    blue: 170,
  ),
  ThreadColor(
    code: "1161",
    catalog: "Madeira Rayon",
    name: "Deep Windsor",
    red: 0,
    green: 63,
    blue: 84,
  ),
  ThreadColor(
    code: "1162",
    catalog: "Madeira Rayon",
    name: "Deep Windsor",
    red: 0,
    green: 63,
    blue: 87,
  ),
  ThreadColor(
    code: "1163",
    catalog: "Madeira Rayon",
    name: "Blue Gray",
    red: 139,
    green: 169,
    blue: 182,
  ),
  ThreadColor(
    code: "1164",
    catalog: "Madeira Rayon",
    name: "Gull",
    red: 82,
    green: 94,
    blue: 101,
  ),
  ThreadColor(
    code: "1166",
    catalog: "Madeira Rayon",
    name: "Royal",
    red: 30,
    green: 28,
    blue: 119,
  ),
  ThreadColor(
    code: "1167",
    catalog: "Madeira Rayon",
    name: "Maverick",
    red: 0,
    green: 43,
    blue: 127,
  ),
  ThreadColor(
    code: "1169",
    catalog: "Madeira Rayon",
    name: "Medium Green",
    red: 158,
    green: 196,
    blue: 0,
  ),
  ThreadColor(
    code: "1170",
    catalog: "Madeira Rayon",
    name: "Dark Palmetto Green",
    red: 86,
    green: 142,
    blue: 20,
  ),
  ThreadColor(
    code: "1171",
    catalog: "Madeira Rayon",
    name: "Star Gold",
    red: 252,
    green: 216,
    blue: 86,
  ),
  ThreadColor(
    code: "1172",
    catalog: "Madeira Rayon",
    name: "Buttercup",
    red: 255,
    green: 198,
    blue: 33,
  ),
  ThreadColor(
    code: "1173",
    catalog: "Madeira Rayon",
    name: "Almond",
    red: 204,
    green: 122,
    blue: 2,
  ),
  ThreadColor(
    code: "1174",
    catalog: "Madeira Rayon",
    name: "Burgundy",
    red: 124,
    green: 45,
    blue: 35,
  ),
  ThreadColor(
    code: "1175",
    catalog: "Madeira Rayon",
    name: "Medium Blue",
    red: 109,
    green: 135,
    blue: 168,
  ),
  ThreadColor(
    code: "1176",
    catalog: "Madeira Rayon",
    name: "Baltic Blue",
    red: 0,
    green: 142,
    blue: 214,
  ),
  ThreadColor(
    code: "1177",
    catalog: "Madeira Rayon",
    name: "Caribbean Blue",
    red: 0,
    green: 81,
    blue: 186,
  ),
  ThreadColor(
    code: "1178",
    catalog: "Madeira Rayon",
    name: "Orange",
    red: 249,
    green: 107,
    blue: 7,
  ),
  ThreadColor(
    code: "1179",
    catalog: "Madeira Rayon",
    name: "Dark Rust",
    red: 193,
    green: 56,
    blue: 40,
  ),
  ThreadColor(
    code: "1180",
    catalog: "Madeira Rayon",
    name: "Daffodil",
    red: 249,
    green: 232,
    blue: 20,
  ),
  ThreadColor(
    code: "1181",
    catalog: "Madeira Rayon",
    name: "Red Berry",
    red: 175,
    green: 30,
    blue: 45,
  ),
  ThreadColor(
    code: "1182",
    catalog: "Madeira Rayon",
    name: "Burgundy",
    red: 140,
    green: 38,
    blue: 51,
  ),
  ThreadColor(
    code: "1183",
    catalog: "Madeira Rayon",
    name: "Cranberry",
    red: 147,
    green: 0,
    blue: 66,
  ),
  ThreadColor(
    code: "1184",
    catalog: "Madeira Rayon",
    name: "Wildfire",
    red: 193,
    green: 5,
    blue: 59,
  ),
  ThreadColor(
    code: "1185",
    catalog: "Madeira Rayon",
    name: "Imperial Aqua",
    red: 0,
    green: 109,
    blue: 105,
  ),
  ThreadColor(
    code: "1186",
    catalog: "Madeira Rayon",
    name: "Dark Pink",
    red: 197,
    green: 26,
    blue: 77,
  ),
  ThreadColor(
    code: "1187",
    catalog: "Madeira Rayon",
    name: "Dark Pink",
    red: 235,
    green: 34,
    blue: 63,
  ),
  ThreadColor(
    code: "1188",
    catalog: "Madeira Rayon",
    name: "Dark Red",
    red: 135,
    green: 0,
    blue: 91,
  ),
  ThreadColor(
    code: "1189",
    catalog: "Madeira Rayon",
    name: "Holly",
    red: 33,
    green: 91,
    blue: 54,
  ),
  ThreadColor(
    code: "1190",
    catalog: "Madeira Rayon",
    name: "Medium Yellow/Green",
    red: 150,
    green: 140,
    blue: 40,
  ),
  ThreadColor(
    code: "1191",
    catalog: "Madeira Rayon",
    name: "Autumn Green",
    red: 163,
    green: 130,
    blue: 5,
  ),
  ThreadColor(
    code: "1192",
    catalog: "Madeira Rayon",
    name: "Bullion",
    red: 163,
    green: 127,
    blue: 20,
  ),
  ThreadColor(
    code: "1193",
    catalog: "Madeira Rayon",
    name: "Hemp",
    red: 175,
    green: 199,
    blue: 66,
  ),
  ThreadColor(
    code: "1194",
    catalog: "Madeira Rayon",
    name: "Desert Cactus",
    red: 137,
    green: 119,
    blue: 25,
  ),
  ThreadColor(
    code: "1195",
    catalog: "Madeira Rayon",
    name: "Pale Green",
    red: 188,
    green: 219,
    blue: 204,
  ),
  ThreadColor(
    code: "1196",
    catalog: "Madeira Rayon",
    name: "Black Eyed Susie",
    red: 198,
    green: 173,
    blue: 15,
  ),
  ThreadColor(
    code: "1198",
    catalog: "Madeira Rayon",
    name: "Cadet Blue",
    red: 191,
    green: 209,
    blue: 229,
  ),
  ThreadColor(
    code: "1199",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 26,
    green: 28,
    blue: 30,
  ),
  ThreadColor(
    code: "1212",
    catalog: "Madeira Rayon",
    name: "Pale Silver",
    red: 191,
    green: 198,
    blue: 209,
  ),
  ThreadColor(
    code: "1217",
    catalog: "Madeira Rayon",
    name: "Peach",
    red: 244,
    green: 196,
    blue: 160,
  ),
  ThreadColor(
    code: "1218",
    catalog: "Madeira Rayon",
    name: "Roebuck",
    red: 182,
    green: 138,
    blue: 113,
  ),
  ThreadColor(
    code: "1219",
    catalog: "Madeira Rayon",
    name: "Sprite",
    red: 170,
    green: 196,
    blue: 191,
  ),
  ThreadColor(
    code: "1220",
    catalog: "Madeira Rayon",
    name: "Pink Icing",
    red: 166,
    green: 11,
    blue: 2,
  ),
  ThreadColor(
    code: "1221",
    catalog: "Madeira Rayon",
    name: "Dark Rust",
    red: 193,
    green: 56,
    blue: 43,
  ),
  ThreadColor(
    code: "1222",
    catalog: "Madeira Rayon",
    name: "Lemon Ice",
    red: 242,
    green: 234,
    blue: 188,
  ),
  ThreadColor(
    code: "1223",
    catalog: "Madeira Rayon",
    name: "Canary",
    red: 227,
    green: 219,
    blue: 12,
  ),
  ThreadColor(
    code: "1224",
    catalog: "Madeira Rayon",
    name: "Star Gold",
    red: 249,
    green: 224,
    blue: 79,
  ),
  ThreadColor(
    code: "1225",
    catalog: "Madeira Rayon",
    name: "Pollen Gold",
    red: 224,
    green: 170,
    blue: 18,
  ),
  ThreadColor(
    code: "1226",
    catalog: "Madeira Rayon",
    name: "Buff Orange",
    red: 255,
    green: 183,
    blue: 119,
  ),
  ThreadColor(
    code: "1227",
    catalog: "Madeira Rayon",
    name: "Pale Blue",
    red: 140,
    green: 175,
    blue: 173,
  ),
  ThreadColor(
    code: "1228",
    catalog: "Madeira Rayon",
    name: "Vertiver Green",
    red: 130,
    green: 117,
    blue: 102,
  ),
  ThreadColor(
    code: "1229",
    catalog: "Madeira Rayon",
    name: "Dark Grey",
    red: 115,
    green: 110,
    blue: 88,
  ),
  ThreadColor(
    code: "1230",
    catalog: "Madeira Rayon",
    name: "Fungi",
    red: 108,
    green: 95,
    blue: 70,
  ),
  ThreadColor(
    code: "1232",
    catalog: "Madeira Rayon",
    name: "Violet",
    red: 237,
    green: 196,
    blue: 221,
  ),
  ThreadColor(
    code: "1233",
    catalog: "Madeira Rayon",
    name: "Blackberry",
    red: 71,
    green: 43,
    blue: 89,
  ),
  ThreadColor(
    code: "1234",
    catalog: "Madeira Rayon",
    name: "Dark Pink",
    red: 204,
    green: 2,
    blue: 86,
  ),
  ThreadColor(
    code: "1235",
    catalog: "Madeira Rayon",
    name: "Rose Dust",
    red: 183,
    green: 114,
    blue: 142,
  ),
  ThreadColor(
    code: "1236",
    catalog: "Madeira Rayon",
    name: "Plum",
    red: 71,
    green: 40,
    blue: 53,
  ),
  ThreadColor(
    code: "1238",
    catalog: "Madeira Rayon",
    name: "Dark Orange/Red",
    red: 145,
    green: 51,
    blue: 56,
  ),
  ThreadColor(
    code: "1239",
    catalog: "Madeira Rayon",
    name: "Twilight",
    red: 84,
    green: 81,
    blue: 74,
  ),
  ThreadColor(
    code: "1240",
    catalog: "Madeira Rayon",
    name: "Charcoal",
    red: 118,
    green: 112,
    blue: 91,
  ),
  ThreadColor(
    code: "1241",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 52,
    green: 59,
    blue: 58,
  ),
  ThreadColor(
    code: "1242",
    catalog: "Madeira Rayon",
    name: "Blue Ribbon",
    red: 43,
    green: 38,
    blue: 91,
  ),
  ThreadColor(
    code: "1243",
    catalog: "Madeira Rayon",
    name: "Light Navy",
    red: 17,
    green: 33,
    blue: 81,
  ),
  ThreadColor(
    code: "1244",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 25,
    green: 24,
    blue: 36,
  ),
  ThreadColor(
    code: "1245",
    catalog: "Madeira Rayon",
    name: "Seafoam",
    red: 112,
    green: 206,
    blue: 155,
  ),
  ThreadColor(
    code: "1246",
    catalog: "Madeira Rayon",
    name: "Jade Green",
    red: 0,
    green: 178,
    blue: 167,
  ),
  ThreadColor(
    code: "1247",
    catalog: "Madeira Rayon",
    name: "Turquoise",
    red: 0,
    green: 178,
    blue: 122,
  ),
  ThreadColor(
    code: "1248",
    catalog: "Madeira Rayon",
    name: "Erin Green",
    red: 186,
    green: 232,
    blue: 96,
  ),
  ThreadColor(
    code: "1249",
    catalog: "Madeira Rayon",
    name: "Harvest Green",
    red: 30,
    green: 181,
    blue: 58,
  ),
  ThreadColor(
    code: "1250",
    catalog: "Madeira Rayon",
    name: "Green",
    red: 0,
    green: 135,
    blue: 81,
  ),
  ThreadColor(
    code: "1251",
    catalog: "Madeira Rayon",
    name: "Vibrant Green",
    red: 0,
    green: 158,
    blue: 73,
  ),
  ThreadColor(
    code: "1252",
    catalog: "Madeira Rayon",
    name: "Deep Atlantic",
    red: 38,
    green: 104,
    blue: 109,
  ),
  ThreadColor(
    code: "1253",
    catalog: "Madeira Rayon",
    name: "Toast",
    red: 186,
    green: 117,
    blue: 48,
  ),
  ThreadColor(
    code: "1254",
    catalog: "Madeira Rayon",
    name: "Flamingo",
    red: 249,
    green: 165,
    blue: 137,
  ),
  ThreadColor(
    code: "1255",
    catalog: "Madeira Rayon",
    name: "Gold",
    red: 209,
    green: 191,
    blue: 142,
  ),
  ThreadColor(
    code: "1256",
    catalog: "Madeira Rayon",
    name: "Sirocco",
    red: 190,
    green: 159,
    blue: 80,
  ),
  ThreadColor(
    code: "1257",
    catalog: "Madeira Rayon",
    name: "Orange/Brown",
    red: 188,
    green: 109,
    blue: 10,
  ),
  ThreadColor(
    code: "1258",
    catalog: "Madeira Rayon",
    name: "Light Cocoa",
    red: 140,
    green: 89,
    blue: 51,
  ),
  ThreadColor(
    code: "1259",
    catalog: "Madeira Rayon",
    name: "Dark Brown",
    red: 89,
    green: 63,
    blue: 61,
  ),
  ThreadColor(
    code: "1260",
    catalog: "Madeira Rayon",
    name: "Wheat",
    red: 234,
    green: 221,
    blue: 150,
  ),
  ThreadColor(
    code: "1261",
    catalog: "Madeira Rayon",
    name: "Pastel Lilac",
    red: 186,
    green: 175,
    blue: 211,
  ),
  ThreadColor(
    code: "1263",
    catalog: "Madeira Rayon",
    name: "Sterling",
    red: 168,
    green: 147,
    blue: 173,
  ),
  ThreadColor(
    code: "1264",
    catalog: "Madeira Rayon",
    name: "Thistle",
    red: 198,
    green: 181,
    blue: 196,
  ),
  ThreadColor(
    code: "1266",
    catalog: "Madeira Rayon",
    name: "Turkish Sea",
    red: 48,
    green: 68,
    blue: 181,
  ),
  ThreadColor(
    code: "1267",
    catalog: "Madeira Rayon",
    name: "Banana Yellow",
    red: 242,
    green: 237,
    blue: 158,
  ),
  ThreadColor(
    code: "1270",
    catalog: "Madeira Rayon",
    name: "Glow",
    red: 255,
    green: 216,
    blue: 130,
  ),
  ThreadColor(
    code: "1272",
    catalog: "Madeira Rayon",
    name: "Impala",
    red: 252,
    green: 204,
    blue: 147,
  ),
  ThreadColor(
    code: "1273",
    catalog: "Madeira Rayon",
    name: "Candied Ginger",
    red: 183,
    green: 170,
    blue: 102,
  ),
  ThreadColor(
    code: "1274",
    catalog: "Madeira Rayon",
    name: "Sky Blue",
    red: 155,
    green: 196,
    blue: 226,
  ),
  ThreadColor(
    code: "1275",
    catalog: "Madeira Rayon",
    name: "Cosmic Sky",
    red: 177,
    green: 179,
    blue: 252,
  ),
  ThreadColor(
    code: "1276",
    catalog: "Madeira Rayon",
    name: "Pale Purple",
    red: 102,
    green: 147,
    blue: 188,
  ),
  ThreadColor(
    code: "1277",
    catalog: "Madeira Rayon",
    name: "Blue",
    red: 0,
    green: 48,
    blue: 94,
  ),
  ThreadColor(
    code: "1278",
    catalog: "Madeira Rayon",
    name: "Sunset Orange",
    red: 247,
    green: 127,
    blue: 0,
  ),
  ThreadColor(
    code: "1279",
    catalog: "Madeira Rayon",
    name: "Surf Bleu Medium",
    red: 0,
    green: 153,
    blue: 135,
  ),
  ThreadColor(
    code: "1280",
    catalog: "Madeira Rayon",
    name: "Green Forest",
    red: 0,
    green: 122,
    blue: 94,
  ),
  ThreadColor(
    code: "1281",
    catalog: "Madeira Rayon",
    name: "Atom Red",
    red: 168,
    green: 12,
    blue: 53,
  ),
  ThreadColor(
    code: "1282",
    catalog: "Madeira Rayon",
    name: "Pale Mint Green",
    red: 142,
    green: 226,
    blue: 188,
  ),
  ThreadColor(
    code: "1284",
    catalog: "Madeira Rayon",
    name: "Green Forest",
    red: 0,
    green: 96,
    blue: 86,
  ),
  ThreadColor(
    code: "1286",
    catalog: "Madeira Rayon",
    name: "Dawn Blue",
    red: 230,
    green: 231,
    blue: 228,
  ),
  ThreadColor(
    code: "1287",
    catalog: "Madeira Rayon",
    name: "Metal",
    red: 102,
    green: 109,
    blue: 115,
  ),
  ThreadColor(
    code: "1288",
    catalog: "Madeira Rayon",
    name: "Moon Mist",
    red: 98,
    green: 115,
    blue: 107,
  ),
  ThreadColor(
    code: "1289",
    catalog: "Madeira Rayon",
    name: "Capri",
    red: 84,
    green: 183,
    blue: 198,
  ),
  ThreadColor(
    code: "1290",
    catalog: "Madeira Rayon",
    name: "Blue Spruce",
    red: 0,
    green: 73,
    blue: 79,
  ),
  ThreadColor(
    code: "1291",
    catalog: "Madeira Rayon",
    name: "Mallard Blue",
    red: 0,
    green: 107,
    blue: 119,
  ),
  ThreadColor(
    code: "1292",
    catalog: "Madeira Rayon",
    name: "Light Blue",
    red: 201,
    green: 232,
    blue: 221,
  ),
  ThreadColor(
    code: "1293",
    catalog: "Madeira Rayon",
    name: "M. D. Green",
    red: 0,
    green: 114,
    blue: 114,
  ),
  ThreadColor(
    code: "1294",
    catalog: "Madeira Rayon",
    name: "Dark Aqua Green",
    red: 0,
    green: 140,
    blue: 178,
  ),
  ThreadColor(
    code: "1295",
    catalog: "Madeira Rayon",
    name: "Dark Blue/Green",
    red: 0,
    green: 153,
    blue: 181,
  ),
  ThreadColor(
    code: "1296",
    catalog: "Madeira Rayon",
    name: "Peacock",
    red: 0,
    green: 79,
    blue: 109,
  ),
  ThreadColor(
    code: "1297",
    catalog: "Madeira Rayon",
    name: "Teal",
    red: 0,
    green: 142,
    blue: 211,
  ),
  ThreadColor(
    code: "1298",
    catalog: "Madeira Rayon",
    name: "Navajo Turquoise",
    red: 0,
    green: 140,
    blue: 130,
  ),
  ThreadColor(
    code: "1299",
    catalog: "Madeira Rayon",
    name: "Aqua Pearl",
    red: 71,
    green: 214,
    blue: 193,
  ),
  ThreadColor(
    code: "1301",
    catalog: "Madeira Rayon",
    name: "Bluestone",
    red: 0,
    green: 201,
    blue: 147,
  ),
  ThreadColor(
    code: "1302",
    catalog: "Madeira Rayon",
    name: "Pale Aqua",
    red: 153,
    green: 229,
    blue: 178,
  ),
  ThreadColor(
    code: "1303",
    catalog: "Madeira Rayon",
    name: "Dark Army Green",
    red: 35,
    green: 58,
    blue: 45,
  ),
  ThreadColor(
    code: "1304",
    catalog: "Madeira Rayon",
    name: "Dark Green",
    red: 0,
    green: 73,
    blue: 63,
  ),
  ThreadColor(
    code: "1305",
    catalog: "Madeira Rayon",
    name: "Light Green/Yellow",
    red: 214,
    green: 206,
    blue: 163,
  ),
  ThreadColor(
    code: "1306",
    catalog: "Madeira Rayon",
    name: "Arcadian Green",
    red: 155,
    green: 158,
    blue: 114,
  ),
  ThreadColor(
    code: "1307",
    catalog: "Madeira Rayon",
    name: "Scarlet",
    red: 239,
    green: 43,
    blue: 45,
  ),
  ThreadColor(
    code: "1308",
    catalog: "Madeira Rayon",
    name: "Medium Green/Yellow",
    red: 119,
    green: 124,
    blue: 79,
  ),
  ThreadColor(
    code: "1309",
    catalog: "Madeira Rayon",
    name: "Wild Pink",
    red: 255,
    green: 119,
    blue: 168,
  ),
  ThreadColor(
    code: "1310",
    catalog: "Madeira Rayon",
    name: "Hot Peony",
    red: 170,
    green: 0,
    blue: 102,
  ),
  ThreadColor(
    code: "1311",
    catalog: "Madeira Rayon",
    name: "Pale Purple",
    red: 181,
    green: 145,
    blue: 209,
  ),
  ThreadColor(
    code: "1312",
    catalog: "Madeira Rayon",
    name: "Purple Accent",
    red: 68,
    green: 35,
    blue: 94,
  ),
  ThreadColor(
    code: "1313",
    catalog: "Madeira Rayon",
    name: "Purple Accent",
    red: 68,
    green: 35,
    blue: 89,
  ),
  ThreadColor(
    code: "1315",
    catalog: "Madeira Rayon",
    name: "Pink Mist",
    red: 249,
    green: 178,
    blue: 183,
  ),
  ThreadColor(
    code: "1317",
    catalog: "Madeira Rayon",
    name: "Emily Pink",
    red: 249,
    green: 175,
    blue: 170,
  ),
  ThreadColor(
    code: "1318",
    catalog: "Madeira Rayon",
    name: "Dark Grey",
    red: 59,
    green: 61,
    blue: 63,
  ),
  ThreadColor(
    code: "1319",
    catalog: "Madeira Rayon",
    name: "Hot Pink",
    red: 211,
    green: 107,
    blue: 158,
  ),
  ThreadColor(
    code: "1320",
    catalog: "Madeira Rayon",
    name: "Medium Purple",
    red: 84,
    green: 35,
    blue: 68,
  ),
  ThreadColor(
    code: "1321",
    catalog: "Madeira Rayon",
    name: "Petal Pink",
    red: 255,
    green: 160,
    blue: 191,
  ),
  ThreadColor(
    code: "1322",
    catalog: "Madeira Rayon",
    name: "Dark Purple/Navy",
    red: 43,
    green: 17,
    blue: 102,
  ),
  ThreadColor(
    code: "1323",
    catalog: "Madeira Rayon",
    name: "Yellow",
    red: 232,
    green: 221,
    blue: 33,
  ),
  ThreadColor(
    code: "1328",
    catalog: "Madeira Rayon",
    name: "Shadow Gray",
    red: 157,
    green: 134,
    blue: 103,
  ),
  ThreadColor(
    code: "1329",
    catalog: "Madeira Rayon",
    name: "Dark Olive Green",
    red: 91,
    green: 71,
    blue: 35,
  ),
  ThreadColor(
    code: "1330",
    catalog: "Madeira Rayon",
    name: "Violet",
    red: 102,
    green: 86,
    blue: 188,
  ),
  ThreadColor(
    code: "1334",
    catalog: "Madeira Rayon",
    name: "Mulberry",
    red: 102,
    green: 17,
    blue: 112,
  ),
  ThreadColor(
    code: "1335",
    catalog: "Madeira Rayon",
    name: "Violet",
    red: 102,
    green: 86,
    blue: 185,
  ),
  ThreadColor(
    code: "1336",
    catalog: "Madeira Rayon",
    name: "Dark Brown",
    red: 89,
    green: 63,
    blue: 64,
  ),
  ThreadColor(
    code: "1337",
    catalog: "Madeira Rayon",
    name: "Pussywillow Gray",
    red: 193,
    green: 198,
    blue: 179,
  ),
  ThreadColor(
    code: "1338",
    catalog: "Madeira Rayon",
    name: "Olive Drab",
    red: 183,
    green: 179,
    blue: 138,
  ),
  ThreadColor(
    code: "1339",
    catalog: "Madeira Rayon",
    name: "Pale Gray Green",
    red: 198,
    green: 198,
    blue: 165,
  ),
  ThreadColor(
    code: "1340",
    catalog: "Madeira Rayon",
    name: "Crescent Moon",
    red: 135,
    green: 137,
    blue: 8,
  ),
  ThreadColor(
    code: "1341",
    catalog: "Madeira Rayon",
    name: "K. A. Bronze",
    red: 178,
    green: 107,
    blue: 115,
  ),
  ThreadColor(
    code: "1342",
    catalog: "Madeira Rayon",
    name: "Amber Beige",
    red: 216,
    green: 181,
    blue: 150,
  ),
  ThreadColor(
    code: "1343",
    catalog: "Madeira Rayon",
    name: "Blue Ink",
    red: 43,
    green: 38,
    blue: 94,
  ),
  ThreadColor(
    code: "1344",
    catalog: "Madeira Rayon",
    name: "Beige",
    red: 175,
    green: 158,
    blue: 100,
  ),
  ThreadColor(
    code: "1347",
    catalog: "Madeira Rayon",
    name: "Fools Gold",
    red: 124,
    green: 99,
    blue: 22,
  ),
  ThreadColor(
    code: "1348",
    catalog: "Madeira Rayon",
    name: "Earthen Tan",
    red: 122,
    green: 91,
    blue: 17,
  ),
  ThreadColor(
    code: "1349",
    catalog: "Madeira Rayon",
    name: "Autumn Gold Light",
    red: 244,
    green: 226,
    blue: 132,
  ),
  ThreadColor(
    code: "1350",
    catalog: "Madeira Rayon",
    name: "Green/Gold",
    red: 175,
    green: 168,
    blue: 10,
  ),
  ThreadColor(
    code: "1351",
    catalog: "Madeira Rayon",
    name: "Green Bay",
    red: 0,
    green: 107,
    blue: 84,
  ),
  ThreadColor(
    code: "1352",
    catalog: "Madeira Rayon",
    name: "Black Eyed Susie",
    red: 198,
    green: 160,
    blue: 15,
  ),
  ThreadColor(
    code: "1353",
    catalog: "Madeira Rayon",
    name: "Slate Blue",
    red: 94,
    green: 130,
    blue: 163,
  ),
  ThreadColor(
    code: "1354",
    catalog: "Madeira Rayon",
    name: "Cerise",
    red: 224,
    green: 7,
    blue: 71,
  ),
  ThreadColor(
    code: "1356",
    catalog: "Madeira Rayon",
    name: "Rose Beige",
    red: 204,
    green: 175,
    blue: 183,
  ),
  ThreadColor(
    code: "1357",
    catalog: "Madeira Rayon",
    name: "D. H. Green",
    red: 66,
    green: 71,
    blue: 22,
  ),
  ThreadColor(
    code: "1358",
    catalog: "Madeira Rayon",
    name: "Dark Brown",
    red: 132,
    green: 73,
    blue: 73,
  ),
  ThreadColor(
    code: "1359",
    catalog: "Madeira Rayon",
    name: "Pollen Gold",
    red: 216,
    green: 181,
    blue: 17,
  ),
  ThreadColor(
    code: "1360",
    catalog: "Madeira Rayon",
    name: "Country Blue",
    red: 119,
    green: 150,
    blue: 178,
  ),
  ThreadColor(
    code: "1361",
    catalog: "Madeira Rayon",
    name: "Medium Grey",
    red: 96,
    green: 96,
    blue: 91,
  ),
  ThreadColor(
    code: "1362",
    catalog: "Madeira Rayon",
    name: "Light Midnight",
    red: 53,
    green: 63,
    blue: 91,
  ),
  ThreadColor(
    code: "1363",
    catalog: "Madeira Rayon",
    name: "Purple Cloud",
    red: 155,
    green: 163,
    blue: 183,
  ),
  ThreadColor(
    code: "1364",
    catalog: "Madeira Rayon",
    name: "Lake Blue",
    red: 38,
    green: 84,
    blue: 124,
  ),
  ThreadColor(
    code: "1365",
    catalog: "Madeira Rayon",
    name: "Light Midnight",
    red: 53,
    green: 63,
    blue: 94,
  ),
  ThreadColor(
    code: "1366",
    catalog: "Madeira Rayon",
    name: "Violet Blue",
    red: 51,
    green: 40,
    blue: 117,
  ),
  ThreadColor(
    code: "1367",
    catalog: "Madeira Rayon",
    name: "Black",
    red: 20,
    green: 33,
    blue: 64,
  ),
  ThreadColor(
    code: "1368",
    catalog: "Madeira Rayon",
    name: "Blue Ribbon",
    red: 0,
    green: 38,
    blue: 73,
  ),
  ThreadColor(
    code: "1369",
    catalog: "Madeira Rayon",
    name: "Kelly",
    red: 61,
    green: 142,
    blue: 51,
  ),
  ThreadColor(
    code: "1370",
    catalog: "Madeira Rayon",
    name: "Evergreen",
    red: 2,
    green: 73,
    blue: 48,
  ),
  ThreadColor(
    code: "1371",
    catalog: "Madeira Rayon",
    name: "Green",
    red: 0,
    green: 89,
    blue: 81,
  ),
  ThreadColor(
    code: "1372",
    catalog: "Madeira Rayon",
    name: "Scholastic",
    red: 252,
    green: 191,
    blue: 73,
  ),
  ThreadColor(
    code: "1373",
    catalog: "Madeira Rayon",
    name: "Ozone",
    red: 96,
    green: 175,
    blue: 221,
  ),
  ThreadColor(
    code: "1374",
    catalog: "Madeira Rayon",
    name: "Warm Wine",
    red: 102,
    green: 30,
    blue: 46,
  ),
  ThreadColor(
    code: "1375",
    catalog: "Madeira Rayon",
    name: "Pale Purple",
    red: 102,
    green: 147,
    blue: 185,
  ),
  ThreadColor(
    code: "1376",
    catalog: "Madeira Rayon",
    name: "Salem Blue",
    red: 0,
    green: 56,
    blue: 107,
  ),
  ThreadColor(
    code: "1377",
    catalog: "Madeira Rayon",
    name: "Neon Green",
    red: 96,
    green: 198,
    blue: 89,
  ),
  ThreadColor(
    code: "1378",
    catalog: "Madeira Rayon",
    name: "Sunkist",
    red: 247,
    green: 73,
    blue: 2,
  ),
  ThreadColor(
    code: "1379",
    catalog: "Madeira Rayon",
    name: "Coral",
    red: 249,
    green: 96,
    blue: 58,
  ),
  ThreadColor(
    code: "1380",
    catalog: "Madeira Rayon",
    name: "Parrot",
    red: 0,
    green: 175,
    blue: 153,
  ),
  ThreadColor(
    code: "1381",
    catalog: "Madeira Rayon",
    name: "Cabernet",
    red: 147,
    green: 22,
    blue: 56,
  ),
  ThreadColor(
    code: "1382",
    catalog: "Madeira Rayon",
    name: "Dark Maroon",
    red: 79,
    green: 33,
    blue: 58,
  ),
  ThreadColor(
    code: "1383",
    catalog: "Madeira Rayon",
    name: "Cherrystone",
    red: 170,
    green: 0,
    blue: 79,
  ),
  ThreadColor(
    code: "1384",
    catalog: "Madeira Rayon",
    name: "Wine",
    red: 125,
    green: 48,
    blue: 67,
  ),
  ThreadColor(
    code: "1385",
    catalog: "Madeira Rayon",
    name: "DKST Burgandy",
    red: 122,
    green: 16,
    blue: 35,
  ),
  ThreadColor(
    code: "1386",
    catalog: "Madeira Rayon",
    name: "Plum",
    red: 71,
    green: 40,
    blue: 56,
  ),
  ThreadColor(
    code: "1387",
    catalog: "Madeira Rayon",
    name: "Light Grape",
    red: 127,
    green: 102,
    blue: 137,
  ),
  ThreadColor(
    code: "1388",
    catalog: "Madeira Rayon",
    name: "Medium Purple",
    red: 84,
    green: 35,
    blue: 71,
  ),
  ThreadColor(
    code: "1389",
    catalog: "Madeira Rayon",
    name: "Brushed Burgundy",
    red: 109,
    green: 33,
    blue: 63,
  ),
  ThreadColor(
    code: "1390",
    catalog: "Madeira Rayon",
    name: "Dark Green",
    red: 0,
    green: 79,
    blue: 66,
  ),
  ThreadColor(
    code: "1391",
    catalog: "Madeira Rayon",
    name: "Green Forest",
    red: 38,
    green: 102,
    blue: 89,
  ),
  ThreadColor(
    code: "1392",
    catalog: "Madeira Rayon",
    name: "Harbor Green",
    red: 79,
    green: 109,
    blue: 94,
  ),
  ThreadColor(
    code: "1393",
    catalog: "Madeira Rayon",
    name: "Hedge",
    red: 63,
    green: 73,
    blue: 38,
  ),
  ThreadColor(
    code: "1394",
    catalog: "Madeira Rayon",
    name: "Green/Yellow",
    red: 73,
    green: 89,
    blue: 40,
  ),
  ThreadColor(
    code: "1395",
    catalog: "Madeira Rayon",
    name: "Dark Forest Green",
    red: 35,
    green: 68,
    blue: 53,
  ),
  ThreadColor(
    code: "1396",
    catalog: "Madeira Rayon",
    name: "Water Lilly",
    red: 84,
    green: 104,
    blue: 86,
  ),
  ThreadColor(
    code: "1397",
    catalog: "Madeira Rayon",
    name: "Winter Pine",
    red: 0,
    green: 68,
    blue: 56,
  ),
];
